### ISSUE TITLE
Add ability to specify container name to impersonate

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#100]
Today, we pick up the first container in the pod we impersonate. This might not be the case for service mesh setups or more elaborate setups, so we need to let the user specify container name and maybe add a warning when we just assume and use the first one.
Also, we should consider ignoring linkerd/envoy containers by default (unless specified?)
Edit:

Status:
- [x]  @camerondurham added basic functionality controlled by env var.
- [x]  Need to expose that functionality from the cli
- [x]  ^^ VS Code Extension

**Comment by camerondurham** [comment]
I'd like to work on this issue. Thanks!

**Comment by aviramha** [comment]
> I'd like to work on this issue. Thanks!

Great! Let us know if you need any help 😊

**Comment by aviramha** [comment]
Thanks @camerondurham . I'm updating the ticket to reflect what needs to be added.

**Comment by aviramha** [comment]
@camerondurham Do you you wish to contribute the other open items as well? (making sure the assigned state is correct ;) )

**Comment by camerondurham** [comment]
Hey @aviramha, I'm interested in finishing the other tasks as well if that's alright! I was running into a bug with the extension selection so sending the draft PR for now and can provide more context in `#dev` too...

**Comment by aviramha** [comment]
That's more than alright! Feel free to consult with us on `#dev`

**Comment by aviramha** [comment]
@camerondurham
Hey, are you still working on this issue? No pressure :) Just so we can mark this as available for others if not.

**Comment by camerondurham** [comment]
@aviramha Following up from convo in`#dev`.

I can help with minor changes to fix existing features added but if it's more than a couple days work I probably won't have time.

What I've done so far:

1. (PR #182) Added a flag to the CLI in (here: https://github.com/metalbear-co/mirrord/pull/182/files#diff-e7e961df0a87503db868f6db719d10b5f06c962d7b1939079055514a118844bc)
2. (PR #185) Added another quickselect window to the VSCode extension when starting to debug (here: https://github.com/metalbear-co/mirrord/pull/185/files#diff-71da5b8ace00ececa231c3f58ec52d2876a05efaf23404acf1c24cbebbad2bea) 

Thanks for following up, I should've asked this sooner!

**Comment by aviramha** [comment]
Thanks @camerondurham - My fault for not tracking the issues/linking to this.
