### ISSUE TITLE
Traffic steal

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#101]
Allow user to "steal" incoming traffic from the remote pod.
First version of this feature will steal all incoming traffic.

**Comment by aviramha** [comment]
I investigated how linkerd works as it's a good model on what we want to achieve - when we intercept connections we want to detect and understand if we want to "steal" it and later on we want to steal only specific requests based on filter.
Initially, I believed we could just use components from linkerd2-proxy codebase but I realized it was too coupled for its use case, so now my goal is to implement our own stuff using hyper.

**Comment by eyalb181** [comment]
"Detect and understand if we want to "steal" it" - based on what?
