### ISSUE TITLE
Rider

### ISSUE THREAD

**Issue by crabstars** [metalbear-co/mirrord#1012]
### Bug Description

I can install mirrord over the plugins in Rider, but it the icon isnt showing up like in Pycharm 

### Steps to Reproduce

1. Install mirrord plugin in Rider

### Your operating system and version

Linux

### Local process

no local process

**Comment by aviramha** [comment]
Thanks for reporting. Unfortunately, we don't have support for Rider at the moment. 
I checked out how we can get this done, and it seems that the Rider SDK is a bit non existent so this might take time to solve. I hope we can prioritize it in few weeks time.

**Comment by aviramha** [comment]
https://github.com/rebel-000/CommandlineArgumentsWCheckboxes/blob/main/src/main/kotlin/com/github/rebel000/cmdlineargs/extensions
might be useful
