### ISSUE TITLE
flush existing connections on steal

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1029]
### Bug Description

on calico k3s we found out that steal doesn't work until established connections are reset, probably due to different behavior in that setup.
possible solution is to have conntrack binary in our image and call `conntrack -F` on each stolen port after adding the rule.

**this should be controlled via env var, at least for the first version, then decide if to make it enabled by default **

### Steps to Reproduce

calico + k3s

### Your operating system and version

n/a

### Local process

n/a

**Comment by aviramha** [comment]
This fixed their issue. Need to decide if we want is by default.

**Comment by eyalb181** [comment]
@meowjesty Discussed this with @aviramha , can you please change it to default to `true`?
