### ISSUE TITLE
mirrord doesn't bind to standard gRPC port on Node process

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#1047]
### Bug Description

When running a Node process, mirrord can't bind to the standard gRPC port. This happened in VS Code.

### Steps to Reproduce

See description

### Your operating system and version

MacOS

### Local process

Node

**Comment by aviramha** [comment]
It fails with an error that it couldn't bind to 1 of resolved addresses.

**Comment by DmitryDodzin** [comment]
Node code does a dns style lookup on the result of getsockname to check the compatability or something but it seems to still work even if the error message is printed,
It can be removed if the getsockname will return a value compatible to the original requested example:

bind on '127.0.0.1:50051' and getsockname returns 127.0.0.1:54123 will result in the No address added out of total 1 resolved error, where the 54123 is the new port from our bind detour

bind on '127.0.0.1:50051' and getsockname returns 10.10.0.6:50051 will also result in the same error

bind on 127.0.0.1:50051 and getsockname returns 0.0.0.0:50051 or bind on 10.10.0.6:50051 and getsockname returns 127.0.0.1:50051 will result in a no error

**Comment by aviramha** [comment]
What's the solution you have in mind?

**Comment by eyalb181** [comment]
Deprioritizing this since it doesn't affect functionality, just logs.

**Comment by eyalb181** [comment]
Reprioritizing! User does not receive incoming traffic.
