### ISSUE TITLE
Remove the word "test" from all tests.

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1065]
All of our tests are called `test_...`. Seems redundant.
Since tests are marked with `#[rstest]`, we don't need to mark them with the word "test" at the beginning of their name.

I suggest we just call them as what they are testing, so if a test is testing that a feature like http mirroring works, then we just call it `http_mirroring`, and if it verifies some invariant, then use the invariant as the name, e.g. `tmp_files_are_bypassed`.

What do you think?

**Comment by aviramha** [comment]
Sounds good!
