### ISSUE TITLE
Target selection is spawned twice when debugging with npx

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord#1072]
### Bug Description

The target selection can be seen twice when debugging a typescript file using npx

refer #1061 

### Steps to Reproduce

start debugging a typescript file with this config:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Control plane backend",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceFolder}",            
            "runtimeExecutable": "npx",
            "runtimeArgs": [
                "ts-node",
                "main.ts"
            ],
         }
    ]
}
```

### Your operating system and version

Darwin mehuls-air.lan 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101 arm64

### Local process

/opt/homebrew/bin/npx ts-node main.ts

### Local process version

mehularora@mehuls-air ts-test % node -v v19.6.0, mehularora@mehuls-air ts-test % npx -v 9.4.0

**Comment by aviramha** [comment]
Fixed with #1080 #1081
