### ISSUE TITLE
Internal proxy hangs with error when mirrord doesn't load into the process

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord#1073]
### Bug Description

Internal proxy hangs with error when mirrord doesn't load into the process:
```
... failure
mehularora@Mehuls-MacBook-Air mirrord % Error: 
  × Internal proxy error: FirstConnectionTimeout
  ╰─▶ Couldn't accept connection before timeout
```

### Steps to Reproduce

target/debug/mirrord exec --target pod/py-serv-deployment-5c57fbdc98-pdbn4 --agent-ttl 100  -- sh   

### Your operating system and version

Darwin mehuls-air.lan 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101 arm64

### Local process

mehularora@mehuls-air ts-test % file $(which sh) /bin/sh: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64 - Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e - Mach-O 64-bit executable arm64e] /bin/sh (for architecture x86_64):      Mach-O 64-bit executable x86_64 /bin/sh (for architecture arm64e):      Mach-O 64-bit executable arm64e

**Comment by aviramha** [comment]
What would you consider as the correct behavior?

**Comment by infiniteregrets** [comment]
The correct behavior would be for the internal proxy to terminate along with the mirrord process if it fails. An approach I had in mind was that the child keeps reading an fd, and waits for an EOF i.e. when parent dies/ killed the child knows it read an EOF and can exit itself. Perhaps would be better to use pipes in this case?

**Comment by aviramha** [comment]
Related to #1761 - unfortunately, I couldn't find a solution that would work for extension.
