### ISSUE TITLE
Specify custom names for agent image in E2E tests

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord#108]
The agent image once built is tagged as `test:latest`, this results in an `Elapsed` error if the image is not loaded to minikube by any chance, so we should not be hardcoding this. It would be nice to be able to specify the image as an environment variable  and read from it, and do the same in the CI.

**Comment by eyalb181** [comment]
I don't follow your reasoning here, what scenario are you trying to avoid? When would the image not be loaded to minikube - doesn't the E2E flow handle this?
