### ISSUE TITLE
Mirrord launches twice on VSCode

### ISSUE THREAD

**Issue by DmitryDodzin** [metalbear-co/mirrord#1080]
### Bug Description

When debugging in VSCode with mirrord enabled the user will be prompted twice to select a target for no apparent reason

### Steps to Reproduce

1. Debug nodejs in VSCode with mirrord ext enabled

### Your operating system and version

macOs 13.2 (22D49)

### Local process

node ./tests/node-e2e/app.js

**Comment by aviramha** [comment]
Could be related to #1072
