### ISSUE TITLE
Support unix sockets

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1105]
Support making outgoing connections from to unix sockets on the remote pod.

Requested by customer who's application reads from the containerd socket.

**Comment by aviramha** [comment]
Adding more information, as I initially started implementing it and have some thoughts:

1. This should be part of the "outgoing" configuration, a field named `unix` (feel free to suggest other) that accepts path patterns to connect remotely.
2. This should leverage the TCP outgoing handler, as it is pretty similar to it in terms of everything (connect, send/recv).
3. Above point is debatable, but I don't really think that splitting and complicating the code makes sense.

**Comment by t4lz** [comment]
> 2\. This should leverage the TCP outgoing handler

Does this mean that for now we are only going to support TCP over unix sockets, not UDP?

**Comment by aviramha** [comment]
It's possible to have UDP over unix sockets?
