### ISSUE TITLE
can't connect to mongo Go with CGO_ENABLED=0

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1107]
### Bug Description

When building with `CGO_ENABLED=0`, mongo fails to connect with error
```
timed out while checking out a connection from connection pool: context deadline exceeded; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 1
```

### Steps to Reproduce

mongo + go

### Your operating system and version

macOS x64

### Local process
using GoLand
go built

**Comment by t4lz** [comment]
The user's program is probably being statically linked when `CGO_ENABLED=0` and then the layer can't load into the process, no?

**Comment by aviramha** [comment]
> The user's program is probably being statically linked when `CGO_ENABLED=0` and then the layer can't load into the process, no?

There's no such thing as static on macOS..

**Comment by scirin** [comment]
@aviramha This is an error with MongoDB driver or server configuration.
Could you please try increasing the connection pool size to see if that resolves the issue?

+Please paste the logs

**Comment by aviramha** [comment]
Thanks @scirin - it might look like issue with mongoDB or server configuration, but the remote pod that is being mirrord does work, which means that mirrord fails to do some of it's underlying logic :)

**Comment by f-blass** [comment]
I have no problems with macOS and Go+MongoDB. Not sure if this helps, but it looks like there are working combinations. 

I am using:

- M1 MacBook with macOS 13.2.1
- Go 1.19/1.20
- mongodb library `go.mongodb.org/mongo-driver` v1.11.2
- MongoDB version 4.2.23
- CGO_ENABLED=0

**Comment by aviramha** [comment]
@f-blass Thank you! Did you use from CLI or IDE?

**Comment by f-blass** [comment]
I tested with the IntelliJ plugin version 3.26+ 
At least I can confirm that it is working with version 3.28.1 right now.

**Comment by scirin** [comment]
I am using M1 as well and cannot reproduce the error, could be something with the x86_64 architecture

**Comment by aviramha** [comment]
> I am using M1 as well and cannot reproduce the error, could be something with the x86_64 architecture

Could be though I suspect it's something related to local ip / network.
Thanks for the help both of you!

**Comment by eyalb181** [comment]
Might have been fixed, needs to be retested.
