### ISSUE TITLE
IntelliJ IDEA Ultimate hangs when running with mirrord and builder is set to Gradle.

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1120]
### Bug Description

https://canary.discord.com/channels/933706914808889356/1076001607512227870/1078055687948599337

### Steps to Reproduce

1. Configure builder to Gradle.
2. Enable mirrord.
3. Start any program.

### Your operating system and version

macOS 

### Local process

Java/Kotlin

**Comment by aviramha** [comment]
I managed to fix it by locking the writeThread only when needed but mirrord isn't loaded.
I am trying to see if we can fix loading into Gradle or we'll just disable it for teh moment.

**Comment by aviramha** [comment]
Fixed this as well loading into Gradle launched processes (yay..)
