### ISSUE TITLE
A way to configure local:remote port mapping

### ISSUE THREAD

**Issue by aeb-dev** [metalbear-co/mirrord#1129]
Currently mirrord expects the local application to use the same port as remote one. Most of the time we are using separate ports for local and remote. A way for configuring it inside mirrord.json would simplify our process to use mirrord. 

example:
```json
{
    "portMappings": {
        "http": "5000:80",
        "https": "5001:443"
    }
}
```

**Comment by aviramha** [comment]
Thank you. We will prioritize it.
We'll probably name it `port_mappings` and under the `incoming` feature.

**Comment by f-blass** [comment]
This can be configured under [Feature>Network>Incoming](https://mirrord.dev/docs/overview/configuration/#feature_network_anyOf_i1_incoming), correct? 
Could you please add this to the docs? Thanks! :)

**Comment by aviramha** [comment]
Yes! Thanks for letting us know.
