### ISSUE TITLE
fail to debug python with vscode

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1145]
The debugger script connects to the remote pod so it fails. We need a better mechanism for determining and excluding debugger ports.

**Comment by infiniteregrets** [comment]
for more context, we just i"assume" a particular higher range for debuggers and ignore them internally for both vscode and intellij, hopefully https://github.com/microsoft/vscode-discussions/discussions/499 can provide some insight..

and note, on intellij, we can get the debugger port like so:
```
return StreamEx.of(DebuggerManagerEx.getInstanceEx(project).getSessions())
  .map(s -> s.getDebugEnvironment().getRemoteConnection())
  .map(c -> c.getDebuggerAddress())
  .toSet();
```

**Comment by infiniteregrets** [comment]
Someone replied to the discussion and said the port is not exposed for vsocde, however, I have an idea, if we can get the process id of the parent process i.e. the debugger process and then list the connections and get the port number from there.. on linux i believe we can use something like `/proc/pid/net/tcp` to do so, but not sure about macos. wdyt @aviramha
