### ISSUE TITLE
Not working with pyenv when FS ops are on.

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1146]
### Bug Description

Mirrord does not load into the python process.

### Steps to Reproduce

```
mirrord exec -c --steal --target deployment/upper-deployment python3 upper/main.py
```
Does not work, but 
```
mirrord exec -c --steal --target deployment/upper-deployment --fs-mode local python3 upper/main.py
```
does.

Where:
```
which python3
/Users/t4lz/.pyenv/shims/python3
```

### Your operating system and version

macOS 13.1

### Local process

python3

**Comment by aviramha** [comment]
@t4lz I think this was solved with one of the default changes we've done?

**Comment by t4lz** [comment]
> @t4lz I think this was solved with one of the default changes we've done?

Yes this works now 🥳
