### ISSUE TITLE
propogate steal issues to layer/cli

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1163]
Follow up on issues where steal iptables rules fail due to missing kernel modules, user has no good way of understanding that it happened.
I think we should add a message that can be sent from daemon to layer that will be printed as warning/error when an issue occurs and it's not as part of a response (like in the case of steal/mirror where listen has no response)

**Comment by Razz4780** [comment]
@aviramha I made a PR to fix this, but it does not cover the errors that can occur before accepting any client connection in the agent. Should this part also be covered here? For example, we could fetch logs from the agent container if it fails to initialize.
