### ISSUE TITLE
outdated doc for flag --no-fs

### ISSUE THREAD

**Issue by JunchengL** [metalbear-co/mirrord#1174]
Hi,

I am following mirrord [doc](https://mirrord.dev/docs/overview/real-world-example/) to do some tests.

It seems that in the command with flag `--no-fs ` in `Outgoing Traffic` section is no longer supported, as it is removed in release `3.20.0`

Im wondering what is the good command to launch with the latest version of mirrord for this use case?

Thanks

**Comment by JunchengL** [comment]
> Hey!
> 
> Sorry about that. `--fs-mode local` would be the new flag. Leaving open to prioritize fixing the docs.

thank you !

**Comment by aviramha** [comment]
Fixed. Thank you!
