### ISSUE TITLE
Update gethostname detour to return null-terminated hostname

### ISSUE THREAD

**Issue by DmitryDodzin** [metalbear-co/mirrord#1189]
Like @artem-collectai mentioned in https://github.com/metalbear-co/mirrord/commit/80b6621c8bb7a1b0875b4b6864376b57d31cebac#r104254690 `gethostname_detour` should use `.as_bytes_with_nul()` to be inline with gethostname(2)

**Comment by aviramha** [comment]
closed via #1190
