### ISSUE TITLE
Make an "enable mirrord"/"disable mirrord" touch bar button for the vscode extension on Mac.

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1195]
I think it would be a cool little enhancement if it's not too complicated to add.

This looks like it could be relevant: https://code.visualstudio.com/api/references/contribution-points#contributes.menus

**Comment by aviramha** [comment]
Touchbar is discontinued so I don't support adding this

**Comment by eyalb181** [comment]
Is it? The M2s have them

**Comment by aviramha** [comment]
> Is it? The M2s have them

Only some models AFAIK and it seems that the direction is towards removal

**Comment by eyalb181** [comment]
Don't see us doing this in the foreseeable future, so closing for now.
