### ISSUE TITLE
Flaky go-e2e-dns on Go 1.20 Linux

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1206]
Seems that some sort of a deadlock/timeout is happening in this test.
https://github.com/metalbear-co/mirrord/actions/runs/4483891847
https://github.com/metalbear-co/mirrord/actions/runs/4483668126

**Comment by aviramha** [comment]
One of the issues here is that the test hangs forever, so another thing we need to do is to add timeouts.
I am adding timeout to the test but have created https://github.com/la10736/rstest/issues/190 so we can cover all tests.

**Comment by meowjesty** [comment]
Looks like this fix wasn't enough, as we still get flaky behavior ([CI run](https://github.com/metalbear-co/mirrord/actions/runs/4503838416/attempts/2)).

**Comment by t4lz** [comment]
> Looks like this fix wasn't enough, as we still get flaky behavior ([CI run](https://github.com/metalbear-co/mirrord/actions/runs/4503838416/attempts/2)).

So far I can't reproduce this timeout flake, but there is an occasional [go crash](https://github.com/t4lz/mirrord/actions/runs/4594110601/jobs/8117308950#step:36:2163). That crash looks like it might be related to issue #380.

**Comment by aviramha** [comment]
I think it's the same - just for some reason in the e2e it doesn't detect the crash and waits for it forever

**Comment by t4lz** [comment]
> in the e2e it doesn't detect the crash and waits for it forever

Also the go crash I sent is in the E2E test.

**Comment by aviramha** [comment]
I'm not sure if this had stopped happening or we disabled the test?

**Comment by Razz4780** [comment]
The test is enabled, has not failed in the last couple days
