### ISSUE TITLE
A lot of drama on Ctrl+C

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1232]
### Bug Description

When stopping a process that the mirrord layer is loaded to, there are 2 error logs, a printed error message, and a rust panic.

Maybe we could reduce it down to a single message/log.
I suggest we also add an E2E regression test where we verify that only the expected message/log is emitted.

### Steps to Reproduce

I'm testing with this little `server.ts`:
```typescript
import express, { Express, Request, Response } from 'express';

const app: Express = express();
const port = 80;

app.get('/', (req: Request, res: Response) => {
  res.send('Express + TypeScript Server');
});

app.listen(port, () => {
  console.log(`⚡️[server]: Server is running at http://localhost:${port}`);
});
```
You might need to install some dependencies, idk.

Then, run:
```
MIRRORD_PROGRESS_MODE=off mirrord exec -c --target deployment/py-serv-deployment npx ts-node wat.ts
```
And after seeing `⚡️[server]: Server is running at http://localhost:80`, press Ctrl + C.

### Relevant Logs

```shell
C2023-03-29T09:39:41.259571Z ERROR ThreadId(04) mirrord_layer::connection: agent disconnected
2023-03-29T09:39:41.260381Z ERROR ThreadId(04) mirrord_layer: agent connection lost
mirrord has encountered an error and is now exiting.
thread 'tokio-runtime-worker' panicked at 'explicit panic', mirrord/layer/src/lib.rs:787:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Your operating system and version

macOS 13.2.1

### Local process

/opt/homebrew/bin/npx: a /usr/bin/env node script text executable, ASCII text

### Local process version

9.5.1

**Comment by aviramha** [comment]
This started happening with the int proxy. It looks like the first to receive the signal is the int proxy then it dies then it causes the agent to prematurely disconnect. I guess intproxy should wait *somehow* for parent to die?
