### ISSUE TITLE
nslookup does not find services on the cluster

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1236]
### Bug Description

When executing `nslookup <SERVICE_NAME>` with mirrord, it is not found, but it is when executing directly on the pod.

### Steps to Reproduce

1. `kubectl config use-context gke_mirrord-test_europe-central2_istio-demo` (if you have access. If you don't have access to that cluster, please just use any other cluster and change the resource names accordingly in the next steps , the issue would probably also reproduce there).
2. `MIRRORD_PROGRESS_MODE=off mirrord exec -c --target deployment/busybox nslookup details` 

> ```
> Server:		213.57.2.5
> Address:	213.57.2.5#53
> 
> ** server can't find details: NXDOMAIN
> ```

3. `kubectl exec --stdin --tty busybox-58d584f97b-md696 -- nslookup details`

> ```
> 
> Server:		10.120.0.10
> Address:	10.120.0.10:53
> 
> Name:	details.default.svc.cluster.local
> Address: 10.120.0.246
> 
> ** server can't find details.cluster.local: NXDOMAIN
> 
> 
> ** server can't find details.svc.cluster.local: NXDOMAIN
> 
> ** server can't find details.cluster.local: NXDOMAIN
> 
> ** server can't find details.svc.cluster.local: NXDOMAIN
> 
> ** server can't find details.google.internal: NXDOMAIN
> 
> ** server can't find details.google.internal: NXDOMAIN
> 
> ** server can't find details.europe-central2-c.c.mirrord-test.internal: NXDOMAIN
> 
> ** server can't find details.europe-central2-c.c.mirrord-test.internal: NXDOMAIN
> 
> ** server can't find details.c.mirrord-test.internal: NXDOMAIN
> 
> ** server can't find details.c.mirrord-test.internal: NXDOMAIN
> 
> command terminated with exit code 1
> ```

You can see that in 2., with mirrord, nothing was found, and in 3., running directly on a container in the cluster, an address was found.

### Your operating system and version

macOS 13.2.1

### Local process

/usr/bin/nslookup: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e] /usr/bin/nslookup (for architecture x86_64):	Mach-O 64-bit executable x86_64 /usr/bin/nslookup (for architecture arm64e):	Mach-O 64-bit executable arm64e

### Local process version

9.10.6

### Additional Info

From `man nslookup`:

> macOS NOTICE
>        The nslookup command does not use the host name and address resolution or the DNS query routing mechanisms used by other processes running on macOS.  The results of name or address queries printed by nslookup may differ from
>        those found by other processes that use the macOS native name and address resolution mechanisms.  The results of DNS queries may also differ from queries that use the macOS DNS routing library.
> 

Seems like nslookup might require special treatment to support and I don't know if it's important.
Opened this issue anyways so that it is documented and can be prioritised.

**Comment by eyalb181** [comment]
Might be resolved by #1776
