### ISSUE TITLE
Can't execute

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#125]
### Bug Description

mirrord-cli in release (downloaded from the script/compiled binary) gets killed when executing the process on macOS

### Steps to Reproduce

1. download release build
2. `mirrord exec --pod-name test-pod python`
3. kill

### Backtrace

```shell
no backtrace :(
```

### Your operating system and version

21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### Local process

python

**Comment by aviramha** [comment]
This seems to happen only when extracting to `$TMPDIR` but not when using `/tmp/` for some reason.

**Comment by aviramha** [comment]
Somehow it doesn't happen to me again, there's something very odd going on. Let's keep this open in case someone else starts having it.

**Comment by JunchengL** [comment]
Hi, I am testing mirrord with GKE cluster and I have the same issue on version 2.2.0 with the same os and kernel version.
And when I use version 2.2.1 I have another error
```
2022-06-16T15:24:01.685723Z ERROR kube_client::client::builder: failed with error error trying to connect: presented server name type wasn't supported
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: HyperError(hyper::Error(Connect, Custom { kind: Other, error: Custom { kind: InvalidData, error: UnsupportedNameType } }))', mirrord-layer/src/pod_api.rs:25:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5 
```

**Comment by aviramha** [comment]
@JunchengL Thanks for reporting! This seems to be because the cluster host is non standard (IP or not TLS?). You can add the flag `-c` to the `mirrord exec` so it will accept this anomaly. 
Let me know if this works for you and if so we'll create an issue to provide better error and also document it :)

**Comment by JunchengL** [comment]
It is working with -c, I can continue my test. thanks a lot !
My hostname pattern is this one `my-mirrord-test`

**Comment by JunchengL** [comment]
> Great. We'll work on documenting that. Regarding the hostname - when you run `kubectl config view` and look at the specific cluster, the server field is not an IP?

ah I have misunderstood. The server filed is an IP with something like this:
`server: https://x.x.x.x`
