### ISSUE TITLE
Don't send unnecessary zero bytes from agent to layer on file read 

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1254]
Saw this log on some CI run:
```
File(Read(Ok(ReadFileResponse { bytes (length): 65536, read_amount: 0 })))
```

Seems like [in the agent](https://github.com/metalbear-co/mirrord/blob/c3174a1462c11151742bd58d19bffcf08ab6aabf/mirrord/agent/src/file.rs) whenever we create a `ReadFileResponse` we include a vector with the full size of the buffer, even though we could easily just truncate it and only send the read bytes.

This is probably not a big problem, but is a bit wasteful and we could just avoid sending all of those zeros over the net between the agent and the layer for no reason.

**Comment by scirin** [comment]
Assign this to me!
