### ISSUE TITLE
`Invalid message: "python"[0] must be str` on vscode when running a fastapi app with mirrord

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1271]
### Bug Description

Getting error message in a pop-up when trying to run on vscode

### Steps to Reproduce

Run app on vscode

### Your operating system and version

MacOS

### Local process

python

### Additional Info

New in version 3.34.0 of mirrord :(

**Comment by jochman** [comment]
I can confirm that the issue is fixed.
ver 3.35.0
