### ISSUE TITLE
Reconsidering the way background tasks are handled

### ISSUE THREAD

**Issue by Razz4780** [metalbear-co/mirrord#1287]
Right now mirrord agent uses 3 global background tasks (dns, sniffer and stealer) and 2 per-client background tasks (tcp and udp). All tasks are run in their own tokio runtimes constructed with `Builder::new_multi_thread`, which spawns `nproc` threads. Main function is also run in a multi-threaded runtime. That means that agent uses `(4 + clients) * nproc` threads. Maybe we could consider using single-threaded runtimes?

**Comment by eyalb181** [comment]
Seems premature at this point - not something our users will really feel the effect of

**Comment by Razz4780** [comment]
> Seems premature at this point - not something our users will really feel the effect of?

Just something I noticed when working with the agent. The change would be very simple - using [different](https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.new_current_thread) tokio runtime flavor.

**Comment by Razz4780** [comment]
Closed with #1497
