### ISSUE TITLE
Error thrown when using HTTP filter

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#1302]
### Bug Description

A user ran mirrord with an HTTP filter, in both the CLI and Goland, and got this error:
```
502 Bad Gateway
mirrord tried to forward the request to the local application and got hyper::Error(Canceled, "connection was not ready")
```

### Steps to Reproduce

N/A

### Your operating system and version

N/A

### Local process

N/A

### Additional Info

https://discord.com/channels/933706914808889356/1096092286821089461

**Comment by aviramha** [comment]
Fixed with #1340 according to user on Discord.
