### ISSUE TITLE
Support mirroring existing sessions

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1317]
Mirroring works only for new TCP sessions.
We can make it work with ongoing TCP sessions by finding HTTP requests and starting to stream from there.
Should resolve #397

**Comment by sunng87** [comment]
It would be nice to have this supported. This makes mirrord more straight forward with how the doc describes it.

**Comment by aviramha** [comment]
> I just needed this for already established websocket connections

We won't be able to support mirroring established websocket connections because those are stateful connections

**Comment by aviramha** [comment]
> Is it doable for stealing?

It already works this way for stealing.

**Comment by meowjesty** [comment]
With #1887 this should now work if your session is using HTTP!

There is a small caveat in the implementation:

Currently only handle it if the packet data starts with valid HTTP bytes, something along the lines of: `["GET / HTTP"]`. It fails to detect HTTP traffic if the bytes are "messed up", e.g. `["some other data \0 GET / HTTP]`. There is an implicit assumption here that we're going to be hitting the common case of seeing a "well-behaved" packet most of the time.

- A quick fix to this, if it ever poses a problem:

Perform HTTP detection on the packet, and move the bytes' cursor to the start of the HTTP part, example:

```
["some other data \0 GET / HTTP]
 /\                 /\
 |                  |
we're starting here
                    |
                    |
      create a slice that starts from here
```
