### ISSUE TITLE
build universal binaries with cargo-zigbuild?

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1344]
In [version 0.16.0](https://github.com/rust-cross/cargo-zigbuild/releases/tag/v0.16.0) cargo-zigbuild added support for a [macOS universal 2 target](https://github.com/rust-cross/cargo-zigbuild#macos-universal2-target). We could use that to build the universal macOS binaries.

**Comment by aviramha** [comment]
That could be amazing improvement in our CI!
We still have to build layer universal then cli universal and make sure everything work with the code signing too.

**Comment by aviramha** [comment]
Just realized we can't do it since we do the "arm64e" patch.
A possible approach would be to create a fork of zigbuild that does the patch but feels like too much work..

**Comment by aviramha** [comment]
think we can close this - won't happen now that we do #2846
