### ISSUE TITLE
Make the protocol "new message fault-proof".

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1354]
Failing to decode a message is fatal.
In the operator, we can assume decoding that fails is okay to ignore and pass as is since it's not really handled by mirrord ATM and as long as we don't change existing structs all is good (and we don't do it almost ever).
There's also the case of added fields for a new struct, where we can ignore the extra data given we have a header to each message for determining the size.

## Cases
* Request incoming that is 8 bytes. First 4 bytes will be used to store "8 bytes". If the decoder only consumes 4 bytes, we will still consume the rest so frames won't break.
* Request incoming to operator where it fails to deserialize, since it doesn't have that message type in the enum it fails. Given it knows the request size, it just passes it as is.

## Assumptions
* Adding variants to the *end* of an enum in bincode doesn't break parsing the preceding variants.
* ?

## Implementation

If we decide to add a frame, it is a breaking change. We should be able to detect the protocol level, whether it supports it or not before using it to avoid breaking. Maybe block this on #1355 ? Not sure.

**Comment by t4lz** [comment]
Do we actually still want this? https://github.com/metalbear-co/mirrord/discussions/1516#discussioncomment-6665950 seems to say we don't:

> - Protocol have to be same across the board layer - (operator) - agent
> - The reason we want the operator to have same protocol as layer/agent is that the operator would act as a "firewall" in the end (enabling/disabling specific operations) and just sending arbitrary messages isn't something we want to happen.

Or do I misunderstand it?

**Comment by aviramha** [comment]
No you're right :)
