### ISSUE TITLE
Fix all check-rust-docs warnings

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1399]
Existing warnings are shown in the "Unchanged files with check annotations" parts of PRs' code, e.g. https://github.com/metalbear-co/mirrord/pull/1343/files#file-mirrord-protocol-src-outgoing-rs-L102.

We should fix all of those issues so that there are no preexisting warnings, then not merge new warning-inducing code into main.

## Where to begin?
Please refer to the [CONTRIBUTING.md file](https://github.com/metalbear-co/mirrord/blob/main/CONTRIBUTING.md)

**Comment by gememma** [comment]
Running `cargo doc --document-private-items --no-deps` generates around 70 warnings, so this might take longer than initially expected. It looks like most of the warnings are broken links.
