### ISSUE TITLE
Cache paths for config dropdown on intelliJ

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord#1423]
The paths are converted to a readable path and that can be cached, if there is a miss we can compute the path.

**Comment by t4lz** [comment]
Why not just save the readable paths in the hash map in the first place? That way we don't recompute the paths of the configuration files on a click on the menu, we just compute them once when they are added to the project.

**Comment by infiniteregrets** [comment]
> Why not just save the readable paths in the hash map in the first place? That way we don't recompute the paths of the configuration files on a click on the menu, we just compute them once when they are added to the project.

Yes, there is no difference in either approaches. Opened this issue when I saw intellij's cache value manager.
