### ISSUE TITLE
mirrord copy pod

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1465]
Following Discord discussion:
https://discord.com/channels/933706914808889356/1111113277053870161/1111263282054045697

User wants to:

1. Get an existing pod environment variable
2. Have networking exposed both incoming and outgoing of the cluster
3. But they don't want to steal an existing pod traffic

I thought a more generic use case would be something like `mirrord exec --replica -t pod/pod`
which instead of running targetless, it will create a replica of an existing pod.

Things to consider:
1. Should we run the original app or just our agent with the replica? (then pause / steal?)
2. ?

**Comment by aviramha** [comment]
Another usecase - CronJob.

**Comment by aviramha** [comment]
Short update - we're prioritizing this as part of mirrord for Teams. 
https://github.com/metalbear-co/operator/issues/321

**Comment by eyalb181** [comment]
This was implemented as part of mirrord for Teams.
