### ISSUE TITLE
Doesn't work with local minikube cluster on WSL2

### ISSUE THREAD

**Issue by pmualaba** [metalbear-co/mirrord#1473]
### Bug Description

I'm trying to mirrord using the cli into a local minikube cluster but i always get the following error and i don't see any Pod created for mirrord in the cluster...:

using the basic command:
`mirrord exec --target pod/settlemint-cc8d8994b-2bxtb pnpm nx serve onprem-deploy-workers`

x mirrord cli starting
  x preparing to launch process
  ✓ layer extracted
  ✓ no operator detected
  ✓ agent pod created
  x waiting for pod to be ready...
Error:   × Agent wasn't ready in time

<img width="641" alt="image" src="https://github.com/metalbear-co/mirrord/assets/1754718/3ed62f59-b1bd-46f9-9a65-ca8dda3d03a8">

### Steps to Reproduce

 1. Vanilla WSL2 on Windows 11
 2. Vanilla minikube setup on WSL2 
 3. mirrord exec --target pod/xxxx pnpm nx serve xxxx

### Your operating system and version

Windows 11 WSL2

### Local process

pnpm nx serve ...

### Local process version

Nx16.2.2

**Comment by aviramha** [comment]
Thanks for reporting this!
Can you execute with the following environment variable `MIRRORD_AGENT_TTL=120`
so for example in your case
`MIRRORD_AGENT_TTL=120 mirrord exec --target pod/xxxx pnpm nx serve xxxx`
then while it starts running, check `kubectl get jobs` and `kubectl get pods` and check if you see the agent job/pod?

**Comment by meowjesty** [comment]
I've tried this out with a sample nx express app, and it seems to be working on latest main of mirrord ([2c35fdf](https://github.com/metalbear-co/mirrord/commit/2c35fdffcb076eeca203f44d41149c1237feede2)).

Could you please update mirrord and try again?

Would also be very helpful if you could follow aviramha's suggestion, and then report back with more info.

**Comment by aviramha** [comment]
Closed after we didn't receive followup
