### ISSUE TITLE
VSCode extension doesn't list pods outside the default namespace

### ISSUE THREAD

**Issue by 7onn** [metalbear-co/mirrord#15]
**Description**:
I went to test the extension with an app written in Golang which runs outside of my cluster's default namespace. After clicking on `Start mirrord` in the status bar, only pods placed in the default namespace are listed. Because of this, I wasn't able to proceed with the tests.

**Notes**:
I'm not sure what useful information I could add here since the debugging mode never got to receive forwarded connections. But feel free to ask anything for I'm willing to help =)

**Comment by eyalb181** [comment]
Released version 1.1.0 of the extension, which adds a settings button which lets you change the namespace and the remote port. Thanks @7onn for the input!
