### ISSUE TITLE
Steal based on HTTP Path Filter

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1512]
Currently we support filtering based on HTTP headers. Some of the users asked to support stealing based on the path accessed.

- [x] merging #1550  
- [x] adding to operator

**Comment by aviramha** [comment]
We probably need to deprecate the old filter config, since it's "explicitly" http header. Having said that, would we want the filters to be `or` / `and` / or mutual exclusive? like if user specifies a http header filter and path header, should it be matching both or only one or should we just error for now?

**Comment by eyalb181** [comment]
Personally I don't see a use case for either, and would rather error out until a user asks for it than support a use case we don't understand.
