### ISSUE TITLE
mirrord-cli : reqwest dependency missing "blocking" feature

### ISSUE THREAD

**Issue by IsaacCloos** [metalbear-co/mirrord#152]
### Bug Description

mirrord-cli uses the "blocking" feature of [reqwest](https://crates.io/crates/reqwest):
https://github.com/metalbear-co/mirrord/blob/255fbe55262019f282010951d9d6f8158ec2530d/mirrord-cli/src/main.rs#L193

but does not enable that feature in its toml file
https://github.com/metalbear-co/mirrord/blob/255fbe55262019f282010951d9d6f8158ec2530d/mirrord-cli/Cargo.toml#L26

should look something like this ([docs](https://crates.io/crates/reqwest#blocking-client)):
```
reqwest = { version = "0.11.10", features = ["blocking"] }
```

### Steps to Reproduce

1. Clone main branch (as of this [commit](255fbe55262019f282010951d9d6f8158ec2530d))
2. Open project in dev container (I'm using VSCode [remote containers extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers))
3. run `cargo check` or `cd mirrord-cli && cargo check`
4. 💥 (see backtrace)

### Backtrace

```shell
if let Ok(client) = reqwest::blocking::Client::builder().build() {
   |                         ^^^^^^^^ could not find `blocking` in `reqwest`
```

### Your operating system and version

local: macOS Monterey version 12.4, container: Debian OS variant buster

### Local process

N/A

### Additional Info

If you have already been working with the source code it may be necessary to rebuild your container to simulate this issue.

I'm not sure if I would call it "cached", but after I solved this issue once "in passing" i was unable to make it happen again regardless of `cargo clean` ext.

**Comment by aviramha** [comment]
Thanks for the detailed report! Are you interested in sending a PR?
