### ISSUE TITLE
React + Webpack app crashes on hot reload

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1524]
### Bug Description

Running react app with hot reload enabled, the app crashes on code changes.

### Steps to Reproduce

1. Probably:
```
npx create-react-app my-app
cd my-app
npm start
```
2. Make a change to the code.
3. Observe as your app crashes and it's our fault.

### Your operating system and version

?

### Local process

node?

**Comment by aviramha** [comment]
User side
