### ISSUE TITLE
Can't use mirrord on Windows without WSL

### ISSUE THREAD

**Issue by wangqianqianjun** [metalbear-co/mirrord#1544]
### Bug Description

Hi Mirrord,
I try use mirrord on my desktop , but seems failed.
error msg: Can't use mirrord on Windows without WSL.

env:
IntelliJ idea: 2023.1.2 Build #IU-231.9011.34
OS:  windows 10
plugin version: mirrord 3.45.0

### Steps to Reproduce

1. install mirrord plugin in windows 10
2. enable mirrord
3. debug you java application
4.  Can't use mirrord on Windows without WSL.

### Your operating system and version

windows 10

### Local process

Java

### Local process version

jdk17

**Comment by aviramha** [comment]
hi, this is a known limitation at the moment #28. Feel free to comment there and upvote so we can track priority.

**Comment by wangqianqianjun** [comment]
@aviramha  thank you , it's a great tool , I try install wsl to fix that
