### ISSUE TITLE
Support local traffic in addition to traffic forwarded from the cluster

### ISSUE THREAD

**Issue by omriza** [metalbear-co/mirrord#1554]
Hey folks, I really enjoy working with mirrord so far, its speed and flexibility is impressive so huge kudos! 👏 

One feature I find compelling is the local application instance's ability to receive both traffic from the cluster, as it is today using either `mirror` or `steal`, and also locally generated traffic (i.e. calling the application from a gRPC client).

For example, I’m developing an app that exposes a gRPC server on port 50051; traffic generated inside the remote cluster on this port it will be forwarded to my localhost, but also, I’d like to be able to send requests from my localhost to port 50051 and have them received in the locally running instance.

Right now I work around this by running the gRPC client in targetless mode which works like a charm, but if there’s a way to spare the extra step it would be even more awesome.

Conceptually, a new configuration can help here, which will allow enabling such capability, along with port mapping for cases where users will want to use different ports locally, something like-

```
"network": {
      "incoming": "steal",
      "outgoing": true,
      "local": {
        "enabled": true,
        "port_mapping": [ "8080:80", "5000:50051" ]
      }
},
...
```

Thanks!

**Comment by gshaibi** [comment]
Thank you for suggesting this approach.
It can be a good strategy to ensure availability and avoid port conflicts.

I think the configuration should take place even if the given port is available. Was this what you meant @aviramha?

**Comment by aviramha** [comment]
@gshaibi yes :)

**Comment by gshaibi** [comment]
Amazing, thank you!

**Comment by t4lz** [comment]
Just brainstorming a bit, since w'ell have a lot of port configuration - maybe it would be more convenient to have it all in one place?
```
{
  "feature": {
    "network": {
      "incoming": {
        "mode": "steal",
        "ports": [
          {
            "port": 80,
            "remote_port": 5000,
            "local_port": 8080,
            "http_header_filter": "host: api"
          },
          {
            "port": 1000,
            "ignore": true
          }
        ]
      }
    }
  }
}
```
Later we could also move `mode` into the individual port configuration.

**Comment by aviramha** [comment]
@t4lz I feel like it'd bind unrelated scenarios/usecases and also doesn't make sense from our logic standpoint..

**Comment by aviramha** [comment]
Can see current version of change here
https://github.com/metalbear-co/mirrord/pull/1561/files
lmk if you have any suggestions.
