### ISSUE TITLE
Python doesn't work with mirrord with default config on Apple CPUs

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1570]
### Bug Description

Python just does nothing with mirrord on a mac with M2.

We get different results when connecting to the mirrord console, in that case the process exits with code 132 (Illegal instruction).

it does work when specifying fs-mode `local-with-overrides`.

### Steps to Reproduce

`mirrord exec -t deploy/py-serv-deployment python3`

### Your operating system and version

macOS 13.4

### Local process

file $(which python3) /Users/tal/.pyenv/shims/python3: Bourne-Again shell script text executable, ASCII text

**Comment by t4lz** [comment]
#1571 prevents this issue from reproducing, but it's not clear that there is no underlying issue that still exists, so we might want to leave this open.

**Comment by eyalb181** [comment]
Can you close this issue (since Python does run on Apple CPUs now) and open a new one that's more descriptive of the actual problem?

**Comment by t4lz** [comment]
Closing for now. If a bug still exists, we'll open an issue when we see it.
