### ISSUE TITLE
`medschool` drops fields (sometimes).

### ISSUE THREAD

**Issue by meowjesty** [metalbear-co/mirrord#1580]
### Bug Description

When running `medschool` in our `mirrord-config` project, sometimes a few fields are dropped (so far I've only seen the `operator` config field being lost).

I'm not quite sure why this happens, probably due to how we search for inner types in the fields of a struct, and when we have reached an edge we go back, and repeat the process until all edges have been found. So the bug probably lies in the "going back" part.

A somewhat decent way of checking if a field has been dropped is to run `medschool` a few times, and check the amount of lines produce in `configuration.md`. The correct one will have more lines (keep in mind that the tool wasn't tested for overwriting an already existing `configuration.md`, so to guarantee you're looking at a correct file, before you re-run it, change the existing file name / remove it / copy it) .

### Steps to Reproduce

1. `cd mirrord/config`;
2. run `../../target/medschool`;
3. `cat -n configuration.md`;
4. check line numbers (currently should be `>= 790`
5. `mv configuration.md.old`;
6. run `../../target/medschool`;
7.  `cat -n configuration.md`;
8. compare line count with previous run;

### Your operating system and version

N.A.

### Local process

medschool

**Comment by eyalb181** [comment]
Since medschool is now deterministic, configuration differences should be easy to follow in PRs - so it should be easy to notice if a field was accidentally dropped, and run medschool again.

So this is low priority.
