### ISSUE TITLE
Add support for setting Agent resource limits

### ISSUE THREAD

**Issue by Exactol** [metalbear-co/mirrord#1621]
I would like to use mirrord, but the Kubernetes cluster I am using has a policy setup where it will reject any pod without a resource limit. This causes the Agent job to timeout because it cannot run. It looks like the resource requests are currently [hardcoded](https://github.com/metalbear-co/mirrord/blob/211afc585b0e10c36fac6df2f5933fd0c592ea20/mirrord/kube/src/api/container.rs#L247C38-L247C38), would it be possible to allow setting a resource limit?

I can get around this issue with a LimitRange that sets a default limit, but I would rather not have to use it incase somebody forgets to set a resource limit on a deployment

**Comment by aviramha** [comment]
Thanks for reporting this. I added default limits in #1622 - I don't think specifying custom makes sense at the moment (we can add it later if needed).
