### ISSUE TITLE
Flush Connections option ineffective

### ISSUE THREAD

**Issue by DmitryDodzin** [metalbear-co/mirrord#1655]
### Bug Description

```
conntrack v1.4.7 (conntrack-tools): 0 flow entries have been deleted.
```
conntrack seems to not delete any entries where in fact there are some

### Steps to Reproduce

When running with --steal on a pod that already has an active connection, we expect that connection to be flushed and our steal connection to replace it. What we're actually seeing is that the steal connection replaces it after a few minutes, i.e. after it disconnects on its own.

### Your operating system and version

macOS

### Local process

any-tcp

**Comment by aviramha** [comment]
This was a regression, and it was fixed. During the testing we found out that it some scenarios, it still doesn't apply.
My suspicion is it depends on the networking of the cluster - if there are rules to drop connections that are not tracked. In some of the cases we've seen it doesn't work but we've lived so far with it, so I think we should wait before trying to add another measure - see that it affects more people then do it.

According to online forums and docs, the `nat` table that we use affects only *new* flows, hence we need to flush. The reason the session stays open is that there are no rules in the `filter` table that drops connections that aren't tracked.
