### ISSUE TITLE
Seems to be not working with php-fpm

### ISSUE THREAD

**Issue by rucciva** [metalbear-co/mirrord#1712]
### Bug Description

when the target container is running php-fpm, which use unix socket, no traffic are being mirrored or stollen to local mirrord 

### Steps to Reproduce

1. deploy php-fpm apps
2. run mirrord and target the deployed app

### Relevant Logs

```shell
on the agent

agent ready
2023-07-24T09:05:43.172920Z  WARN ThreadId(07) mirrord_agent::outgoing: interceptor_task -> no messages left
2023-07-24T09:05:43.172945Z  WARN ThreadId(08) mirrord_agent::outgoing::udp: interceptor_task -> no messages left
2023-07-24T09:05:43.888466Z  WARN ThreadId(06) mirrord_agent::steal::ip_tables::flush_connections: `conntrack` output is Output {
    status: ExitStatus(
        unix_wait_status(
            256,
        ),
    ),
    stdout: "",
    stderr: "conntrack v1.4.7 (conntrack-tools): 0 flow entries have been deleted.\n",
}
```

on the local mirrord
```
mirrord cli starting...
exec
preparing to launch process
extracting layer
layer extracted
checking operator
no operator detected
creating agent pod...
agent pod created
waiting for pod to be ready...
pod is ready
ready to launch process
[24-Jul-2023 08:49:34] NOTICE: Failed implicitly binding to ::, retrying with 0.0.0.0
[24-Jul-2023 08:49:34] NOTICE: Failed implicitly binding to ::, retrying with 0.0.0.0
[24-Jul-2023 08:49:34] NOTICE: fpm is running, pid 1
[24-Jul-2023 08:49:34] NOTICE: ready to handle connections
```
```


### Your operating system and version

rancher docker desktop, docker engine version 23.0.6

### Local process

php-fpm

### Local process version

_No response_

### Additional Info

link to discord: https://discord.com/channels/933706914808889356/1132300217354559579

**Comment by cslamar** [comment]
@rucciva Someone on the Mirrord Discord said you were able to get this working (with a workaround), if true, how'd you end up doing it?

**Comment by rucciva** [comment]
Hi @cslamar , i end up running two mirrord, one for nginx and one for php-fpm. Mirrord on nginx will steal incoming traffic but will not steak outgoing connection. That way when nginx on remote receive traffic, it will forward it to local nginx, and local nginx will have it forwarded to local php-fpm instead of remote php-fpm.

**Comment by aviramha** [comment]
I think we can implement unix socket stealing by moving the original socket - https://unix.stackexchange.com/questions/169228/how-does-moving-a-unix-domain-socket-enable-socat-to-monitor-traffic

**Comment by rucciva** [comment]
hi @aviramha , i'm not quite sure how nginx and php-fpm communicate, but in my case, i passed ip and hostname to `fastcgi_pass`. does it means that it was not actually using unix socket? or if it was, then the same logic can be used, have mirrord listen to said port and forward it to the actual port?

<img width="438" alt="Screenshot 2023-07-31 at 12 44 32" src="https://github.com/metalbear-co/mirrord/assets/4647473/0226920a-da99-41a5-b652-b4447b5d3199">

**Comment by aviramha** [comment]
In this case, if you didn't have `ignore_localhost` set to `true` running `php-fpm` using mirrord alone should work..

**Comment by rucciva** [comment]
i have make sure that `ignore_localhost` is set to `false` in incoming and outgoing but it won't work with `php-fpm` only. it only work if i also inject nginx

**Comment by aviramha** [comment]
Do you listen on `php-fpm` on same port? (9000)

**Comment by rucciva** [comment]
yes, both are the same in local and remote

**Comment by rucciva** [comment]
these are when injecting php-fpm only 
<img width="1102" alt="Screenshot 2023-07-31 at 13 40 52" src="https://github.com/metalbear-co/mirrord/assets/4647473/18191ac7-44ed-4f0b-94dd-2866a0f40bf3">

and these are when injecting with nginx
<img width="1097" alt="Screenshot 2023-07-31 at 13 41 24" src="https://github.com/metalbear-co/mirrord/assets/4647473/e553588c-33e2-4f27-8916-2bc8e8c972aa">

**Comment by rucciva** [comment]
These are when injectin php-fpm only

<img width="822" alt="Screenshot 2023-07-31 at 13 33 22" src="https://github.com/metalbear-co/mirrord/assets/4647473/fbc32d84-74fe-42e4-8928-9e2026dfce89">

these are when injecting php-fpm and nginx
<img width="955" alt="Screenshot 2023-07-31 at 13 50 02" src="https://github.com/metalbear-co/mirrord/assets/4647473/0fd77c16-d715-4478-8776-aa4460748f10">

**Comment by aviramha** [comment]
I think this is related to #1655

**Comment by cslamar** [comment]
@rucciva what's the `mirrord exec` command you're using to connect both the php-fpm and nginx services to the cluster?

**Comment by rucciva** [comment]
@cslamar here are the `feature` section of my config. The main point is so that outgoing connection from local nginx to local php-fpm does not get intercepted by mirrord. (note that my nginx and php-fpm container are communicating through local network, both on the kubernetes and local docker compose)

nginx:
```
feature:
    network:
        incoming:
            mode: steal
        outgoing:
            ignore_localhost: true
    fs: false
    env:
        include: "*"
```

php-fpm:
```
feature:
    fs: false
    env:
        include: "*"
```

and the command to inject nginx correctly needs to be separated into two mirrord execution, since it encountered panic when injecting shell script and the nginx won't start

```
/opt/mirrord/bin/mirrord exec -f /opt/mirrord/etc/mirrord-backend-nginx.yaml /docker-entrypoint.sh -- nginx -v
exec /opt/mirrord/bin/mirrord exec -f /opt/mirrord/etc/mirrord-backend-nginx.yaml nginx -- -g "daemon off;"     
```

**Comment by gawsoftpl** [comment]
Hi @rucciva have you resolve issue with mirrord and php-fpm. I am looking for how to create mirrord with k8s and php-fpm with laravel project. How did you resolve your issue, have you use docker-compose or install php-fpm in local environment?

**Comment by rucciva** [comment]
Hi @gawsoftpl , yes, you can see the snipped of my config from my comment before yours. And i did you docker compose in my local machine.

**Comment by eyalb181** [comment]
Hey @rucciva , is this still blocking you?

**Comment by rucciva** [comment]
Hey @eyalb181 , I haven't tried it again. I just leave it with the workaround above
