### ISSUE TITLE
Internal proxy resets connection from layer when running shell with mirrord and piping input

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1716]
### Bug Description

When running a shell (was observed with both sh and zsh) that reads some commands from stdin with mirrord the internal proxy sometimes resets an incoming connection from a layer and an error is displayed. 

### Steps to Reproduce

```
echo "nvm use" | MIRRORD_PROGRESS_MODE=off mirrord exec -f .mirrord/mirrord.json zsh -- -is
```

where `.mirrord/mirrord.json` is:
```
{
    "accept_invalid_certificates": true,
    "target": {
        "path": {
            "deployment": "dotenv"
        }
    },
    "feature": {
        "network": {
            "incoming": "mirror",
            "outgoing": true
        },
        "fs": {
            "mode": "localwithoverrides",
            "read_only": ".*/.env"
        },
        "env": true
    }
}
```

Also reproduced with just `echo "nvm use" | MIRRORD_PROGRESS_MODE=off mirrord exec zsh -- -is`, but less often.

### Relevant Logs

```
2023-07-24T20:16:49.964783Z ERROR ThreadId(09) mirrord_layer::connection: Couldn't connect to internal proxy: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }, 127.0.0.1:51068                                                                                      
```
### Your operating system and version

macOS 13.4

### Local process

zsh

### Additional Info

The error never reproduced with `trace` level logs.

Running zsh with that stdin results in **hundreds** of `execve`s, each of them results in the initialization of a new layer, each of those layers connects to the internal proxy (most of them soon disconnect as their process is replaced by the next executed process).

So one thing I'm looking into is whether the internal proxy is somehow overwhelmed by that crazy chain of process execusions.

**Comment by aviramha** [comment]
Now getting connectionrefused from internal proxy

**Comment by t4lz** [comment]
#1724 did not fix this. It seems like the intproxy does not die, but sends a RST to one request, but then keeps accepting other requests, after some connections close, so we think maybe it reaches some limit of connections (and running a shell with mirrord triggers it because it executes hundreds of processes). It seems like setting `ulimit -n 1024` makes the issue happen less often, but maybe it was random.
There is also https://github.com/rust-lang/rust/issues/55614

As a solution to this kind of problem, regardless of where the bottleneck is exactly, we want to make the connection to the intproxy lazy, so that we only create a connection once we actually want to send a message. That way the hundreds of processes that don't trigger any hook, and don't need to send any message won't connect to the intproxy. @aviramha will take the issue from here.
