### ISSUE TITLE
`go` stopped working in VScode devcontainer after a few hours of running mirrord.

### ISSUE THREAD

**Issue by meowjesty** [metalbear-co/mirrord#1725]
### Bug Description

User reported:

After working for several hours, stealing traffic from a remote container, debugging locally a GO service (Intel Mac, VScode devcontainer), suddendly hit this:

```sh
Build Error: go build -o /workspaces/the-x/__debug_bin2795526562 -gcflags all=-N -l ./main.go
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find /lib64/ld-linux-x86-64.so.2: No such file or directory
collect2: error: ld returned 1 exit status (exit status 1)
 ```

Only rebuilding the devcontainer from scratch, worked...

Intel Mac, Go is 1.20, I'm using the vscode ext. so I assume mirrord version is fetched from latest?

This happened only once. The only possible way to recover was rebuilding the devcontainer.

It was bunch of trial & errors, running in debug, stopping, re-running, stopping again untill I hit this.

[Discord thread](https://discord.com/channels/933706914808889356/1133862304837030028)

### Steps to Reproduce

1. Run `go` project with mirrord in `steal` mode a bunch of times;
2. After a few hours of this flow, `go` stopped working;

### Your operating system and version

Intel Mac, Go is 1.20

### Local process

go build -o /workspaces/the-x/__debug_bin2795526562 -gcflags all=-N -l ./main.go

**Comment by aviramha** [comment]
I think this is related to the VSCode - I think we get loaded into the build tools and we can avoid it from vscode perspective.
If the fix is in VSCode let's move it there (up to the assignee)
