### ISSUE TITLE
Provide a `--context` option for the `exec` command

### ISSUE THREAD

**Issue by chriszarate** [metalbear-co/mirrord#1735]
In addition to the "sticky" `config use-context` command, `kubectl` provides a `--context` option to allow run-time overrides. This is especially useful in multi-cluster environments to enable quick, temporary switching between clusters. It is also invaluable for use in scripting.

An equivalent option in `mirrord exec` would be equally helpful and provide a nice symmetry with `kubectl`. Thank you!

**Comment by ni-todo-spot** [comment]
> In addition to the "sticky" `config use-context` command, `kubectl` provides a `--context` option to allow run-time overrides. This is especially useful in multi-cluster environments to enable quick, temporary switching between clusters. It is also invaluable for use in scripting.
> 
> An equivalent option in `mirrord exec` would be equally helpful and provide a nice symmetry with `kubectl`. Thank you!

I'd find this feature useful as well 😄

**Comment by chriszarate** [comment]
Thank you, @aviramha!
