### ISSUE TITLE
agent pause fails

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1737]
[2m2023-08-01T09:25:05.962963Z[0m [31mERROR[0m ThreadId(02) [1mmirrord_agent[0m[2m:[0m Error handling client message: Status(Status { code: Unknown, message: "cannot pause a paused container: unknown", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None })

**Comment by eyalb181** [comment]
Any more info you can provide? @aviramha

**Comment by eyalb181** [comment]
Might be related to #1878
