### ISSUE TITLE
Remove unwraps and exit gracefully in the shared library constructor 

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord#176]
https://github.com/metalbear-co/mirrord/blob/main/mirrord-layer/src/lib.rs#L63

The shared library constructor has two unwraps in it, it would be nicer if we could just print to stderr and exit gracefully instead of rust panic.

**Comment by TawalMc** [comment]
Hi. I work on this issue.

Assign it to me.

**Comment by eyalb181** [comment]
Hey @TawalMc , we've not heard anything for a while so opening this one back up for takers, let me know if you plan to get back to it.

**Comment by infiniteregrets** [comment]
@meowjesty note: we can't use any std functions in the ctor, it causes a segfaults (in case of arm64e)
