### ISSUE TITLE
Couldn't connect to internal proxy: Connection Refused

### ISSUE THREAD

**Issue by lks-mtzn** [metalbear-co/mirrord#1761]
### Bug Description

When I'm starting the the mirrord process with this command: `mirrord exec -f .mirrord/mirrord.yaml dlv -- debug --headless -l 127.0.0.1:38697 cmd/service/main.go`, wait to long to connect with dlv connect 127.0.0.1:38697 and type `continue` in the dlv process.

It gives me following error:
```
__debug_bin2287811174 (pid = 3926).
2023-08-04T09:02:06.565195Z ERROR ThreadId(11) mirrord_layer::connection: Couldn't connect to internal proxy: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }, 127.0.0.1:49813
```

### Steps to Reproduce

1. run `mirrord exec -f .mirrord/mirrord.yaml dlv -- debug --headless -l 127.0.0.1:38697 cmd/service/main.go`
2. wait few seconds (less than 30 seconds)
3. connect to the dap server `dlv connect 127.0.0.1:38697`
4. type `continue` in dlv
5. get the error from the mirrord process

### Your operating system and version

macOS Ventura 13.4

### Local process

an go service/binary? idk

**Comment by aviramha** [comment]
hey, I tried finding a complete solution for this but couldn't, so the PR I created #1770 will enable you to specify your own timeouts, so then you could extend it to 60 sec, or even 120.
Bear in mind the timeout begins from the moment agent was created.

**Comment by aviramha** [comment]
Please try using the latest version 3.56.0 and add
```json
{"internal_config": {"start_idle_timeout": 120}}
```
and see if that helps.

**Comment by lks-mtzn** [comment]
It works now with this yaml:
```
agent:
  namespace: &ns bar
target:
  namespace: *ns
  path:
    deployment: foo
internal_proxy:
  idle_timeout: 60
```
