### ISSUE TITLE
Warn when mirroring on service mesh

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#1768]
Since mirroring traffic in clusters with a service mesh isn't really supported, we should detect when users try to do it and warn them. We can detect by checking if the pod is running a container with a proxy for a service mesh - e.g. linkerd, istio. 

As with all warnings, please make sure it shows on both the CLI and the IDE extensions.

**Comment by meowjesty** [comment]
Warning has been added. Tested and can see it on both cli and vscode, but I could not test it in IntelliJ stuff (my intellij ide was kinda borked, and was not showing the mirrord notifications properly?).
