### ISSUE TITLE
DNS config should cover "manual" DNS resolvers that use `send/sendto/sendmsg`.

### ISSUE THREAD

**Issue by meowjesty** [metalbear-co/mirrord#1807]
Currently the DNS config we have is only checked for hooking `getaddrinfo` and `freeaddrinfo`, but as we've seen in some previous issues (#1776 comes to mind), some languages/frameworks will resolve DNS manually, by trading UDP messages.

A solution for this would be to have a global config for DNS, then check if it's enabled when `send[to|msg](address:53)` (maybe also check it in `connect`?), and act appropriately, sending the packets from local when DNS is disabled.

**Comment by aviramha** [comment]
I think we're good now?

**Comment by meowjesty** [comment]
Good until the next YADI!

Close it?
