### ISSUE TITLE
read SSL certificate on C# Linux fails

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1815]
```
Unhandled exception. Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
   at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
   at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Certificates.CertificateConfigLoader.LoadCertificate(CertificateConfig certInfo, String endpointName)
```

**Comment by aviramha** [comment]
Issue confirmed.
Created a sample project, added:
```
X509Certificate2 x509 = new X509Certificate2("/var/run/secrets/kubernetes.io/serviceaccount/ca.crt");
```
and didn't see any trace indicating attempt to open file, while it did fail.

**Comment by infiniteregrets** [comment]
> Issue confirmed. Created a sample project, added:
> 
> ```
> X509Certificate2 x509 = new X509Certificate2("/var/run/secrets/kubernetes.io/serviceaccount/ca.crt");
> ```
> 
> and didn't see any trace indicating attempt to open file, while it did fail.
> 
> ```
> Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
>    at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
>    at System.Security.Cryptography.X509Certificates.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
>    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
>    at Program.<Main>$(String[] args) in /app/WebApplication1/Program.cs:line 26
> ```

just took a quick look as I had everything from mongodb issue open in a window so it was easy to search: https://github.com/dotnet/runtime/blob/ac02b66e41041e1cefd355eacaddb45bcb4f1741/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/OpenSslX509CertificateReader.cs#L17 calls `BioNewFile` for the handle which returns null which brings me here: https://github.com/dotnet/runtime/blob/ac02b66e41041e1cefd355eacaddb45bcb4f1741/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.BIO.cs#L16 and which is related to 
```
BIO* CryptoNative_BioNewFile(const char* filename, const char* mode)
{
    ERR_clear_error();
    return BIO_new_file(filename, mode);
}
```
which calls `openssl_fopen`: https://github.com/openssl/openssl/blob/c2a8226cba2757b251729620aedffeed23d73623/crypto/bio/bss_file.c#L57C1-L57C1

which is https://github.com/openssl/openssl/blob/c2a8226cba2757b251729620aedffeed23d73623/crypto/o_fopen.c#L38C1-L38C1 and the only thing i see unhooked is `_wfopen`
