### ISSUE TITLE
Configuration templating

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1817]
Right now our configuration supports constant values, but some users asked for templating features, so they could have a config file that is mutated by the specific run.
I think maybe we should start with adding ability to use environment variables, so for example have
```json
{
  "target": {
    "path": "{DEPLOYMENT_NAME}",
    "namespace": "{NAMESPACE_NAME}"
  }
}
```
then user can set `DEPLOYMENT_NAME` and fetch it from env.

**Comment by aviramha** [comment]
Have to do before:

- [ ] #1840
- [ ] https://github.com/metalbear-co/mirrord-vscode/issues/57
- [ ] https://github.com/metalbear-co/mirrord-intellij/issues/99

**Comment by meowjesty** [comment]
All 3 requirements have been merged!
