### ISSUE TITLE
Configuration validation from cli

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1840]
The new command will take a cfg path, and output the debug representation of `LayerConfig` and stderr will be used for outputing list of errors/warnings, so extensions can use it.

**Comment by meowjesty** [comment]
`mirrord verify-config [path]` has been added in #1926

Only the `TargetConfig` part is returned back when validation succeeds.

**Comment by meowjesty** [comment]
Welp, after changing it to a tagged union, the `Failure` portion doesn't serialize to json.

Working on a fix.
