### ISSUE TITLE
Different flow for targetless

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1844]
Change the targetless flow to be different then the default `create_agent` flow, since it doesn't require any capabilities, or privileges and a lot of configuration is irrelevant there (for example, can't be ephemeral)

- [x] metalbear-co/operator#299 - this should block metalbear-co/mirrord#1836 
- [ ] Change incoming to off on targetless, so we won't need privileges. - make sure agent doesn't create iptables/etc if no steal
- [ ] Create a different job/pod spec for targetless (to drop capabilities/privileges)

**Comment by eyalb181** [comment]
@DmitryDodzin Any chance this was done already?

**Comment by DmitryDodzin** [comment]
Yes, specs and permissions are separate for targeted and targetless

**Comment by eyalb181** [comment]
@DmitryDodzin So I can close this right?

**Comment by DmitryDodzin** [comment]
@eyalb181 I think yes, one thing though is that #1836 is still open and is mentioned in this issue
