### ISSUE TITLE
Use published hyper instead of our fork.

### ISSUE THREAD

**Issue by meowjesty** [metalbear-co/mirrord#1877]
Right now to solve #1869 we had to update hyper and hyper-util, and this was done in a fork.

When a newer release of hyper and hyper-util drops, we should change back to it.

P.S.: the forks don't even change any code, they're needed due to hyper-util depending on hyper, and the fix we need for #1869 being not-released yet.

**Comment by meowjesty** [comment]
We can almost update hyper to 1.0, we're blocked on [kube #1351](https://github.com/kube-rs/kube/issues/1351) now.

**Comment by aviramha** [comment]
New Kube was released!

**Comment by aviramha** [comment]
Blocked on merging our kube-rs fork that has this implemented https://github.com/kube-rs/kube/issues/1361

**Comment by aviramha** [comment]
Blocked on https://github.com/metalbear-co/private/issues/33
