### ISSUE TITLE
Support go run on Linux

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1922]
Following #1921 - we found out that even when compiled dynamically, go run wouldn't work on Linux, probably because it doesn't emit symbols we rely on.

**Comment by danielloader** [comment]
Is this just a Linux issue or does MacOS have the same issue?

**Comment by aviramha** [comment]
Should be Linux only since on macOS we don't hook Go specific symbols - just libc symbols which you have to have.

**Comment by drehelis** [comment]
Stumbled upon this issue now, looks life adding `-ldflags="-s=false"` works with `go run`.
