### ISSUE TITLE
sbt support

### ISSUE THREAD

**Issue by chameleon82** [metalbear-co/mirrord#1936]
I'm trying to execute simple sbt command `sbt run` with mirrord which is doing compile step and run main java class step internally. However, sbt execution stuck at the beggining with no progression. 
As sbt command line is a shell wrapper over sbt java app is there any chance this will be supported by default and added to `skip_build_tools` ?

**Comment by aviramha** [comment]
Did you try adding it there and it worked? if yes, sure!

**Comment by chameleon82** [comment]
can confirm with version `3.86.0` it works now, example to run server app:
```
mirrord exec -f .mirrord/mirrord.json sbt run 
```
surprisingly, compiltation works as well

```
mirrord exec -f .mirrord/mirrord.json sbt clean compile
```

I believe ticket can be closed

**Comment by aviramha** [comment]
Thanks for letting us know!
