### ISSUE TITLE
error when polling the I/O driver

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord#1946]
### Bug Description

 error when polling the I/O driver: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }

### Steps to Reproduce

mix phx.new ./mirrord_demo_app --no-html --no-gettext --no-dashboard --no-assets --no-ecto --no-esbuild --no-mailer --no-tailwind`

run with mirrord

### Backtrace

```shell
via 💧 took 50s ❯ RUST_BACKTRACE=full mirrord exec mix phx.server
⠓ mirrord exec
    ✓ Running on latest (3.67.0)!
    ✓ ready to launch process
      ✓ layer extracted
      ✓ no operator detected
      ✓ OpenShift was not detected.
      ✓ agent pod created
      ✓ pod is ready                                                                                                                                                                                                  thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/io/driver.rs:164:23:
unexpected error when polling the I/O driver: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }
stack backtrace:
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/io/driver.rs:164:23:
unexpected error when polling the I/O driver: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }
stack backtrace:
   0:        0x1037ee234 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4030c4138bcdf528
   1:        0x1038107d0 - core::fmt::write::h4b06b32fd4efd613
   2:        0x1037eaba8 - std::io::Write::write_fmt::hed3d984009928384
   3:        0x1037ee074 - std::sys_common::backtrace::print::h7e2b50b6cbf90560
   4:        0x1037efbb4 - std::panicking::panic_hook_with_disk_dump::{{closure}}::ha89af3293c7da63a
   5:        0x1037ef8b4 - std::panicking::panic_hook_with_disk_dump::hc4a4f27be6208df3
   6:        0x1037f0170 - std::panicking::rust_panic_with_hook::h037f273058a2da78
   7:        0x1037f0074 - std::panicking::begin_panic_handler::{{closure}}::h9026ba3bb755434a
   8:        0x1037ee6c0 - std::sys_common::backtrace::__rust_end_short_backtrace::h80ce8cb0d36934dc
   9:        0x1037efdd0 - _rust_begin_unwind
  10:        0x10383545c - core::panicking::panic_fmt::h77049d0460a1d743
  11:        0x1037a97ec - tokio::runtime::io::driver::Driver::turn::h889785e6b45ba27c
  12:        0x10379f964 - tokio::runtime::time::Driver::park_internal::hef7326cbeef46a1f
  13:        0x103799030 - tokio::runtime::scheduler::current_thread::Context::park::heb2f2de97acdf466
  14:        0x1033e2990 - tokio::runtime::context::set_scheduler::hd585f9fcd818cf3a
  15:        0x103414f4c - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::hd113ab11d0bc2e05
  16:        0x10339a65c - tokio::runtime::context::runtime::enter_runtime::h7c37a6adbb5b7469
  17:        0x103414228 - tokio::runtime::runtime::Runtime::block_on::h7119da2ac7d936cc
  18:        0x10341efe4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9cd8d667776551a5
  19:        0x10341ff58 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h122d9ec4308625ca
  20:        0x1037f42d0 - std::sys::unix::thread::Thread::new::thread_start::h5212bf6667c157b0
  21:        0x1a7f9ffa8 - __pthread_joiner_wake
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/io/driver.rs:216:27:
failed to wake I/O driver: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }
stack backtrace:
   0:        0x1037ee234 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4030c4138bcdf528
   1:        0x1038107d0 - core::fmt::write::h4b06b32fd4efd613
   2:        0x1037eaba8 - std::io::Write::write_fmt::hed3d984009928384
   3:        0x1037ee074 - std::sys_common::backtrace::print::h7e2b50b6cbf90560
   4:        0x1037efbb4 - std::panicking::panic_hook_with_disk_dump::{{closure}}::ha89af3293c7da63a
   5:        0x1037ef8b4 - std::panicking::panic_hook_with_disk_dump::hc4a4f27be6208df3
   6:        0x1037f0170 - std::panicking::rust_panic_with_hook::h037f273058a2da78
   7:        0x1037f0074 - std::panicking::begin_panic_handler::{{closure}}::h9026ba3bb755434a
   8:        0x1037ee6c0 - std::sys_common::backtrace::__rust_end_short_backtrace::h80ce8cb0d36934dc
   9:        0x1037efdd0 - _rust_begin_unwind
  10:        0x10383545c - core::panicking::panic_fmt::h77049d0460a1d743
  11:        0x1038357b4 - core::result::unwrap_failed::h30acd788e15ba8ae
  12:        0x103798668 - tokio::runtime::context::scoped::Scoped<T>::with::h124534ca181ba6d5
  13:        0x1037a4ab0 - tokio::runtime::task::waker::wake_by_val::hdc21103913305279
  14:        0x10340847c - core::ptr::drop_in_place<mirrord_layer::Layer>::h2843d1f9e63f7f14
  15:        0x10340d7ec - core::ptr::drop_in_place<mirrord_layer::thread_loop::{{closure}}>::h4ea1f46fd63e7564
  16:        0x1034142b4 - tokio::runtime::runtime::Runtime::block_on::h7119da2ac7d936cc
  17:        0x10341efe4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9cd8d667776551a5
  18:        0x10341ff58 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h122d9ec4308625ca
  19:        0x1037f42d0 - std::sys::unix::thread::Thread::new::thread_start::h5212bf6667c157b0
  20:        0x1a7f9ffa8 - __pthread_joiner_wake
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/io/driver.rs:216:27:
failed to wake I/O driver: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }
stack backtrace:
   0:        0x1037ee234 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4030c4138bcdf528
   1:        0x1038107d0 - core::fmt::write::h4b06b32fd4efd613
   2:        0x1037eaba8 - std::io::Write::write_fmt::hed3d984009928384
   3:        0x1037ee074 - std::sys_common::backtrace::print::h7e2b50b6cbf90560
   4:        0x1037efbb4 - std::panicking::panic_hook_with_disk_dump::{{closure}}::ha89af3293c7da63a
   5:        0x1037ef8b4 - std::panicking::panic_hook_with_disk_dump::hc4a4f27be6208df3
   6:        0x1037f0170 - std::panicking::rust_panic_with_hook::h037f273058a2da78
   7:        0x1037f0074 - std::panicking::begin_panic_handler::{{closure}}::h9026ba3bb755434a
   8:        0x1037ee6c0 - std::sys_common::backtrace::__rust_end_short_backtrace::h80ce8cb0d36934dc
   9:        0x1037efdd0 - _rust_begin_unwind
  10:        0x10383545c - core::panicking::panic_fmt::h77049d0460a1d743
  11:        0x1038357b4 - core::result::unwrap_failed::h30acd788e15ba8ae
  12:        0x10379970c - <tokio::runtime::scheduler::current_thread::Handle as tokio::util::wake::Wake>::wake::hbdc8ec2a9417e921
  13:        0x10340c9b8 - core::ptr::drop_in_place<mirrord_layer::outgoing::tcp::TcpOutgoingHandler>::h7025a409429c2442
  14:        0x103408658 - core::ptr::drop_in_place<mirrord_layer::Layer>::h2843d1f9e63f7f14
  15:        0x10340d7ec - core::ptr::drop_in_place<mirrord_layer::thread_loop::{{closure}}>::h4ea1f46fd63e7564
  16:        0x1034142b4 - tokio::runtime::runtime::Runtime::block_on::h7119da2ac7d936cc
  17:        0x10341efe4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9cd8d667776551a5
  18:        0x10341ff58 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h122d9ec4308625ca
  19:        0x1037f42d0 - std::sys::unix::thread::Thread::new::thread_start::h5212bf6667c157b0
  20:        0x1a7f9ffa8 - __pthread_joiner_wake
thread '<unnamed>' panicked at library/core/src/panicking.rs:144:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
[notice] Application ranch exited: exited in: :ranch_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function :ranch_app.start/2 is undefined (module :ranch_app is not available)
            (ranch 1.8.0) :ranch_app.start(:normal, [])
            (kernel 8.5) application_master.erl:293: :application_master.start_it_old/4
[notice] Application cowlib exited: :stopped
[notice] Application jason exited: :stopped
[notice] Application telemetry_poller exited: :stopped
[notice] Application telemetry_metrics exited: :stopped
[notice] Application phoenix exited: :stopped
[notice] Application castore exited: :stopped
[notice] Application websock_adapter exited: :stopped
[notice] Application websock exited: :stopped
[notice] Application phoenix_template exited: :stopped
[notice] Application phoenix_pubsub exited: :stopped
[notice] Application plug exited: :stopped
[notice] Application telemetry exited: :stopped
[notice] Application plug_crypto exited: :stopped
[notice] Application mime exited: :stopped
[notice] Application eex exited: :stopped
[notice] Application runtime_tools exited: :stopped
** (Mix) Could not start application ranch: exited in: :ranch_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function :ranch_app.start/2 is undefined (module :ranch_app is not available)
            (ranch 1.8.0) :ranch_app.start(:normal, [])
            (kernel 8.5) application_master.erl:293: :application_master.start_it_old/4
```

### Your operating system and version

macos

### Local process

 mix phx.server

### Local process version

erlang 25.1 elixir 1.14.0;  mix --version Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]  Mix 1.14.0 (compiled with Erlang/OTP 23)

**Comment by infiniteregrets** [comment]
probably related to https://github.com/metalbear-co/mirrord/issues/1618

**Comment by aviramha** [comment]
Things I've tried and failed so far:

1. Reusing the Sender/Receiver from the first creation, assuming it should work between runtimes - same error
2. Changing code to be single-threaded - resulted in new error of TLS context destroyed

<details>
<summary>Details</summary>

hread '<unnamed>' panicked at /Users/aviramhassan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:86:25:
The Tokio context thread-local variable has been destroyed.
stack backtrace:
   0:        0x10b874f10 - std::backtrace_rs::backtrace::libunwind::trace::hed51874e81bbae52
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10b874f10 - std::backtrace_rs::backtrace::trace_unsynchronized::hef6c6f4c5fd75c6f
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10b874f10 - std::sys_common::backtrace::_print_fmt::h49f63f82968326f8
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10b874f10 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4030c4138bcdf528
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10b8974b4 - core::fmt::rt::Argument::fmt::ha69ee8fe2d766f44
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/core/src/fmt/rt.rs:138:9
   5:        0x10b8974b4 - core::fmt::write::h4b06b32fd4efd613
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/core/src/fmt/mod.rs:1094:21
   6:        0x10b871740 - std::io::Write::write_fmt::hed3d984009928384
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/io/mod.rs:1714:15
   7:        0x10b874d50 - std::sys_common::backtrace::_print::hd6b45778e631d9b6
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x10b874d50 - std::sys_common::backtrace::print::h7e2b50b6cbf90560
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x10b876890 - std::panicking::panic_hook_with_disk_dump::{{closure}}::ha89af3293c7da63a
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/panicking.rs:280:22
  10:        0x10b876590 - std::panicking::panic_hook_with_disk_dump::hc4a4f27be6208df3
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/panicking.rs:314:9
  11:        0x10b876e4c - std::panicking::default_hook::hac9bce13d1518d4f
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/panicking.rs:239:5
  12:        0x10b876e4c - std::panicking::rust_panic_with_hook::h037f273058a2da78
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/panicking.rs:753:13
  13:        0x10b876d50 - std::panicking::begin_panic_handler::{{closure}}::h9026ba3bb755434a
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/panicking.rs:631:13
  14:        0x10b87539c - std::sys_common::backtrace::__rust_end_short_backtrace::h80ce8cb0d36934dc
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/sys_common/backtrace.rs:170:18
  15:        0x10b876aac - rust_begin_unwind
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/panicking.rs:619:5
  16:        0x10b8c05c0 - core::panicking::panic_fmt::h77049d0460a1d743
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/core/src/panicking.rs:72:14
  17:        0x10b793788 - core::panicking::panic_display::h25521635103bf373
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/core/src/panicking.rs:168:5
  18:        0x10b798694 - tokio::runtime::handle::Handle::enter::h45238bae91bd1740
                               at /Users/aviramhassan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:86:25
  19:        0x10b7b3ea0 - tokio::runtime::runtime::Runtime::enter::h8c9cf3de350d0b34
                               at /Users/aviramhassan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:388:9
  20:        0x10ac2bdac - tokio::runtime::runtime::Runtime::block_on::h5660132e8475d369
                               at /Users/aviramhassan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:344:22
  21:        0x10ab6ced8 - mirrord_layer::close_detour::h7cfe02db1a32164d
                               at /Users/aviramhassan/Code/mirrord/mirrord/layer/src/lib.rs:995:5
  22:        0x10ab6cf50 - mirrord_layer::close_nocancel_detour::hcd96a6818cf03845
                               at /Users/aviramhassan/Code/mirrord/mirrord/layer/src/lib.rs:1006:5
fatal runtime error: failed to initiate panic, error 5

</details>

4. Trying now to remove Tokio from layer, which is actually like 3 but more aggressive.

**Comment by infiniteregrets** [comment]
not happening on main

```
../mirrord/target/universal-apple-darwin/debug/mirrord exec mix phx.server
⠖ mirrord exec
    ✓ Running on latest (3.73.1)!
    ✓ ready to launch process
      ✓ layer extracted
      ✓ connected to operator
      ✓ comparing versions                                                                                                                                                    [info] Running MirrordDemoAppWeb.Endpoint with cowboy 2.10.0 at 127.0.0.1:4000 (http)
[info] Access MirrordDemoAppWeb.Endpoint at http://localhost:4000
[info] GET /
```
