### ISSUE TITLE
New Subcommand for Generating Shell Completions

### ISSUE THREAD

**Issue by bradschwartz** [metalbear-co/mirrord#1947]
I'm proposing a new subcommand that can generate shell completions. The `clap` crate is already being used for actually building the `mirrord` CLI, and they already build a crate [`clap_complete`](https://github.com/clap-rs/clap/tree/master/clap_complete) to make generating shell completions simple for a few popular shells (bash, fish, zsh, powershell, elvish). This would make discoverability of flags and subcommands much simpler to newcomers and as the number of options grow.

It looks like some subcommands are hidden (like `extract` and `verify`) - I don't know if clap_complete supports _not_ generating completions for them, or if that would be an issue if they were.

It would look like:

```bash
$ mirrord completions bash
### long output of bash completion to stdout truncated here

## could directly source
$ source <(mirrord completions bash)

$ mirrord exec <TAB><TAB>
-t                             -c                             --agent-namespace              --skip-processes               --no-outgoing                  --help
-n                             -e                             --agent-log-level              --agent-ttl                    --no-tcp-outgoing              <BINARY>
-a                             -p                             --agent-image                  --agent-startup-timeout        --no-udp-outgoing              [BINARY_ARGS]...
-l                             -f                             --fs-mode                      --accept-invalid-certificates  --no-telemetry                 
-i                             -h                             --override-env-vars-exclude    --ephemeral-container          --disable-version-check        
-x                             --target                       --override-env-vars-include    --steal                        --config-file                  
-s                             --target-namespace             --no-remote-dns                --pause                        --context   

$ mirrord exec --fs-mode <TAB><TAB>
write                 read                  local                 local-with-overrides  
````

I know Homebrew has some nice functionality for calling these scripts and putting the generated output/files to sane places to source from when mirrord is installed, not sure about other package managers.

Happy to do the implementation myself, it should be fairly straightforward.

**Comment by eyalb181** [comment]
Hey @bradschwartz, sounds good! Would be great if you could implement yourself, we're here or on Discord if any help is needed
