### ISSUE TITLE
mirrord ls use operator if available

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1959]
Right now `mirrord ls` uses user's access to get targets which means it might have options that operator don't and vice versa.
Don't implement it until operator returns containers also to not break current users.

**Comment by eyalb181** [comment]
Blocked by Operator #325

**Comment by eyalb181** [comment]
The above mentioned issue was completed, can this be unblocked? @aviramha

**Comment by aviramha** [comment]
yes

**Comment by aviramha** [comment]
https://github.com/metalbear-co/operator/issues/325 is the correct issue.

**Comment by t4lz** [comment]
When doing this change, we can also change the `mirrord ls` code in the cli to also list container targets for deployments and argo rollouts, not only for pods. The operator will already include those targets in the target list.

**Comment by t4lz** [comment]
Another note: in the non-operator code of `mirrord ls`, the containers are filtered by name:

https://github.com/metalbear-co/mirrord/blob/e92c20d2d117170c3186799f8c7cdafb615779b4/mirrord/cli/src/main.rs#L270

The same filter should be performed after fetching the target list from the operator, as the operator does not pre-filter the results.

**Comment by t4lz** [comment]
https://github.com/metalbear-co/mirrord/pull/2437
