### ISSUE TITLE
Allow specifying targetless in configuration file

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1962]
Following [Discord discussion](https://discord.com/channels/933706914808889356/1154898142739832934) we realized there's no way to mention that user wants targetless without interactive flow for the IDE plugins.
I suggest the possible configuration to be supported:
```json
{
"target": "targetless"
}
```
another option is `"target": null` but it'd be tricky from the IDE perspective to distinguish an explicit null vs just missing value.

**Comment by eyalb181** [comment]
Seems to have already been implemented.
