### ISSUE TITLE
asdf + mix doesn't work on macOS

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1966]
asdf gets a broken pipe error
(mix of Elixir)

**Comment by aviramha** [comment]
@bradschwartz please fill if it's arm or Intel

**Comment by bradschwartz** [comment]
> @bradschwartz please fill if it's arm or Intel

ARM machine:
```bash
$ bash --version
GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.1.0)

$ asdf --version
v0.13.1
```

**Comment by aviramha** [comment]
I couldn't reproduce it with asdf on 3.70.0 - maybe the issue we had for elixir itself was same as what asdf faced?

**Comment by aviramha** [comment]
Happens only with brew.

**Comment by aviramha** [comment]
> @aviramha and you said your brew didn't replicate right? So potentially just something weird with how I've set my environment up?
> 
> 

Makes sense, yes. I'll have someone else from the team with a Mac to try it out.

**Comment by aviramha** [comment]
@infiniteregrets tried the following and didn't reproduce as well:
```sh
brew install asdf
asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf plugin add elixir https://github.com/asdf-vm/asdf-elixir.git
git clone git@github.com:bradschwartz/mirrord_demo.git
cd mirrord_demo
mix deps.get
mix deps.compile
mix compile
mix run --no-halt
mirrord exec -- mix run --no-halt
```

**Comment by bradschwartz** [comment]
Thanks for taking a look @infiniteregrets ! 

Up to the mirrord team if you want to keep this issue open or close as non-reproducible, but I'm going to wait until that refactor lands before diving in again. Thanks!

**Comment by ooaklee** [comment]
I'm also experiencing `asdf` + `mix` not working with `mirrord` on my M1 MacBook. Using [**the demo repo**](git@github.com:bradschwartz/mirrord_demo.git) with a couple of version tweaks on the `.tool_versions` so it works on my machine.

I am using the following setup:

- M1 MacBook using 14.1
- asdf v0.13.1


> `.tool_versions` below

```
elixir 1.14.5-otp-25
erlang 25.3.2.7
```  

When using the commands [outlined above](https://github.com/metalbear-co/mirrord/issues/1966#issuecomment-1744286263), I get  the output below. When using the `mix run --no-halt` without `mirrord`, it works as expected.

```
⠐ mirrord exec
    ✓ Running on latest (3.74.1)!
    ✓ ready to launch process
      ✓ layer extracted
      ✓ no operator detected
      ✓ container created
      ✓ container is ready                                         
/opt/homebrew/opt/asdf/libexec/lib/utils.bash: line 726: cannot create temp file for here document: No such file or directory
/opt/homebrew/opt/asdf/libexec/lib/utils.bash: line 729: cannot create temp file for here document: No such file or directory
/opt/homebrew/opt/asdf/libexec/lib/utils.bash: line 737: cannot create temp file for here document: No such file or directory
/opt/homebrew/opt/asdf/libexec/lib/utils.bash: line 738: cannot create temp file for here document: No such file or directory
/opt/homebrew/opt/asdf/libexec/lib/utils.bash: line 743: cannot create temp file for here document: No such file or directory
/opt/homebrew/opt/asdf/libexec/lib/utils.bash: line 780: cannot create temp file for here document: No such file or directory
/opt/homebrew/opt/asdf/libexec/lib/utils.bash: line 568: cannot create temp file for here document: No such file or directory
No plugin given
/opt/homebrew/opt/asdf/libexec/lib/utils.bash: line 592: cannot create temp file for here document: No such file or directory
No mix executable found for  
```

> Note: I am using `mirrord exec` with the ephemeral agent setting enabled

**Comment by aviramha** [comment]
Original issue seems to be resolved but leaving this open in light of last comment.

**Comment by ooaklee** [comment]
Hey @aviramha, after some more digging, it turns out that the issue was related to the fact that my M1 Mac was using the default bash version, which was `3.2.57`!


After running the commands below, I was able to get my mac use the `version 5.2.15` bash, which, as a result, enabled me to run `mirrord` as expected.

```sh
which -a bash # note the path of your default bash
brew install bash
which -a bash # verify that you can see two versions of bash, i.e. /opt/homebrew/bin/bash & /bin/bash
sudo vim /etc/shells # Add the path for the newly added bash to our system whitelist
vim ~/.zshrc # Add the following `export PATH="<path-to-homebrew-bin>:$PATH"`, i.e. `export PATH="/opt/homebrew/bin:$PATH"`  to the end of the file so that it will use the newest version of bash by default (this will vary dependent on default shell)
# reopen terminal/ shell and reattempt the mirrord command
```

**Comment by aviramha** [comment]
> Hey @aviramha, after some more digging, it turns out that the issue was related to the fact that my M1 Mac was using the default bash version, which was `3.2.57`!
> 
> 
> 
> 
> 
> After running the commands below, I was able to get my mac use the `version 5.2.15` bash, which, as a result, enabled me to run `mirrord` as expected.
> 
> 
> 
> ```sh
> 
> which -a bash # note the path of your default bash
> 
> brew install bash
> 
> which -a bash # verify that you can see two versions of bash, i.e. /opt/homebrew/bin/bash & /bin/bash
> 
> sudo vim /etc/shells # Add the path for the newly added bash to our system whitelist
> 
> vim ~/.zshrc # Add the following `export PATH="<path-to-homebrew-bin>:$PATH"`, i.e. `export PATH="/opt/homebrew/bin:$PATH"`  to the end of the file so that it will use the newest version of bash by default (this will vary dependent on default shell)
> 
> # reopen terminal/ shell and reattempt the mirrord command
> 
> ```

Interesting. Do you mind creating a new issue as it seems to be different than OP?

**Comment by ooaklee** [comment]
Sure @aviramha, I've added created a new issue https://github.com/metalbear-co/mirrord/issues/2051#issue-1974780355
