### ISSUE TITLE
no file named /opt/homebrew/bin/mix

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1967]
when running mix installed from homebrew on macOS using mirrord, it errors out with `/opt/homebrew/bin/mix`
It also has the #1946 issue, but I think this one is the real blocker.

**Comment by bradschwartz** [comment]
Can replicated using this demo app: https://github.com/bradschwartz/mirrord_demo

**Comment by aviramha** [comment]
I ran an experimental branch that gets rid of #1946 but still had the issue + crash, so it fortifies my assumption that this is the real blocker.

**Comment by t4lz** [comment]
reproduction of the underlying erlang issue: https://github.com/t4lz/erlang-mirrord-bug-repro/

**Comment by aviramha** [comment]
I found out that the issue was introduced in https://github.com/metalbear-co/mirrord/commit/134b7e30564b9a11798a348f584b73fa758f4160
