### ISSUE TITLE
Improve `mirrord-agent` `Args` handling by using `json`.

### ISSUE THREAD

**Issue by meowjesty** [metalbear-co/mirrord#1980]
`mirrord-agent` is started with a cli interface, meaning that if we want to pass args to its initialization, we do it like so: `agent --arg1 "value1" --arg2 "value2"`. Which can be problematic if the arg comes after a sub-command, such as `mode`.

I kinda lost some time trying to add a new arg (`--mesh`) due to this being the case, so I'm proposing we change it to take a json instead of this args thing.

The initialization could be something like `agent "{ "arg1": "value1", "arg2": "value2" }", thus we won't have to care about the order of things ever again.

The json could be also put in the env, thus starting the agent with just `agent`, but I think the explicit version is friendlier to use, tbh.

**Comment by aviramha** [comment]
Should be via env anyway
