### ISSUE TITLE
Add sanity tests for the VS Code extension

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#201]
We don't test the VS Code extension at the moment, so changes there are risky. Please add a suite of sanity tests and have them run in the CI.

**Comment by eyalb181** [comment]
For now just one test should do, where we run a process with mirrord enabled, pick a pod and see that everything starts up properly. No need to then send traffic to the remote pod or anything.

**Comment by infiniteregrets** [comment]
relevant discussion: https://github.com/microsoft/vscode-discussions/discussions/274
