### ISSUE TITLE
`verify-config` lacks information to distinguish `targetless` from missing `target` in config.

### ISSUE THREAD

**Issue by meowjesty** [metalbear-co/mirrord#2010]
### Bug Description

When `verify-config` calls `generate_config`, `target` is converted to `null` both if the user set `target: targetless` and if they don't set it at all, becoming impossible to know if we should display the "select target" box in the IDEs.

- the config produces for both cases:

```json
{
  "type": "Success",
  "config": {
    "path": null,
    "namespace": null
  },
  "warnings": []
}
```

We should instead make `Targetless` become an actual value, or anything that we can use to distinguish it from missing the `target` option altogether.

### Steps to Reproduce

...

### Your operating system and version

...

### Local process

mirrord verify-config

**Comment by eyalb181** [comment]
@meowjesty @Razz4780 Was this done already?
