### ISSUE TITLE
Save users from stumbling over fs exceptions

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#2018]
A lot of users have difficulties using mirrord because they don't know about the path patterns that are read locally by default in all fs modes.

We have to help them know those patterns exist and also make it easy enough to find out what they are and what to do if you want to read remotely a path that is covered by those patterns.

Same goes for other default pattern sets - not found, read remotely.

TODO:

- [x] #2019
- [x] https://github.com/metalbear-co/mirrord.dev/issues/179
- [x] https://github.com/metalbear-co/mirrord.dev/issues/180
- [x] #2020
  - [x] https://github.com/metalbear-co/mirrord.dev/issues/181

**Comment by eyalb181** [comment]
Removed #2008 (will be some time before we get to it), closing this.
