### ISSUE TITLE
Go service hangs when trying to "Run Without Debugging"

### ISSUE THREAD

**Issue by drehelis** [metalbear-co/mirrord#2029]
### Bug Description

- vscode, macOS (m1), Go service in a devcontainer.

Trying to start the service with "Run Without Debugging" simply hangs on:
```
Starting: /go/bin/dlv dap --listen=127.0.0.1:41171 --log-dest=3 from /workspaces/service-name
DAP server listening at: 127.0.0.1:41171
```

"Start Debugging" however, works and service bootstraps successfully.

I've managed to narrow this down to the `dlv` [v1.21.1](https://github.com/go-delve/delve/releases/tag/v1.21.1) package, downgrading to [v1.21.0](https://github.com/go-delve/delve/releases/tag/v1.21.0) solves the hang.

mirrord.json -
```
{
    "target": "deployment/service-name/container/service-name",
    "accept_invalid_certificates": false,
    "feature": {
        "network": {
            "incoming": {
                "mode": "steal",
                "ignore_localhost": true
            },
            "outgoing": {
                "ignore_localhost": true
            }
        },
        "fs": "read",
        "env": true
    },
    "pause": true,
    "agent": {
        "ephemeral": true,
        "privileged": true
    }
}

```

### Steps to Reproduce

1. Open repository in vscode's devcontainer
2. Our devcontainer's Dockerfile includes the following 
```
RUN go install -v golang.org/x/tools/gopls@latest && \
    go install -v github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest && \
    go install -v github.com/go-delve/delve/cmd/dlv@latest && \
    go install -v github.com/vektra/mockery/v2@latest && \
    go install -v github.com/golangci/golangci-lint/cmd/golangci-lint@latest && \
    go install -v github.com/fatih/gomodifytags@latest
```
3. Run "Run Without Debugging"

### Your operating system and version

macOS m1

### Local process

internal go service

### Local process version

latest

**Comment by aviramha** [comment]
I believe this is an upstream bug in delve, that we aren't related to following review of Delve's changelog.
Checking their issue tracker and commit history since the release for fixes, I saw the following:
https://github.com/go-delve/delve/commit/f90ede46539400c5497cc0f0f5b6f676de72d40a
which seems to be very related to what user here experiences. Please try using compiled version post-that commit and let us know if it works for you.

**Comment by aviramha** [comment]
User verified it works with Delve from master (known issue in 1.21.1)
