### ISSUE TITLE
Outdated docs mention `http_header_filter`.

### ISSUE THREAD

**Issue by meowjesty** [metalbear-co/mirrord#2030]
Parts of the config documentation still mention the old `http_header_filter` option that is deprecated. The docs should only show how to use the new `http_filter`, which supports both `header_filter` and `path_filter`.

I've spotted this in the docs for `IncomingFileConfig`, and in `LayerConfig`.

To fix this, change the docs to show the newest config, re-build the schema, run medschool and publish the generated docs to mirrord.dev.

Side question: For how long are keeping both versions? What's our policy for removing deprecated stuff?

**Comment by infiniteregrets** [comment]
closes by https://github.com/metalbear-co/mirrord.dev/pull/210
