### ISSUE TITLE
VolumeMount on `/etc/webhooks/certs/` is missing on local process

### ISSUE THREAD

**Issue by gshaibi** [metalbear-co/mirrord#2031]
### Bug Description

Hi guys!
I hope you are all safe and well during these challenging times.

We have a deployment that creates a pod with a volume sourced from a TLS secret and mounted on the pod's container under `/etc/webhooks/certs`.
When I run `mirrord exec`, the local process fails since it can't find the TLS files on the `certs` directory.

Mirrord configuration:
```
{
    "target": {
        "path": {
            "deployment": "accessrule-controller"
        },
        "namespace": "runai"
    },
    "feature": {
        "env": true,
        "fs": "read"
    }
}
```

Mirrord verison: `mirrord 3.73.0`

Please tell me if there is anything else I can provide, or if I did something wrong here.
Thank you.

### Steps to Reproduce

1. Create a deployment with a TLS secret volume mounted on the `/etc/webhooks/certs` directory of the container.
2. Run `mirrord exec` with fs:"read"
3. The TLS secret data doesn't exist (in my case) on the mounted directory from the process perspective.

### Your operating system and version

MacOS 14.0 (23A344)

### Local process

/opt/homebrew/bin/go: Mach-O 64-bit executable arm64

**Comment by gshaibi** [comment]
Mirrord trace logs attached

[mirrord.log](https://github.com/metalbear-co/mirrord/files/13162498/mirrord.log)

**Comment by eyalb181** [comment]
Hey @gshaibi , any chance it's [this issue](https://mirrord.dev/docs/overview/faq/#my-application-is-trying-to-read-a-file-locally-instead-of-from-the-cluster)?

**Comment by gshaibi** [comment]
Yes, it is!
Thank you very much, sorry for the bother 🙇
