### ISSUE TITLE
Allow for overriding remote environment variables with those from a local file.

### ISSUE THREAD

**Issue by cslamar** [metalbear-co/mirrord#2045]
Looking for a way to override the remote environment variables from a local file, like a `.env` file.  This would allow for a quick way to replace only targeted variables without having to directly edit the main mirrord config every time a variable should be overridden. 

Could be done with something like 

```
{
  "feature": {
    "env": {
      "override": {
        "DATABASE_CONNECTION": "db://localhost:7777/my-db",
        "LOCAL_BEAR": "panda"
      },
      "overrideEnvFile": "./env"
    }
  }
}
```

or if possible, have mirrord check what's defined locally and then override from there.

Thanks!

**Comment by eyalb181** [comment]
This has actually already been suggested - see #1913 . Closing this one as duplicate.
