### ISSUE TITLE
Buffer file contents locally when reading files

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#2067]
Some applications read files byte-by-byte and when reading remotely this currently takes forever even for not that large files.

Users faced this issue with an application that reads a key file for connecting to a DB a URL like `jdbc:postgresql://<DB-LOCATION>?sslmode=verify-ca&sslrootcert=/run/secrets/rds_public_key/some_cert.pem`.
With a 7kb cert file it apparently takes forever. 

In order to prevent this huge slowdown we could read remotely with a bigger buffer than the app actually has, and then buffer the data locally and only make a new request to the agent once we finished the local buffer.

Currently users facing this issue are working around it by downloading the file to their computer and configuring mirrord to read it locally.

**Comment by eyalb181** [comment]
Duplicates #2069
