### ISSUE TITLE
Connecting to a PostgreSQL DB with JDBC takes forever 

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#2069]
### Bug Description

User connects to the DB with a URL like `jdbc:postgresql://<DB-LOCATION>?sslmode=verify-ca&sslrootcert=/run/secrets/rds_public_key/some_cert.pem`, the PostreSQL jdbc driver reads the provided cert file byte-by-byte, so we send a request to the agent for each byte in the file and that is way too slow.

### Steps to Reproduce

Write a Java app that connects to a URL like `jdbc:postgresql://<DB-LOCATION>?sslmode=verify-ca&sslrootcert=/run/secrets/rds_public_key/some_cert.pem` and run with mirrord

### Your operating system and version

macOS

### Additional Info

We could do #2067 in order to optimise reading the file.

As a temporary workaround the user downloads the cert file and tells mirrord to read it locally, but that path can't be written to on macOS so currently the user also has to change the cert file's path in the URL argument in the app's code, which is suboptimal. #2068 could help with that as at least the user would not have to change the app's code for that workaround.

**Comment by aviramha** [comment]
Fixed in #2979 - requires config for now:
```json
{"experimental": {"readonly_file_buffer": 4096}}
```
