### ISSUE TITLE
Erlang - `Cluster.Strategy.Kubernetes` leads to error

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#2077]
### Bug Description

When using [`Cluster.Strategy.Kubernetes`]( https://hexdocs.pm/libcluster/Cluster.Strategy.Kubernetes.html) as a strategy users get an error:

```
{"time":"2023-11-09T18:17:39.456Z","severity":"error","message":"[libcluster:service_cluster] request to kubernetes failed!: {:failed_connect, [{:to_address, {'kubernetes.default.svc.cluster.local', 443}}, {:inet, [:inet], :nxdomain}]}","metadata":{"domain":["elixir"],"erl_level":"error"}}
```

### Steps to Reproduce

The declaration of the topology is

```Erlang
 topologies = [
            service_cluster: [
              strategy: Cluster.Strategy.Kubernetes,
              config: [
                kubernetes_ip_lookup_mode: :pods,
                kubernetes_node_basename: app_name,
                kubernetes_selector: "app=#{app_name}-web",
                kubernetes_namespace: namespace,
                polling_interval: polling_interval
              ]
            ]
          ]
```

### Your operating system and version

Mac OS 14.1

### Local process

User is developing in Elixir

### Additional Info

https://canary.discord.com/channels/933706914808889356/1169678897420439582/1174664744146309150

User works around the issue by changing their code to use `Elixir.Cluster.Strategy.DNSPoll`.

**Comment by aviramha** [comment]
Should be retested after https://github.com/metalbear-co/mirrord/pull/2179

**Comment by eyalb181** [comment]
@infiniteregrets Can you retest please?
