### ISSUE TITLE
Mirrord extension on VsCode Failing

### ISSUE THREAD

**Issue by devdut1999** [metalbear-co/mirrord#2083]
### Bug Description

I am getting an error:
mirrord error: Create agent failed. KubeError( Api( ErrorResponse { status: "Failure", message: "Unauthorized", reason: "Unauthorized", code: 401, }, ), )

### Steps to Reproduce

I export the AWS credentials on the VsCode CLI
Then I update kubeconfig 
I enable the mirrord button
Then I debug the python file.

### Your operating system and version

MacOS Ventura Version 13.4.1

### Local process

Trying to run a python file

**Comment by devdut1999** [comment]
users:
- name: arn:aws:eks:us-west-2:894794456443:cluster/control-plane
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - control-plane
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: sso-dev
- name: arn:aws:eks:us-west-2:894794456443:cluster/eureka
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - eureka
      - --output
      - json
      command: aws
- name: arn:aws:eks:us-west-2:575580285474:cluster/eureka
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - eureka
      - --output
      - json
      command: aws
- name: arn:aws:eks:us-west-2:575580285474:cluster/control-plane
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - control-plane
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: sso-dev

**Comment by devdut1999** [comment]
Did you add your aws keys to your launch.json file?

**Comment by aviramha** [comment]
How did you create your kubeconfig entry?

**Comment by devdut1999** [comment]
I followed the follwing steps

Install the latest [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html) 

Edit ~/.aws/config and add the following. Developers have access to saas aws accounts for dev environment through okta.
[profile sso-dev]
sso_start_url = https://d-9a672829d2.awsapps.com/start
sso_region = us-east-2
sso_account_id = 894794456443
sso_role_name = SaaS-InfraAdmin
region = us-west-2
output = json
Now we are ready to login via sso to the dev account. Run the command
BROWSER=/usr/bin/true aws sso login --profile sso-dev
This prints a url and an access code. Open the URL in the browser that you use for okta.

You are authenticated to AWS, you can check it via the command
AWS_PROFILE=sso-dev aws sts get-caller-identity. 

To get access to EKS Kubernetes cluster, first you need to update your ~/.kube/config using AWS CLI: AWS_PROFILE=sso-dev aws eks --region us-west-2 update-kubeconfig --name control-plane
Verify you can run kubectl commands:
AWS_PROFILE=sso-dev kubectl get pods
