### ISSUE TITLE
mirrord-agent is attempting to perform a DNS lookup on my Macbook local hostname through the remote pod (DnsLookupError)

### ISSUE THREAD

**Issue by nabeelpaytrix** [metalbear-co/mirrord#2084]
### Bug Description

When running a Springboot application through IntelliJ with the MirrorD plugin enabled, my application starts successfully. However when inspecting the logs from the generated `mirrord-plugin` pod I see the following error:

```
2023-11-27T22:32:09.371776Z  WARN ThreadId(07) mirrord_agent::outgoing::udp: interceptor_task -> no messages left
2023-11-27T22:32:09.371883Z  WARN ThreadId(06) mirrord_agent::outgoing: interceptor_task -> no messages left
2023-11-27T22:32:10.284308Z ERROR ThreadId(03) mirrord_agent::dns: dns_lookup -> ResponseError:: DnsLookup(DnsLookupError { kind: NoRecordsFound(3) })
2023-11-27T22:32:14.840138Z  WARN ThreadId(05) mirrord_agent::steal::ip_tables::flush_connections: `conntrack` output is Output {
    status: ExitStatus(
        unix_wait_status(
            256,
        ),
    ),
    stdout: "",
    stderr: "conntrack v1.4.7 (conntrack-tools): 0 flow entries have been updated.\n",
}

```

I have increased the log_level on the agent and discovered this log using:

```
"agent": {
    "log_level": "mirrord=trace,warn"
}
```

The output of the log included:

```
2023-11-27T22:36:53.900040Z TRACE ThreadId(03) dns_lookup: mirrord_agent::dns: return=Err(DnsLookup(DnsLookupError { kind: NoRecordsFound(3) })) root_path="/proc/115758/root" host="MY_MACBOOK_HOSTNAME"
```

I could not find any indication of my SpringBoot application trying to connect to MY_MACBOOK_HOSTNAME, is this something which the `mirrord-agent` tries to do out of the box? Is there a way to disable this dnslookup?

### Steps to Reproduce

1. Potentially only reproducible on a Macbook Pro M2 with Sonoma 14.0
2. Install the IntelliJ MirrorD plugin
3. Ensure your kubectl is configured with a remote cluster
4. Create a helloworld springboot application 
5. Run a similar SpringBoot helloworld app within the remote cluster on port `8080`
6. Use the following mirrord.json config:
```
{
    "target": "pod/REMOTE_POD_NAME/container/CONTAINER_NAME",
    "accept_invalid_certificates": true,
    "feature": {
        "network": {
            "incoming": {
                "mode": "steal",
                "port_mapping": [[ 8080, 8080 ]]
            },
            "outgoing": true
        },
        "fs": "read",
        "env": true
    },
    "agent": {
        "ttl": 120,
        "privileged": true,
        "log_level": "mirrord=trace,warn"
    }
}
```
7. Attempt to run the springboot application on port `8080`
8. The spring boot application should succesfully start up
9. View the logs on the `mirrord-agent` pod in the remote cluster, there will be alot of logs due to `mirrord=trace,warn`
10. Search within the logs for `NoRecordsFound`
11. Confirm if your macbook hostname appears in the this log

### Your operating system and version

MacOS Sonoma 14.0

### Local process

Java SpringBoot Application

### Local process version

Java 14

**Comment by aviramha** [comment]
Thanks for reporting this. Just to clarify, besides seeing this happen, what's the actual symptoms of the problem? Are you not able to receive traffic? Something else?
In general this might happen (as part of internal app/framework logic) so I wouldn't be worried on the specified event..

**Comment by nabeelpaytrix** [comment]
@aviramha My Java application starts successfully, but my local application is not receiving any traffic sent to the remote pod. I'm not sure if the DnsLookupError is a Red Herring, but it's the only error I could see within the mirrod-agent Job logs.

Addiitionally, I've tried this now with the VSCode plugin and the outcome is the same, the same DnsLookupError is printed and my local spring app does not receive stolen traffic from the cluster

**Comment by nabeelpaytrix** [comment]
Also here is some additional TRACE logs from the `mirrord-agent` pod:

I think this suggests the remote pods DNS server is being used to resolve IPs for hostnames within the cluster context:
```
2023-11-28T13:07:11.271601Z TRACE ThreadId(01) start:handle_client_message:handle_message:open: mirrord_agent::file: new cancellation_token=CancellationToken { is_cancelled: f
alse } FileRequest(Open(OpenFileRequest { path: "/etc/resolv.conf", open_options: OpenOptionsInternal { read: true, write: false, append: false, truncate: false, create: false
, create_new: false } })) request=Open(OpenFileRequest { path: "/etc/resolv.conf", open_options: OpenOptionsInternal { read: true, write: false, append: false, truncate: false
, create: false, create_new: false } }) path="etc/resolv.conf" open_options=OpenOptionsInternal { read: true, write: false, append: false, truncate: false, create: false, crea
te_new: false }
```

Also my local service is successfully sending `outgoing` calls to other services, e.g. MongoDB and RabbitMQ. Which would only be accessible within the cluster
```
2023-11-28T13:07:13.688071Z TRACE ThreadId(01) start:handle_client_message: mirrord_agent: new cancellation_token=CancellationToken { is_cancelled: false } GetAddrInfoRequest(GetAddrInfoRequest { node: "rabbitmq.mydomain" })
2023-11-28T13:07:13.688104Z TRACE ThreadId(01) start:handle_client_message:make_request: mirrord_agent::dns: new cancellation_token=CancellationToken { is_cancelled: false } GetAddrInfoRequest(GetAddrInfoRequest { node: "rabbitmq.mydomain" }) request=GetAddrInfoRequest { node: "rabbitmq.mydomain" }
```

But I don't see any logs to suggest that `inbound` traffic to the remote pod is successfully hitting my local pod.
I have triple checked that the target is correct in the `mirrord.json` file.

**Comment by aviramha** [comment]
It is probably a red herring.
Is the remote application also listening on port 8080?

**Comment by aviramha** [comment]
@nabeelpaytrix i might have asked this already but do you have more than one container in the pod? If so you're probably not specifying it explicitly making mirrord randomly select. 
If that's not the case, would you like to schedule time with us using the button on mirrord.dec so we can debug it together?

**Comment by nabeelpaytrix** [comment]
Hello @aviramha 

I've been looking into the issue today and it appears that HTTP traffic was successfully being intercepted on port 8080, but the traffic I was testing was GRPC traffic on port 9090, and only specific actions in my Portal would trigger a call to my applications GRPC port.

Definitely a user error, thank you for helping me debug this issue.

I have been able to identify that the default behaviour in MirrorD is to map all ports exposed by my service even if I don't include every port in the `port_mapping` which isn't an issue for my use case, but saves me from having to declare every port.

**Comment by aviramha** [comment]
Great! Happy that you have it resolved and I hope you'd have a wonderful experience using it further
Let us know if we can be of any help 🙌
