### ISSUE TITLE
unsuccessful tunnel (HTTP/1.0 502 Bad - When connecting to local k3d cluster inside WSL2 

### ISSUE THREAD

**Issue by visbvr** [metalbear-co/mirrord#2123]
### Bug Description

`Create agent failed. KubeError( HyperError( hyper::Error( Connect, Custom { kind: Other, error: "unsuccessful tunnel (HTTP/1.0 502 Bad)", }, ), ), )`

The image can be pulled normally in the cluster.

### Steps to Reproduce

1. Create k3d cluster with running pods
2. Confirm pods run normally and kubectl get pods returns expected results
3. Start intellij mirrord plugin 
4. Error is shown

### Your operating system and version

"Ubuntu 20.04.6 LTS"

### Local process

amazon-corretto-17.0.2.8.1-linux-x64/bin/java

**Comment by aviramha** [comment]
hi,
this error usually happens when you have `HTTP_PROXY`, `HTTPS_PROXY` or `SOCKS_PROXY` set.
Can you check your env and see if it's set? if it is, can you unset it in the run configuration (just set it to '')

**Comment by visbvr** [comment]
Thank you for your quick answer. After unsetting the proxy the error was gone and the agent appeared in the cluster. But a second error followed:
`Couldn't get port of internal proxy`
Any idea what could case this?
Thanks!

**Comment by aviramha** [comment]
That usually happens if agent pod fails to run - you can check the job status by using kubectl get jobs and also describe the pod it creates.
If you don't see it you can extend the time it stays after being done by setting MIRRORD_AGENT_TTL to 120.

**Comment by aviramha** [comment]
Maybe try to enable invalid certificate
```json
"accept_invalid_certificate": true
```

**Comment by visbvr** [comment]
Thanks again for your reply. Setting MIRRORD_AGENT_TTL to 120 did the trick for me.

**Comment by aviramha** [comment]
> Thanks again for your reply. Setting MIRRORD_AGENT_TTL to 120 did the trick for me.

Actually it's quite impossible that that fixed it (since it doesn't do anything but make the pod stay for 120 secs post completion..)
