### ISSUE TITLE
Handle WebSockets in filtered HTTP steal

### ISSUE THREAD

**Issue by Razz4780** [metalbear-co/mirrord#2126]
When an `UPGRADE` request is detected and matched (against header or path), need to steal the current TCP connection completely.
Relevant piece of code [here](https://github.com/metalbear-co/mirrord/blob/fa2af7f1e77a9254fb0908be40b0dae5da53d298/mirrord/agent/src/steal/http/hyper_handler.rs#L206)

Edit: I found it very hard to navigate in the `agent::steal` module. I don't want to add more special cases and channels there, also spotted 3 bugs. Also, adjusting stuff to allow switching from http connection to raw tcp connection is not trivial. This time I'm gonna do series of smaller PR's to do this

* [x] #2213 
* [x] #2270
* [x] #2214
* [x] #2224

**Comment by aviramha** [comment]
Edited OP to mention that only matched UPGRADE would make the whole connection stolen.
