### ISSUE TITLE
Add userextras/oid mirrord-operator cluster role

### ISSUE THREAD

**Issue by revanth-Infoworks** [metalbear-co/mirrord#2152]
### Bug Description

I am using mirrord team with AKS (1.25.15)

I installed mirrord with
`mirrord operator setup --accept-tos --license-path ~/mirrord-license.pem  | kubectl apply  -f -`

I see below error in mirrord pod when trying I try run

`mirrord exec -f ~/mirror-config.json node target/Index.js`

`2023-12-27T05:51:35.062668Z ERROR operator_controller::restful: get resource, error: "ApiError: userextras.authentication.k8s.io \"0cc8e575-bb90-4efe-94a3-f51330bc1836\" is forbidden: User \"system:serviceaccount:mirrord:mirrord-operator\" cannot impersonate resource \"userextras/oid\" in API group \"authentication.k8s.io\" at the cluster scope: Azure does not have opinion for this user.: Forbidden (ErrorResponse { status: \"Failure\", message: \"userextras.authentication.k8s.io \\\"0cc8e575-bb90-4efe-94a3-f51330bc1836\\\" is forbidden: User \\\"system:serviceaccount:mirrord:mirrord-operator\\\" cannot impersonate resource \\\"userextras/oid\\\" in API group \\\"authentication.k8s.io\\\" at the cluster scope: Azure does not have opinion for this user.\", reason: \"Forbidden\", code: 403 })"`

I needed to add "userextras/oid" to the resources for "impersonate" in mirrord-operator cluster role as the error suggests. 

Just logging it here incase this needs to be documented

### Steps to Reproduce

1. `mirrord operator setup --accept-tos --license-path ~/mirrord-license.pem  | kubectl apply  -f -`
2. `mirrord exec -f ~/mirror-config.json node target/Index.js`

### Your operating system and version

macos ventura (intel)

### Local process

node

**Comment by aviramha** [comment]
Thanks! We will add it to the definitions.
Note: need to do it in the helm chart and in this repo as well.
