### ISSUE TITLE
`fs_config_default` unit test is flaky on CI

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#2163]
Failed here: 
https://github.com/metalbear-co/mirrord/actions/runs/7466234067/job/20317188352?pr=2162#step:36:439

Successful here without any change in the code:
https://github.com/metalbear-co/mirrord/actions/runs/7466234067/job/20317958535

**Comment by t4lz** [comment]
Also [`feature::fs::advanced::tests::advanced_fs_config_default`](https://github.com/metalbear-co/mirrord/actions/runs/7693486800/job/20962365645?pr=2210#step:36:438)

**Comment by Razz4780** [comment]
I think I remember doing a short investigation of this. The config unit tests may not be properly isolated - some tests are setting values in the current env and those values are later read by other tests when generating config.
