### ISSUE TITLE
copy + replace with reload

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2177]
When reloading/restarting an app with copy+replace it fails. Probably the lock happens. The issue happens with IntelliJ but I assume it might happen in other scenarios - we can think of solving it from the IDE (waiting for last session to close) or from the operator side. Need to reproduce with IDE and without and see what would be the best solution.

**Comment by aviramha** [comment]
You didn't enable `scaledown`.

**Comment by infiniteregrets** [comment]
> You didn't enable scaledown

thanks, this reproduced the issue, it makes sense why it happens. I think providing just an error message to try again from the operator would make sense and not the IDE and that same error can be propagated to user in the IDE. Do you have something else in mind?

**Comment by aviramha** [comment]
We could make a scaledown session be re-used... @Razz4780 thoughts?

**Comment by infiniteregrets** [comment]
> We could make a scaledown session be re-used... @Razz4780 thoughts?

ok, that sounds reasonable, didn't think about it

**Comment by Razz4780** [comment]
> We could make a scaledown session be re-used... @Razz4780 thoughts?

Yeah, there would be no problem. I'd also consider case when the new session does not need scaledown - we should probably keep the old copied pod, but drop the scaledown
