### ISSUE TITLE
Add ability to exclude all local ENVs

### ISSUE THREAD

**Issue by emanuelef** [metalbear-co/mirrord#2225]
Hi,
in my case I have some ENV vars that are only present locally and not on the remote.
I'd like to have a setting where I can exclude all the local ENVs so only the remote ones are used, would that make sense ?
Thanks

**Comment by emanuelef** [comment]
Thanks, in my case I generally use a .env file and so the workaround for me is just remove all ENVs there.

**Comment by dcharbonnier** [comment]
the fact the local .env overwrite the remove env is also an issue for me we should not have this behavior by default or at least we should be able to disable it
