### ISSUE TITLE
Can not debug normally

### ISSUE THREAD

**Issue by ls-2018** [metalbear-co/mirrord#2242]
### Bug Description

![image](https://github.com/metalbear-co/mirrord/assets/38821215/7afcc52b-2b88-4922-b0de-83b316857f02)
![image](https://github.com/metalbear-co/mirrord/assets/38821215/ca30315a-72b4-48d4-9947-973c198046ee)
![image](https://github.com/metalbear-co/mirrord/assets/38821215/316d285a-1b10-4f8e-b2f8-0c7f5ffe2183)

### Steps to Reproduce

Can not debug normally, do not know what the problem

### Your operating system and version

macos  14.2.1 (23C71)

### Local process

ip-visit-counter: Mach-O 64-bit executable x86_64

**Comment by aviramha** [comment]
Hi, it seems agent can't be accessed/started. Can you add
```json
"agent": {ttl: 120}
```
to your configuration then see if the agent pod is being created?
