### ISSUE TITLE
use relative path to kubeconfig files in mirrord.json

### ISSUE THREAD

**Issue by jstrachan** [metalbear-co/mirrord#2262]
we have lots of different git repositories that work with different kubernetes clusters; so we tend to check in local kube config files to each git repository. e.g. relative to the git directory they may be in: `./kubeconfigs/dev/.kube/config` for the `Dev` environment

however I’ve only been able to refer to these project local kube config files using an absolute path in the `.mirrord/mirrord.json `file; all attempts at relative paths don't seem to work. I guess this is due to the mirrord plugin/agent running in a different temp directory maybe?

I wonder is it possible to use a relative path or expression/environment variable for the current IntelliJ project directory inside the `kubeconfig` value in the `.mirrord/mirrord.json` file? 

As I’d love to be able to check in the `.mirrord/mirrord.json` file to git but right now it only works on 1 persons laptop due to the absolute path.

If this isn’t supported yet I’ll happy try figure out a patch; any hints/tips greatly appreciated - thanks!

**Comment by aviramha** [comment]
Hey! Thanks for the suggestion.
We actually use `shellexpand` which should support tilde
```rs
        let kubeconfig = shellexpand::tilde(&kubeconfig);
        let parsed_kube_config = Kubeconfig::read_from(kubeconfig.deref())?;
```
I'll send a patch to also expand environment variables - I'm not sure what's the "current directory" from our execution context, but hopefully the env would be good enough?

**Comment by aviramha** [comment]
I've sent a PR - we just 2 releases today so I'd prefer to postpone it to early next week ;)

**Comment by jstrachan** [comment]
@aviramha many thanks!

is there a canonical env var for the current project directory I wonder? I guess thats maybe more of a question for the IntelliJ plugin; it could maybe pass that along when it runs mirrord agent

**Comment by aviramha** [comment]
@jstrachan not sure if we have the project directory from our context - seems there's an open issue for IntelliJ to provide it
https://youtrack.jetbrains.com/issue/IDEA-122504
Sadly it is open for quite long time, but it seems to be updated lately so maybe there's hope!
If you'd like to send a PR for the IntelliJ plugin to do it from our side, feel free to do so :)
