### ISSUE TITLE
Service account - AWS auth for operator

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2293]
1. Define required IAM Role json for users to apply
2. Add support for helm chart to have the operator service account required label/annotation to get the role

**Comment by Razz4780** [comment]
Blocked by SQS

**Comment by aviramha** [comment]
> Blocked by SQS

I think SQS is blocked by it, not the other way around no?

**Comment by Razz4780** [comment]
> I think SQS is blocked by it, not the other way around no?

Sorry, confusion. This is ready and should work fine, but there's no point in adding it right now
