### ISSUE TITLE
Mirrord intellij plugin is not working on intel CPU at all

### ISSUE THREAD

**Issue by avielb** [metalbear-co/mirrord#2315]
### Bug Description

hey! 
I am a DevOps engineer trying to enable working with mirrord for our developers and we run some issues using it. All of us using MacBooks. some with Intel CPU and some with M2/M3 (ARM). The current application that we all try to use now is a spring boot application and using using the IntelliJ plugin for mirrord. 
When starting a simple project (non spring boot) we have mirrord fully working (just like in a demo 😄 we see the dialog to select a pod for target, breakpoints are stopped when calling the application) but when trying to work with mirrord for the original application we see weird behavior. Looks like on Intel MacBooks we see the following: 
The dialog is not popping and we get "mirrord cancelled" popup
Breakpoints won't stop when calling the application
Connectivity to the kubernetes services is not working as well

When working with the application's code and on ARM MacBooks the dialog for selecting the target is not popping but the rest of the functionalities are working as expected

IntelliJ versions are all 2023.1 

### Steps to Reproduce

described above

### Your operating system and version

macOS 12.2

### Local process

.

**Comment by aviramha** [comment]
Hey, we can't manage to reproduce it.
Can you jump on a call to share screen to debug it together please?
