### ISSUE TITLE
compatability issue with IDE

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2339]
When running mirrord with current IntelliJ plugin it fails when targeting a deployment without operator installed.
Introduced in https://github.com/metalbear-co/mirrord/pull/2306

**Comment by ishaiboro** [comment]
Happen to me, waiting for fix, thx

**Comment by aviramha** [comment]
@ishaiboro we just rolled back the binary, can you retry?

**Comment by ishaiboro** [comment]
yes it works now thanks!

**Comment by ishaiboro** [comment]
Awesome product!!!

**Comment by aviramha** [comment]
Thank you! If you like it make sure to leave a review on the market place ;)

**Comment by aviramha** [comment]
> Awesome product!!!


@ishaiboro Thank you! If you like it make sure to leave a review on the market place ;)
