### ISSUE TITLE
Provide explanation before session start

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2367]
When user starts a session, provide information to it about their config, and what it would do.

For example:
```
Running binary X with args Y. mirrord Configuration file is C.
mirrord will target PODNAME. It will load all of its environment variables, provide access to its file for read only and will mirror all ports you're listening on locally
```

**Comment by aviramha** [comment]
Need to think how to add it later in the extensions.

**Comment by gememma** [comment]
So far, using `sub_progress.info` to log config details at the end of setup, I can print something like the following (I've shown multiple options in square brackets, separated with slashes):
```
* Running binary "/path/to/binary with arguments: ["sample/node/app.mjs"]
* mirrord will target: pod/py-serv-deployment-xxxxxx, [no configuration file was loaded/a configuration file was loaded from: path/to/config]
* env: [all/not all] environment variables will be loaded
* fs: file operations will default to [read only from the remote/read and write from the remote/read and write locally]
* incoming: incoming traffic will be [mirrored/stolen/ignored]
* outgoing: forwarding is [enabled on TCP, UDP/enabled on TCP/enabled on UDP/disabled on TCP, UDP]
```
Is there any important information that is missing here? I wasn't so sure about the `network.outgoing` section

**Comment by eyalb181** [comment]
I wonder if we need to display configurations that are set to their default value, @aviramha wdyt?
Also need to see how this displays on the extensions - if it looks bad we might want to disable it there, and find some more UI-y way to show it

**Comment by Razz4780** [comment]
>Is there any important information that is missing here?
I'd mention `dns` and `operator` settings as well

>Also need to see how this displays on the extensions
This info can be reported to the IDEs using `Progress:ide` method, I think. This way we can pass it to extension code in JSON and handle however we want

**Comment by aviramha** [comment]
> I wonder if we need to display configurations that are set to their default value, @aviramha wdyt? Also need to see how this displays on the extensions - if it looks bad we might want to disable it there, and find some more UI-y way to show it

I think the idea is to explain what is going to happen, so even if default values are used it's useful to explain.

**Comment by aviramha** [comment]
> I wonder if we need to display configurations that are set to their default value, @aviramha wdyt? Also need to see how this displays on the extensions - if it looks bad we might want to disable it there, and find some more UI-y way to show it

I think the idea is to explain what is going to happen, so even if default values are used it's useful to explain.
