### ISSUE TITLE
agent stays when passing mirrord a non-existing executable

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#2386]
### Bug Description

When you call `mirrord exec` with an executable that doesn't exist, an agent pod keeps running until it is manually deleted.

Impact on users: low - not reported by any users so far AFAIK. Won't prevent them from doing anything, will just leave lingering unwanted agent pods running, that they have to delete themselves, if they ever have a typo when typing their executable's name.

### Steps to Reproduce

```
mirrord exec no-such-binary
```

### Your operating system and version

macOS 14.4.1

### Local process

does-not-exist

**Comment by aviramha** [comment]
Are you sure that it's lingering for more than 60s? (Startup timeout)

**Comment by t4lz** [comment]
> Are you sure that it's lingering for more than 60s? (Startup timeout)

yes:

![image](https://github.com/metalbear-co/mirrord/assets/12370607/67015121-44eb-4bce-bc10-c76628be90fd)

**Comment by meowjesty** [comment]
Looking into this, found out it terminates after around 11 minutes lol.

![image](https://github.com/metalbear-co/mirrord/assets/43983236/218f870b-f856-4e37-8ead-f9eddf824e4c)

Working on decreasing this time though.
