### ISSUE TITLE
native dns resolving fails on macOS + Netty + Java when http filter is set

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2411]
The bug starts happening with 3.97.0. 3.96.1/0 works fine.
Last version also works if http filter is not set, meaning it's related to the port stealing logic somehow.
https://github.com/metalbear-co/mirrord/compare/3.96.0...3.97.0

**Comment by nabeelpaytrix** [comment]
I have created a reproducible example on this issue here: https://github.com/nabeelpaytrix/mirrord-srv-connections-broken

Please let me know if the instructions in the README are unclear or invalid
