### ISSUE TITLE
VS code: restarting during debugging often causes error `ConnectionRefused`

### ISSUE THREAD

**Issue by danielwinkler** [metalbear-co/mirrord#2432]
### Bug Description

During debugging code, if we restart the debugger, often i get the following error:

```
The program '[3763] WebAPI.dll' has exited with code 0 (0x0).
 
------------------------------------------------------------------------------You may only use the Microsoft Visual Studio .NET/C/C++ Debugger (vsdbg) withVisual Studio Code, Visual Studio or Visual Studio for Mac software to help youdevelop and test your applications.------------------------------------------------------------------------------
 
Using launch settings from './launchSettings.json' [Profile 'app']...
 
thread '<unnamed>' panicked at mirrord/layer/src/lib.rs:366:10:
 
failed to initialize proxy connection: IoFailed(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })
 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 
mirrord layer setup panicked
 
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
 
The program '[4653] WebAPI.dll' has exited with code 255 (0xff).
```

This can be mitigated by stopping the application and waiting, and then starting the debug process.

### Steps to Reproduce

1. Debug a .NET application
2. Do not stop the debugger, but restart it
3. The exits with the above error

### Your operating system and version

Linux devcontainer on a Windows host

### Local process

.net web app

**Comment by aviramha** [comment]
Hi!
Apologize for the inconvenience. I am pretty sure you're experiencing this known issue https://github.com/metalbear-co/mirrord-vscode/issues/43.
You could try setting
```json
{"internal_proxy": {"idle_timeout": 60}}
``` to have the internal proxy stay alive, which might be a way to workaround it.

**Comment by danielwinkler** [comment]
Dear @aviramha , 

Thank you for the very fast response, we're evaluating the settings and keeping you updated.

```
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Net.Http.dll
 
Exception thrown: 'System.Net.Http.HttpIOException' in System.Private.CoreLib.dll
 
Proxy error, connectivity issue or a bug.
 
You may report it to us on https://github.com/metalbear-co/mirrord/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml
 
connection closed
```

This is one of the issues we ran into right after chaning the settings as suggested; but it doesn't occur every time.

Are these

  - https://mirrord.dev/docs/reference/configuration/#internal_proxy-log_level
  - https://mirrord.dev/docs/reference/configuration/#internal_proxy-log_destination

the correct log settings?

```
    "internal_proxy": {
      "log_destination": "/tmp/internal_proxy.log",
      "log_level": "mirrord=trace"
    }
```

**Comment by aviramha** [comment]
yes, if you could attach `/tmp/internal_proxy.log` after making sure it doesn't include any sensitive information that can be helpful.
When those issues occur? When restarting debugging? I'd advise to not use that VS Code feature with mirrord as our integration with VSCode makes it buggy

**Comment by eyalb181** [comment]
Hey @danielwinkler , is this still happening to you?

**Comment by danielwinkler** [comment]
Hi @eyalb181 ,

Thanks for checking back with me.
The problem was mostly occurring to a co-worker, but now that we changed the configuration everything is working like a charm.

Thanks for the great product and support!
