### ISSUE TITLE
gRPC traffic is not mirrored when using the Linkerd service mesh

### ISSUE THREAD

**Issue by bourquep** [metalbear-co/mirrord#2452]
### Bug Description

When debugging a mirrored C# (.Net 8) micro service in Rider, breakpoints for incoming gRPC requests are not hit.

My service listens for HTTP requests on port 8080 and for gRPC requests on port 5000. I see that HTTP handlers are mirrored properly (well, at least the `/healthz` endpoint which is called periodically by the k8s probe). But the gRPC requests are not. Those gRPC requests actually come into the ingress (Contour/Envoy) as grpc-web requests, which are translated to gRPC by Envoy. Then, Envoy sends a meshed request to my service on port 5000. 

Removing the Linkerd proxy from my mirrored pod fixes the issue (my breakpoints are hit)

### Steps to Reproduce

1. Have a Contour ingress, injected with the Linkerd proxy
2. Have a gRPC service in a pod that is also injected by the Linkerd proxy
3. Use mirrord to mirror the service's traffic
4. Make a grpc-web call to the Contour ingress
5. Observe that the mirrored process doesn't receive the request
6. Remove the Linkerd proxy from the gRPC service pod
7. Make a grpc-web call to the Contour ingress
8. Observe that the mirrored process _does_ receive the request

### Your operating system and version

macOS 14.4.1 (23E224)

### Local process

A C# (.Net 8) process

**Comment by aviramha** [comment]
Probably related to #2537

**Comment by bourquep** [comment]
> Probably related to #2537

@aviramha I'm not sure it's related, as in my case my service listens on the same interface for port 5000 and 8080

**Comment by aviramha** [comment]
I am pretty sure it is, since in mesh situation we do some kind of special logic, which isn't detected in your case (since it's not classic mesh).
