### ISSUE TITLE
question about  logs/errors path

### ISSUE THREAD

**Issue by zjtv** [metalbear-co/mirrord#2467]
I am debugging a `go` program with vscode, `mirrord` did not start successfully, the vscode output the following notification: 
![2024-05-28_18-05](https://github.com/metalbear-co/mirrord/assets/165639285/df70d5db-5b4c-4c9d-9e27-1e112dcf8fa9)

But I don't know where to find this log. I tried the following configuration, but still got nothing.

```
    "internal_proxy": {
        "log_destination": "/tmp/mirrord/internal_proxy.log",
        "log_level": "mirrord=trace"
    }
```

Here is my env:
+ go: go1.22.0 linux/amd64
+ os: Ubuntu 22.04.4 LTS
+ k8s: v1.27.5

the mirrord's configuration:

```json
{
    "feature": {
        "network": {
            "incoming": {
                "mode": "steal"
              }
        },
        "fs": "read",
        "env": true
    },

    "use_proxy": false,
    "kubeconfig": "~/.kube/config",
    "target": {
        "path": {
            "pod": "xxx-648c597b57-vcgnm",
            "container": "xxx-container"
        },
       "namespace": "xxx-system"
      },
    "internal_proxy": {
        "idle_timeout": 60
    }
}

```

Is my configuration incorrect or did I not find the correct logs/errors directory or for some other reason,Please help me find it. thx.

**Comment by aviramha** [comment]
Thanks for reporting this. This usually means the mirrord agent wasn't ready/got into issues.
Can you run `kubectl get pods | grep mirrord` AND `kubectl get jobs | grep mirrord` while starting a session?
Also, it'd help if you'd do `mirrord exec -f mirrord.json -- sh` (mirrord.json being the file you attached) and see if that works

**Comment by zjtv** [comment]
i fix it, thx.
If you are a Chinese user and encounter similar problems, you can try to solve this problem by modifying the default image address.
BTW @aviramha
> We provide sane defaults for this option, so you don’t have to set up anything here.

This prompt may not be suitable for Chinese users

**Comment by aviramha** [comment]
You mean you used another source for the agent image?

**Comment by zjtv** [comment]
> You mean you used another source for the agent image?


 I mean is  I used a mirror image
