### ISSUE TITLE
thread 'DNS worker' panicked

### ISSUE THREAD

**Issue by xavidop** [metalbear-co/mirrord#2468]
### Bug Description

We are evaluating Mirrord Enterprise and we are facing this issue:
```
agent ready - version 3.102.0
2024-05-28T10:52:51.105553Z  WARN ThreadId(07) mirrord_agent::outgoing::udp: interceptor_task -> no messages left
2024-05-28T10:53:00.032631Z  WARN ThreadId(04) mirrord_agent::steal::ip_tables::flush_connections: `conntrack` output is Output {
    status: ExitStatus(
        unix_wait_status(
            256,
        ),
    ),
    stdout: "",
    stderr: "conntrack v1.4.7 (conntrack-tools): 0 flow entries have been updated.\n",
}
2024-05-28T10:54:09.997371Z ERROR ThreadId(14) mirrord_agent::util: Failed setting pid 2853783 namespace "net" with FailedNamespaceOpen(
    Os {
        code: 2,
thread 'DNS worker' panicked at mirrord/agent/src/util.rs:187:42:
Failed setting namespace!: FailedNamespaceEnter(FailedNamespaceOpen(Os { code: 2, kind: NotFound, message: "No such file or directory" }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        kind: NotFound,
        message: "No such file or directory",
    },
)
```

### Steps to Reproduce

The command we are running is the following one:
```
mirrord exec --config-file "./.mirrord/mirrord.json"  --target "deployment/general-service/container/app" --target-namespace "dev-xavi"  --agent-namespace "dev-xavi"  yarn start:meshed
```

The mirord config file is:
```json
{
  "feature": {
    "env": true,
    "fs": "read",
    "network": {
      "dns": true,
      "incoming": {
        "mode":"steal",
        "port_mapping": [[8080, 8006]],
        "listen_ports": [[8080, 8006]]
      }
    }
  }
}

```

### Your operating system and version

MacOS 14.5

### Local process

yarn start:meshed

### Local process version

3.102.0

### Additional Info

This happens only when a request comes in from the public URL

**Comment by aviramha** [comment]
Thanks for reporting this - Are you using the operator?
I suspect that the remote pod you're targeting had a restart, which leads to mirrord failing to access it's Linux namespace.
Can you verify if the container you target had a restart? Sometimes this happens due to health checks failing (timeout) so we recommend using a HTTP filter to avoid stealing the health checks.

**Comment by xavidop** [comment]
hi,
that is correct, we are not using the operator for now and the pod restarts. it does not usually restart when mirrored it is not being executed. what should I do?
thank you in advance

**Comment by aviramha** [comment]
thanks for the clarification - this means you're using mirrord OSS and not enterprise :)

Can you check what's the reason for the restart?

**Comment by aviramha** [comment]
I mean the reason for the restart of the target pod - your service.
P.S if you'd like we can do a screenshare session to debug it.

**Comment by xavidop** [comment]
after the mirrord connection, I am seeing this:
`│ app {"level":40,"time":1716896956775,"msg":"[app] [http] SIGTERM received stopping server..."}                                                                                                                                                  │`

**Comment by aviramha** [comment]
I would like you to describe the app's pod, and see if there's any kubernetes event saying restart / health check failed etc

**Comment by xavidop** [comment]
yeah I see this:
<img width="1462" alt="image" src="https://github.com/metalbear-co/mirrord/assets/4416096/77cbd05b-1de4-4392-afe2-1cb08a23cd65">

What I did not understand is why the other service works perfectly and not this one. Both have the same checks

**Comment by aviramha** [comment]
You can probably run the application with a debugger - put a breakpoint into health and see where it hangs

**Comment by aviramha** [comment]
Would you like to debug it over a call?
meet.google.com/nrq-sstk-qtb

**Comment by aviramha** [comment]
Issue was health checks being stolen and not answered in a timely manner.
