### ISSUE TITLE
Can't load mirrord layer to run 'go run' on Mac M2 Pro 

### ISSUE THREAD

**Issue by muralikrishnagk** [metalbear-co/mirrord#2483]
### Bug Description

Tried to use mirrord on Mac m2 Pro on a sample. But got this error when i tried bringing up mirrord on CLI
Can't load mirrord layer to run 'go run' on Mac M2 Pro 

`dyld[96526]: terminating because inserted dylib '/tmp/10262963994388674232-libmirrord_layer.dylib' could not be loaded: tried: '/tmp/10262963994388674232-libmirrord_layer.dylib' (code signing blocked mmap() of '/private/tmp/10262963994388674232-libmirrord_layer.dylib'), '/System/Volumes/Preboot/Cryptexes/OS/tmp/10262963994388674232-libmirrord_layer.dylib' (no such file), '/tmp/10262963994388674232-libmirrord_layer.dylib' (code signing blocked mmap() of '/private/tmp/10262963994388674232-libmirrord_layer.dylib'), '/private/tmp/10262963994388674232-libmirrord_layer.dylib' (code signing blocked mmap() of '/private/tmp/10262963994388674232-libmirrord_layer.dylib'), '/System/Volumes/Preboot/Cryptexes/OS/private/tmp/10262963994388674232-libmirrord_layer.dylib' (no such file), '/private/tmp/10262963994388674232-libmirrord_layer.dylib' (code signing blocked mmap() of '/private/tmp/10262963994388674232-libmirrord_layer.dylib')
dyld[96526]: tried: '/tmp/10262963994388674232-libmirrord_layer.dylib' (code signing blocked mmap() of '/private/tmp/10262963994388674232-libmirrord_layer.dylib'), '/System/Volumes/Preboot/Cryptexes/OS/tmp/10262963994388674232-libmirrord_layer.dylib' (no such file), '/tmp/10262963994388674232-libmirrord_layer.dylib' (code signing blocked mmap() of '/private/tmp/10262963994388674232-libmirrord_layer.dylib'), '/private/tmp/10262963994388674232-libmirrord_layer.dylib' (code signing blocked mmap() of '/private/tmp/10262963994388674232-libmirrord_layer.dylib'), '/System/Volumes/Preboot/Cryptexes/OS/private/tmp/10262963994388674232-libmirrord_layer.dylib' (no such file), '/private/tmp/10262963994388674232-libmirrord_layer.dylib' (code signing blocked mmap() of '/private/tmp/10262963994388674232-libmirrord_layer.dylib')`

### Steps to Reproduce

Tried the GIST https://gist.github.com/vfarcic/896c84c9c9c0067811f078eaee9d18b1

### Your operating system and version

Mac M2 Pro

### Local process

go run

### Additional Info

NA

**Comment by muralikrishnagk** [comment]
Any update on the this exclusion from Vmware

**Comment by aviramha** [comment]
Hey, I tried reaching them but didn't get any feedback - if you want we can have a session with your IT and see if we can setup an exclusion from their side.

**Comment by muralikrishnagk** [comment]
After adding the exclusion '/tmp/10262963994388674232-libmirrord_layer.dylib' to the Carbon Black Cloud, it went ahead and was able to connect with mirrord. Need to explore further more.!!

**Comment by aviramha** [comment]
Thanks for reporting back. Please note that the path changes from version to version - can you see if you can make an exclusion based on a regex? if not, we'll add a feature to control where mirrord extracts the dylib to.
