### ISSUE TITLE
readlink stabilization

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2518]
In few months time, when we stabilize readlink, make sure to warn at first at unused config `readlink` under `experimental` and don't fail, for another period of time.

**Comment by eyalb181** [comment]
On September 20th, check if we can stabilize this according to the versions currently in use.

**Comment by aviramha** [comment]
tbh we can use the protocol detection to use it, and we already have `READDIR_BATCH_VERSION` which includes it for sure

**Comment by aviramha** [comment]
c

**Comment by aviramha** [comment]
gggg

**Comment by aviramha** [comment]
b
