### ISSUE TITLE
Retest mirroring under high load

### ISSUE THREAD

**Issue by Razz4780** [metalbear-co/mirrord#2571]
Since https://github.com/metalbear-co/mirrord/pull/2561 is merged, we'd like to run the same tests that discovered the problem and see if there is an improvement.

**Comment by DmitryDodzin** [comment]
After another test with mirrord `3.114.1` and our mirrord-pytest as target with running under `incoming = "mirror"` and executing `go-e2e` as server, the results look better but still inconclusive

all tests ran for 30s

baseline:
- pytest failed after ~26592 requests when running at roughly 1450rps

with-mirrord:
- mirrord failed after ~15645 requests when running at roughly 900rps
- mirrord failed after ~15942 requests when running at roughly 700rps
- mirrord works fine with ~20446 requests when running at ~500rps

**Comment by aviramha** [comment]
imo quite good results - we should consider optimizing/improving once user really is affected.

**Comment by DmitryDodzin** [comment]
Also one more data point

mirrord with `--steal` and `go-e2e` and unrestricted all works fine with 109011 requests at roughly 3627rps

**Comment by aviramha** [comment]
![Awesome 3](https://github.com/user-attachments/assets/b5993dc5-5305-45c1-8e66-38c7894114f6)

**Comment by Razz4780** [comment]
Can we close then?

**Comment by eyalb181** [comment]
Yes, closing, thanks!
