### ISSUE TITLE
Extend dns config with filter

### ISSUE THREAD

**Issue by Razz4780** [metalbear-co/mirrord#2581]
`feature.network.dns` config has to be extended with an optional local/remote filter, following `feature.network.outgoing.filter` pattern. The motivation for this is to catch cases where resolving name/address remotely is pointless (and prone to failures), because the resolved will be used for local outgoing connection.

**Comment by aviramha** [comment]
In the referenced [example](https://github.com/metalbear-co/mirrord/issues/2579#issuecomment-2218467745) you've put ports but not sure how that applies to DNS

**Comment by aghajani** [comment]
I guess the goal here is to skip DNS resolution for host section of outgoing requests matching the filter. Maybe we can expand the `outgoing` filter instead e.g.
```json
{
    "agent":
    {
        "ephemeral": true
    },
    "feature":
    {
        "network":
        {
            "incoming":
            {
                "ignore_localhost": true
            },
            "outgoing":
            {
                "ignore_localhost": true,
                "filter":
                {
                    "local":
                    [
                        { "pattern": ":9000", "dns": false },
                        { "pattern": ":9003", "dns": false },
                    ]
                }
            }
        }
    }
}
```

**Comment by Razz4780** [comment]
> In the referenced [example](https://github.com/metalbear-co/mirrord/issues/2579#issuecomment-2218467745) you've put ports but not sure how that applies to DNS

We've observed calls like `getaddrinfo("192.168.65.254", "9000", ...)` and the arguments for name resolution are a `(name/address, port)` pair. I thought the simplest way to do filtering is just copying what we have in the outgoing filter.

> Maybe we can expand the outgoing filter instead

I'm not sure if we want to bind these two settings. If we keep them separate, we'll get an additional free feature from this change - general dns filter. Plus, outgoing filters allow for specifying protocol (udp/tcp), which is not known at the point of name resolution. @aviramha wdyt?

**Comment by aghajani** [comment]
Yes, the separate `dns` has the benefit of a broader use case, but can be a bit confusing at the same time. But I think with good documentation this can be clarified. So in `dns` filter, we want to support this pattern: `[name|address|subnet/mask]:[port]` and for cases that the port is specified, the filter only applies on outgoing requests targeting the specified port. Is it correct?

**Comment by aviramha** [comment]
I think the split is better having dns/outgoing their own.

**Comment by Razz4780** [comment]
> for cases that the port is specified, the filter only applies on outgoing requests targeting the specified port. Is it correct?

The filter will be checked before any outgoing requests. The DNS query specifies both name/address and the port. So, for example, filter `1.1.1.1` would match queries for both `1.1.1.1:80` and `1.1.1.1:22`, while filter `1.1.1.1:80` would match only query `1.1.1.1:80`. If the local/remote filter does match, outgoing requests/connections to the resolved address will be done locally/remotely

**Comment by aviramha** [comment]
@aghajani Thank you for helping us design and add this improvement!

**Comment by aghajani** [comment]
> > for cases that the port is specified, the filter only applies on outgoing requests targeting the specified port. Is it correct?
> 
> 
> 
> The filter will be checked before any outgoing requests. The DNS query specifies both name/address and the port. So, for example, filter `1.1.1.1` would match queries for both `1.1.1.1:80` and `1.1.1.1:22`, while filter `1.1.1.1:80` would match only query `1.1.1.1:80`. If the local/remote filter does match, outgoing requests/connections to the resolved address will be done locally/remotely

@Razz4780 but we still going to support :9000 filter for dns as well, right? Meaning dns resolution step will be local for any request targeting that port no matter what the IP or host be. This is important in our case since we don't know the IP before the container starts, of course we can do some tricks here too but a flexible pattern will help a lot.  @aviramha I am happy to help, you have good community here.

**Comment by Razz4780** [comment]
@aghajani Ah yes, of course ^^
