### ISSUE TITLE
Support Bash pipe/redirect operators

### ISSUE THREAD

**Issue by DmitryDodzin** [metalbear-co/mirrord#259]
There is a problem with bash pipe `|` or redirect `>` operators that perform ops between stdouts and stdins of forked process, needs further investigation on the issue.
Some operations fail some just halt the further execution of the process managed by mirrord

possibly related: #258

**Comment by infiniteregrets** [comment]
Just did some digging:
conceptually I believe, pipe operators call pipe() then dup on the pipe fd with the stdout of one end and otherway around on the receiving end of the pipe. However strace does not show any calls to dup, dup2, dup3, fcntl..

https://gist.github.com/infiniteregrets/1838c511792353116d071ee1bfd17c0a

**Comment by aviramha** [comment]
This seems to work now.
