### ISSUE TITLE
Buffer directory iteration

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2611]
When user iterates a directory, we fetch each entry on its own, causing it to be very slow when reading big directory.
Similar in nature to https://github.com/metalbear-co/mirrord/issues/2069

**Comment by Razz4780** [comment]
Note: this will probably require extending `mirrord-protocol`, so operator will have to updated as well

**Comment by Razz4780** [comment]
Closed with #2637
Operator counterpart [here](https://github.com/metalbear-co/operator/issues/618)
