### ISSUE TITLE
mirrord doesn't mirror/steal traffic when binding localhost

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2621]
macOS, Go, GoLand
```go
func (s *Server) serveGRPC(context.Context, context.CancelFunc) error {
    l, err := net.Listen("tcp", s.grpcAddress)
    if err != nil {
        return err
    }
    defer l.Close()

    log.Info("Starting grpc server", log.Fields{"address": s.grpcAddress})
    err = s.grpcServer.Serve(l)
    if s.inShutdown && errors.Cause(err) == grpc.ErrServerStopped { //nolint:errorlint // legacy
        err = nil
    }
    return errors.Wrap(err, "grpc server")
}
```
user's code - when `s.grpcAddress` is `0.0.0.0:50051` mirrord works, when it's `localhost:50051` it doesn't.
Discord:
https://discord.com/channels/933706914808889356/1267880088892997663

**Comment by Razz4780** [comment]
Shouldn't be macOS specific

**Comment by meowjesty** [comment]
I've tried triggering this on linux, but had no success thus far.

I'm using the grpc [`helloworld`](https://github.com/grpc/grpc-go/tree/master/examples/helloworld) example, and it's always working for both `mirror` and `steal`. Tested it on cli and intellij-idea, after changing the example server to listen on `localhost`:

```go
lis, err := net.Listen("tcp", "localhost:80")
```

And the client to use the pod service ip:

```go
addr = flag.String("addr", "192.168.49.2:30031", "the address to connect to")
```

Whenever I run the client greeter, it reaches the server I'm debugging.

I'm using a `mirrord.json` similar to the user.

```json
{
    "target": "pod/sample-python-deployment-796d8bcd4f-zv62c",
    "feature": {
        "network": {
            "incoming": {
                "mode": "steal",
                "ignore_ports": [2112]
            },
            "outgoing": true
        }
    }
}
```

Should I try it in GoLand? Am I missing something?

**Comment by DmitryDodzin** [comment]
I tested same example as @meowjesty with localhost explicitly specified in `net.Listen` and in both cases stealing worked perfectly I did have problems with mirroring though the problem with mirroring persisted regardless of binding to `0.0.0.0` or `localhost`
