### ISSUE TITLE
Ability to use remote trusted CA certs

### ISSUE THREAD

**Issue by feynmanliang** [metalbear-co/mirrord#2629]
We are using `mirrord` in an application involving internal PKI where we need to add custom CA certs to the operating system certificate store.

I've added the CA cert (on OpenSUSE, add cert to `/pki/trust/anchors` and run `update-ca-certificates`) and verified that `curl` on the same pod successfully validates HTTPS endpoints signed by this CA.

However, when I use `mirrord` to access this pod and perform the same command I am getting invalid CA issues. Upon further inspection, it looks like `mirrord` is using my dev machine's CA certificates (undesirable) rather than the remote pod's (desirable).

I tried setting `"fs": "read"` but got the same results; the `/etc/ssl` directory visible through mirrord seems to be my dev machine rather than the remote pod.

It would be great if there was a flag or feature to use the same CA trust stores as the remote. At the moment, I have to manually download the desired CAs from the pod and trust them a second time on my dev machine.

**Comment by aviramha** [comment]
What operating system are you using?

**Comment by feynmanliang** [comment]
OS data
```
feynman@nesterov:~> uname -r
6.9.9-1-default
feynman@nesterov:~> cat /etc/os-release 
NAME="openSUSE MicroOS"
# VERSION="20240726"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed microos sl-micro"
VERSION_ID="20240726"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20240726"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:MicroOS"
LOGO="distributor-logo-MicroOS"
```

**Comment by aviramha** [comment]
Ah, should've suggested to have this under fs:
```
"fs": {"mode": "read_only", "read_only": ["/etc/ssl"]}
```
By default we use local `/etc`.

**Comment by feynmanliang** [comment]
Incredible! That's all I needed - removed the CA from my local cert store verified that custom CA certs validate correctly iff I have the `read_only` setting.

I'm seeing this functionality in your docs https://mirrord.dev/docs/reference/configuration/#feature-fs so I should have read that... thanks for helping me out!
