### ISSUE TITLE
schema issue on "incoming" (and probably others)

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2662]
<img width="570" alt="image" src="https://github.com/user-attachments/assets/b2232ec4-66e2-4670-85a2-c7d1b97c00f9">

I assume it's part of the refactor that @DmitryDodzin did

**Comment by DmitryDodzin** [comment]
I need to take a closer look but I think it should be contained to incoming because of how schemars parses serde macro and I added manual parsing logic to it
