### ISSUE TITLE
Support specifying both header and path filter for stealing HTTP

### ISSUE THREAD

**Issue by Razz4780** [metalbear-co/mirrord#2683]
IMO we should probably just allow for any set/combination of filters.
Remember to verify config after fetching `mirrord-protocol` version used by agent/operator

**Comment by aviramha** [comment]
I agree technically, but from UX side we wouldn't want too complex configuration

**Comment by Razz4780** [comment]
Currently the config looks like:
```json
{
    "http_filter": {
        "header_filter": "user: me"
    }
}
```
or
```json
{
    "http_filter": {
          "path_filter": "/api/v1/my-route.*"
    }
}
```
I'd allow for third variant like this:
```json
{
    "http_filter": [
        {"header": "user: me"},
        {"path": "/api/v1/my-route.*"},
    ]
}
```

**Comment by aviramha** [comment]
How about allowing both to be set and take it as an AND?
```json
{
    "http_filter": {
          "path_filter": "/api/v1/my-route.*",
		          "header_filter": "user: me"
    }
}

**Comment by Razz4780** [comment]
Sounds ok, but it would be the same amount of work on our end with less flexibility :c

**Comment by gememma** [comment]
> Another, more extensible option:
> 
> ```json
> {
>     "http_filter": {
>         "all": [
>             {"header": "user: me"},
>             {"path": "/api/v1/my-route.*"}
>         ]
>     }
> }
> ```
> 
> (allow for `"all"` | `"any"`)

I like how explicit this is tbh

**Comment by aviramha** [comment]
I'm okay with it, as long as the basic config options remain (so users can just specify under http_filter one condition..)
