### ISSUE TITLE
"Operator not found" message shown even if operator is set to false

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#2695]

**Comment by Razz4780** [comment]
Which binary version was used? This is what I see when running main
![image](https://github.com/user-attachments/assets/70dd6dc9-6cd0-44b1-8247-0add53d4cb1e)

**Comment by aviramha** [comment]
It was seen on the IDE, intellij specifically

**Comment by Razz4780** [comment]
> It was seen on the IDE, intellij specifically

Don't see any message there as well :eyes:

**Comment by aviramha** [comment]
It's part of the progress bar flow so I think it's Java et al

**Comment by Razz4780** [comment]
Yeah, I used plain Java project. Grepped mirrord-intellij for "operator not found" to no results, so this message certainly comes from the binary. Maybe the user pinned binary version?

**Comment by aviramha** [comment]
ah that's probably the case
