### ISSUE TITLE
User runs yarn/npm with mirrord, their app does not start

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#2716]
### Bug Description

On CLI - new shell opens, on vscode - Nothing happens.

### Steps to Reproduce

Did not reproduce for me, but here is what the user reported:

1. `git clone https://github.com/hmcts/civil-citizen-ui && cd civil-citizen-ui`
2. `yarn install && yarn webpack`
3. `mirrord exec -t .. -- yarn start`
4. A new interactive shell opens, the yarn app does not run.

For vscode:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/src/main/server.ts"
        },{
            "command": "npm start",
            "name": "Run npm start",
            "request": "launch",
            "type": "node-terminal"
        }
    ]
}
```

And user only sees this output:

```
echo 'yarn run start' | DYLD_INSERT_LIBRARIES=/tmp/10779832966104285419-libmirrord_layer.dylib /var/folders/82/bndhr3411j90b382k_dh7kjw0000gn/T/mirrord-bin-ghu3278mz/bin/zsh -is
user@User-Mac civil-citizen-ui % echo 'yarn run start' | DYLD_INSERT_LIBRARIES=/tmp/10779832966104285419-libmirrord_layer.dylib /var/folders/82/bndhr3411j90b382k_dh7kjw0000
gn/T/mirrord-bin-ghu3278mz/bin/zsh -is
```

This output is valid, I get it too, but for me the app then starts, so I think maybe something in the session start gets stuck or takes very long and so the user is stuck on that phase.

### Your operating system and version

macOs

### Local process

node

### Local process version

v21.7.1

### Additional Info

https://canary.discord.com/channels/933706914808889356/1280178791469023314

**Comment by DmitryDodzin** [comment]
I couldn't manage to reproduce the error, `mirrord exec .. yarn -- start` works as expected, though there are some problems I did have to change because of my local setup, I don't have a tls redis and the string value from env variable propagated to comparison and "false" is truthy
```diff
-- const protocol = config.get('services.draftStore.redis.tls') ? 'rediss://' : 'redis://';
++ const protocol = config.get('services.draftStore.redis.tls') === 'true' ? 'rediss://' : 'redis://';
```

**Comment by DmitryDodzin** [comment]
I have a feeling something in `~/.zshrc` or similar is involved here because we are running zsh with mirrord so it's probably related to that and not the underlying nodejs or npm

**Comment by gmikerlemos** [comment]
I also use zsh

**Comment by aviramha** [comment]
User can't reproduce, everything works now.
