### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by xavidop** [metalbear-co/mirrord#2730]
### Bug Description

From time to time, our users are seeing this error.

![image](https://github.com/user-attachments/assets/5df7d2c3-b5fb-4e31-ab14-a70f08f43d0e)

### Steps to Reproduce

run mirrord to connect to a service

### Relevant Logs

```shell
io failed: Resource temporarily unavailable (os error 35)
Assertion failed: (!"unknown EAI_* error code"), function uv__getaddrinfo_translate_error, file getaddrinfo.c, line 90.
```
```


### Your operating system and version

Mac OS

### Local process

running yarn process

### Local process version

_No response_

### Additional Info

_No response_

**Comment by xavidop** [comment]
@trs can add more context here if requested

**Comment by aviramha** [comment]
Is the remote pod restarted in this case?

**Comment by xavidop** [comment]
@trs could you please help us debugging this issue?

**Comment by trs** [comment]
I don't believe it is

**Comment by aviramha** [comment]
@trs Does it still happen? Is there something you do that helps you reproduce it?

**Comment by aviramha** [comment]
Hi @trs - we need more information to investigate this
