### ISSUE TITLE
Enable internal proxy log by default to enable easier troubleshooting

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2750]
We have quite few issues that raise from layer saying internal proxy died, but users can't know why it happened.
I suggest the following:

1. Make internal proxy log by default to tempdir with `mirrord_datetime_rand4chars.log`
2. Prompt user to look into it and upload it to the issue they open when they get an internal proxy error.

https://github.com/metalbear-co/mirrord/issues/2742

**Comment by meowjesty** [comment]
Now that 1 has been done, I think 2 should be part of the error report, but do we also to add it in the "new issue" template thingy?
