### ISSUE TITLE
Question: Is mirrord able to run on Cilium without kube-proxy implementation?

### ISSUE THREAD

**Issue by alternaivan** [metalbear-co/mirrord#2777]
We are planning on running mirrord on the Kubernetes that uses [Cilium without kube-proxy](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/).

Is it possible to run the mirrord in that setup, and are there any limitations for it?

Thanks,
Marjan

**Comment by aviramha** [comment]
hi @alternaivan - we don't know of any limitation or any reason it wouldn't work. mirrord works on a container level and doesn't touch or play with the kubeproxy rules.
I believe that you can try it out pretty fast, and happy to assist if something doesn't work.

**Comment by alternaivan** [comment]
Hi @aviramha,

Thanks for the fast response! I'll try to run it on the environment, and see the results.

Thanks!
Marjan
