### ISSUE TITLE
crash on system's Python3 on macOS

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2779]
Happens from VScode

Python 3.12.5
happened to @Anita-ihuman 
[python3-2024-09-25-143237.txt](https://github.com/user-attachments/files/17135730/python3-2024-09-25-143237.txt)

**Comment by Anita-ihuman** [comment]
I am not sure i have access to the launch.json fil in question anymore. 

So what happened wa, immediately i hit debug, it would show mirrord is trying to run and then end the session with this output in the terminal.  
<img width="1046" alt="Screenshot 2024-09-25 at 5 25 08 PM" src="https://github.com/user-attachments/assets/404e9321-b9bd-4761-ae14-2e1046d4bd70">
<img width="1056" alt="Screenshot 2024-09-25 at 5 33 18 PM" src="https://github.com/user-attachments/assets/de6a5841-fef8-4924-aa86-fb506286b34f">

**Comment by t4lz** [comment]
Thanks for the info. It looks like vscode was trying to debug `mirrord.json` with `debugpy`. I guess you could make this happen if you set a current-file debugpy run, and then press run while `mirrord.json` is open in the editor, or something like that.
This run wouldn't work or make sense with or without mirrord, but I don't know if it would result in a crash report. Do you know if the crash also happened when running a python file?

**Comment by t4lz** [comment]
Was able to make vscode try to run the json file with debugpy by:
1. Open a python file in the editor.
2. Open the menu next to the run button.
  ![image](https://github.com/user-attachments/assets/9d197d1d-87e1-4643-b507-09d371bcbf43)
3. Click `Python Debugger: Debug using launch.json`
4. Choose `Python Debugger: Current File`
  ![image](https://github.com/user-attachments/assets/a93f3883-e5c7-4625-89b4-034fca9eeec4)
5. That runs the python file and creates the following `launch.json` file:
    ```json
    {
        // Use IntelliSense to learn about possible attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Python Debugger: Current File",
                "type": "debugpy",
                "request": "launch",
                "program": "${file}",
                "console": "integratedTerminal"
            }
        ]
    }
6. Stop that run, open `mirrord.json` in the editor, and press `F5`.
7. Results in "debugging" the `mirrord.json` as in the screenshots above:
    ```
    cd /Users/t4lz/projects/test_projects/vanilla_py ; /usr/bin/env /usr/local/bin/python3 /Users/t4lz/.vscode/extensions/ms-python.debu
    gpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher 57789 -- /Users/tal/Documents/projects/test_projects/vanilla_py/.mirrord/mir
    rord.json
    ```

However, I did not get the `posix_spawn` error like in the screenshot, nor was a crash report created, so I'm trying to reproduce that now.

**Comment by t4lz** [comment]
@anitai hey, so far I can't reproduce this issue. Could you please check if you can reproduce it on your system, so that I can see the issue happen and gather more information so that I can understand what is happening and reproduce it on my system? If it helps I could jump on a call with you.
