### ISSUE TITLE
running shell scripts without shebang causes SIP detection to fail

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2784]
Latest macOS update, Sequoia (15.0) broke running shell scripts using mirrord. Specifically, it looks like it broke the SIP detection somehow.

To reproduce create a script called fun.sh:
```sh
#/bin/sh
curl http://ip-info
```

then
 on 
`MIRRORD_PROGRESS_MODE=off RUST_LOG=mirrord=trace mirrord exec -t deployment/ip-visit-counter -- ./fun.sh`

you get 
```
2024-09-27T15:23:39.388168Z TRACE start: mirrord_sip::main: No SIP detected on "./sha.sh"
* Could not resolve host: ip-info
* Closing connection
curl: (6) Could not resolve host: ip-info
```

**Comment by gememma** [comment]
it looks like currently SIP detection for scripts like `fun.sh` relies on a shebang being present - a step should be added to the SIP check to determine if the default interpreter is SIP protected when the binary to be run is a script *without* a shebang
