### ISSUE TITLE
Not able to load environment variables or connect to services via gradle+intellij

### ISSUE THREAD

**Issue by scottillogical** [metalbear-co/mirrord#2785]
### Bug Description

I recently got a new mac, setting it up I am not able to get intellij mirrord to load the environment variables correctly. This worked on my previous mac fine

Via CLI it works fine
```
mirrord exec -a scott1 --target=deployment/<APP> -- bash
$ env | grep MIRRORD_AGENT_NAMESPACE=scott1
MIRRORD_AGENT_NAMESPACE=scott1
```

But when I start up the java app in intellij, it does not load the environment variables from the target pod
<img width="1504" alt="Screenshot 2024-09-27 at 12 31 05 PM" src="https://github.com/user-attachments/assets/bc0ebf1f-2eba-4461-a9c4-5e4b55c39875">

Since in the past this has been due to SIP issue https://mirrord.dev/docs/faq/common-issues/ I copied my JDK into ~/java, but this did not ameliorate the issue

I also tried running `sudo codesign --remove-signature ./<your-binary>` but after that I could not boot the jdk without it exiting immediately afterwards. I tried other jdks no dice thus far

### Steps to Reproduce

1. Run java app in intellij
2. Observe no environment variables

### Your operating system and version

osx sonoma 14.7

### Local process

$| file $JAVA_HOME/bin/java /Users/sschulthess/.jenv/versions/corretto64-1.8.0.422/bin/java: Mach-O 64-bit executable arm64

### Local process version

$| java -version openjdk version "1.8.0_422" OpenJDK Runtime Environment Corretto-8.422.05.1 (build 1.8.0_422-b05) OpenJDK 64-Bit Server VM Corretto-8.422.05.1 (build 25.422-b05, mixed mode)

### Additional Info
config file

```
{
    "target": {
        "path": {
            "deployment": "APP"
        },
        "namespace": "scott1"
    },
    "agent": {
        "namespace": "scott1"
    },
    "feature": {
        "network": {
            "incoming": "steal",
            "outgoing": {
                "filter": {
                    "local": [
                        "localhost:3000"
                    ]
                }
            }
        },
        "fs": "read"
    },
    "kube_context": "zc-carsharing-dev"
}
```

**Comment by aviramha** [comment]
Hi,
Environment variables can't be affected by SIP so it's probably not that.
Can you enable internal proxy logs by adding this to your mirrord.json:
```json
{"internal_proxy": {"log_destination": "/tmp/internal_proxy.log", "log_level": "mirrord=trace"}}
```
then after running attaching the logs (after redacting sensitive information?

**Comment by aviramha** [comment]
User was able to reproduce it in a vanilla project launching "gradle run" - so perhaps the problem is with the gradle/intellij integration (not using IntelliJ's compilation/execution)

**Comment by aviramha** [comment]
Hey
setting fs to read means that most files would be from the remote, but not that local files wouldn't be available (it depends on our default filters)
We're planning to look into it soon.

**Comment by scottillogical** [comment]
Okay thanks for the update.  I did confirm that its not just an environment variable issue, as when the environment variables are set manually, the app still can't connect to rabbitmq over mirrord

**Comment by scottillogical** [comment]
Tried to get this working on a new mac, no dice.  The problem is not just that it doesnt get env vars, even if it gets the env vars it cannot connect to rmq running in the namespace. But only when running via intellij gradle

**Comment by scottillogical** [comment]
https://gist.github.com/scottillogical/ebcebf60d53e088222c6e38f4188a896 logs

**Comment by scottillogical** [comment]
Hey folks was playing around with this this morning.  I was able to reproduce the issue on a sample gradle app by changing the run configuration

https://github.com/scottillogical/mirrord-gradle-bug

1. In intellij, select FIle - New  - Project from existing sources
2. Select project directory
3. update the mirrord settings to point at a deployment in your k8s cluster - mine is set to my namespace/app
4. The broken run configuration should be preloaded - run that to observe only "hello world" and about 14 env vars
5. Run the "works" configuration to observe that more env vars come through

The only difference between the two run configurations is the broken one runs `jdk -cp test.main` and the one that works runs `jdk -cp test`.

**Comment by aviramha** [comment]
Ah that's extremely valuable, thank you @scottillogical 
We've prioritized this - hope we'll have progress soon.

**Comment by aviramha** [comment]
I managed to reproduce thanks for the example!

**Comment by t4lz** [comment]
Documenting some early findings:<br>even with the "Works" configuration it only works sometimes for me.

It looks like sometimes the IDE creates a different type of configuration object without me (intentionally/knowingly) doing anything different.

When `configuration` has the dynamic type `GradleRunConfiguration` (which `is ExternalSystemRunConfiguration`), the application does not get the env from the cluster, even though that env is successfully fetched and is set to in the configuration. I don't know at what point it is lost.

<img src="https://uploads.linear.app/7ccbf9ab-1d7d-4415-b8cf-e243210db298/5c400371-0349-474a-93ed-d6c58acbf945/cc2a8172-8441-4fc2-b334-f6d0ac379029?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdjY2JmOWFiLTFkN2QtNDQxNS1iOGNmLWUyNDMyMTBkYjI5OC81YzQwMDM3MS0wMzQ5LTQ3NGEtOTNlZC1kNmM1OGFjYmY5NDUvY2MyYTgxNzItODQ0MS00ZmMyLWIzMzQtZjZkMGFjMzc5MDI5IiwiaWF0IjoxNzI4NjY0MzUzLCJleHAiOjMzMjk5MjI0MzUzfQ.1_np10xsFVB12W76CfAKVAzOrNvG6mChKGhtZeZVttA " alt="image.png" width="813" height="313" />

When `configuration` is an `ApplicationConfiguration` the application does get the env as it should.

<img src="https://uploads.linear.app/7ccbf9ab-1d7d-4415-b8cf-e243210db298/2410584e-2c00-4168-89d3-f0fb184d0864/73e2cffa-1f00-41f6-b310-f524edaea683?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdjY2JmOWFiLTFkN2QtNDQxNS1iOGNmLWUyNDMyMTBkYjI5OC8yNDEwNTg0ZS0yYzAwLTQxNjgtODlkMy1mMGZiMTg0ZDA4NjQvNzNlMmNmZmEtMWYwMC00MWY2LWIzMTAtZjUyNGVkYWVhNjgzIiwiaWF0IjoxNzI4NjY0MzUzLCJleHAiOjMzMjk5MjI0MzUzfQ.u6jCNHVwdXndqLEIA0YDd-jIx1uOjux5zjYpVMNkhZk " alt="Pasted Graphic.png" width="866" height="353" />

debugging the plugin to find out why.

I'm getting the "good" type of configuration in one or two runs after starting the debug IDE, and after that only the "bad" type. I thought the difference has something to do with the env-cleanup in `processTerminated`, but I think if that were the case it would not sometimes work a second time.

**Comment by aviramha** [comment]
Just a guess, but perhaps it's because `isReattachDebugProcess = true`? can you set it to false manually and see if it helps?

**Comment by aviramha** [comment]
Tried it, nope

**Comment by aviramha** [comment]
I would try to check where IntelliJ decides which configuratoin is to be used and see what's the logic there

**Comment by aviramha** [comment]
This seems to be an IntelliJ issue on itself - if you add any environment variable to the run configuration it doesn't get to the debugged/ran process.
Created issue here https://youtrack.jetbrains.com/issue/IDEA-360874/Environment-variables-arent-set-in-Application-run-configuration

**Comment by scottillogical** [comment]
If it is a bug in intellij, reverting to an older version of intellij does not appear to help

1. Launch mirrord pod successfully 
2. App refuses to boot and prints an error indicating that the environment variables are not being loaded from the remote deployment
3. Even if I set the environment variables manually, the addresses do not resolve over mirrord successfully
4. The mirrord pods stick around in my environment even after I shut down the process.  This did not used to be the case

I have tried
1.  Old versions of intellij
2. Old versions of mirrord
3. Different jdks & gradle versions
4. Using the same code 
5. old version of mirrord intellij plugin 

Running mirrord like so does appear to load the env variables fine
$| RUST_LOG=mirrord=trace /Users/sschulthess/Library/Application\ Support/JetBrains/IntelliJIdea2024.2/plugins/mirrord/bin/macos/mirrord ext -f /Users/sschulthess/cheetahs/ultron/.mirrord/mirrord.json

**Comment by aviramha** [comment]
Does adding environment variables regardless of mirrord work? because when I reproduced it I saw that's the case (and that's why mirrord fails to work as well)

**Comment by scottillogical** [comment]
@aviramha okay I think i figured it out.   needed to use a version of gradle that natively supports apple silicion (6.9.1+). thanks for the help!
