### ISSUE TITLE
mirrord config/cli `spec.nodeSelector` support

### ISSUE THREAD

**Issue by drehelis** [metalbear-co/mirrord#2805]
We utilize bunch of node groups and it seems there's no way forcing mirrord-agent to run on specific node type, it is randomly being placed on any of the available nodes which sometimes needs to be avoided.

I find this mostly required when using `mirrord exec`, on the command line and the targetless approach.
It could be nice to support both cli args and config as currently all cli args are being passed ad-hoc, without the need of maintaining another `mirrord.json` file (as we already have one in place for steal flow),
i.e: 
```mirrord) exec --agent-image ... --agent-namespace ... --nodeselector disktype=ssd```

**Comment by aviramha** [comment]
Closed thanks to @dbeilin  #2834
