### ISSUE TITLE
SIP creates non-signed file when agent timeout

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2814]
User tried to run
```mirrord exec -f .. -- ./script.sh```
then got agent timeout, next execution everything failed because it used the patched `sh` binary that for some reason wasn't signed.
Two possible solutions (maybe should do both):
1. when reusing "file cache" - check file is also signed before reusing it
2. find how execution failure can lead to signing not happening?

**Comment by aviramha** [comment]
seems that deleting the file doesn't help, but manually `codesign`'ing again does help. very weird.
user has some AV that blocks running unsigned code

**Comment by t4lz** [comment]
I'm trying to reproduce this issue with no luck.

I can cause an agent timeout by running
```
MIRRORD_AGENT_TEST_ERROR=true mirrord-dev exec -t deployment/py-serv-deployment -- sh
! Warning: field AgentConfig.test_error is marked as unstable. Please note API may change
When targeting multi-pod deployments, mirrord impersonates the first pod in the deployment.
Support for multi-pod impersonation requires the mirrord operator, which is part of mirrord for Teams.
You can get started with mirrord for Teams at this link: https://mirrord.dev/docs/overview/teams/?utm_source=multipodwarn&utm_medium=cli
  x ! Warning: field AgentConfig.test_error is marked as unstable. Please note API may change
    ✓ running on latest (3.125.0)!
    x preparing to launch process
      ✓ layer extracted
      ✓ operator not found
      ✓ agent pod created
      ✓ pod is ready                                                                                                                                                                                                                                                                                                       Error:   × Failed to communicate with the agent: timeout
  help: Please check agent status and logs.
        
        - If you're still stuck:
        
        >> Please open a new bug report at https://github.com/metalbear-co/mirrord/issues/new/choose
        
        >> Or join our Discord https://discord.gg/metalbear and request help in #mirrord-help
        
        >> Or email us at hi@metalbear.co
```

On a cluster without an operator (did the user have an operator installed?).

But no patched `sh` is created (`find $TMPDIR -iwholename "**/bin/sh" 2>/dev/null` does not return results).

Any more information for reproduction, @aviramha?

How should I proceed? Should I continue trying to reproduce? Should I add a signature check for executing already patched binaries and sign them before running if they're not signed?

**Comment by aviramha** [comment]
The user had an operator.
Not sure if we can reproduce it as they had some custom AV..
I think maybe the more complete solution would be to create the patched file in temp file, codesign it then mv it to the "cache". Wdyt?

**Comment by t4lz** [comment]
> I think maybe the more complete solution would be to create the patched file in temp file, codesign it then mv it to the "cache". Wdyt?

Sounds good. Not sure if that's exactly what you meant, but when patching a file we can write the binary to a file with a random path, sign it there, and only move it to the destination once we're done. That way there is no need for extra checks on running an existing patched file, because if it's there it means it's signed (except for files created by older mirrord versions, but they will be deleted on a restart).

**Comment by aviramha** [comment]
That's what I meant 🙂

**Comment by t4lz** [comment]
So apparently we already do that @aviramha 

https://github.com/metalbear-co/mirrord/blob/705998e979b188977673de429d163ead28c9c7c9/mirrord/sip/src/lib.rs#L277-L279

https://github.com/metalbear-co/mirrord/blob/705998e979b188977673de429d163ead28c9c7c9/mirrord/sip/src/lib.rs#L312-L317

**Comment by aviramha** [comment]
Ok let's close this 😢
