### ISSUE TITLE
Publish to krew

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#282]
Krew is plug-in manager for Kubectl. I think it makes sense to publish mirrord there.

**Comment by eyalb181** [comment]
@infiniteregrets please link the response you got and close this as not planned.

**Comment by infiniteregrets** [comment]
Closing this based on -
> FWIW not all tools have to be kubectl plugins. For example, skaffold, tilt or minikube aren't.

The point of kubectl plugins is to make the "kubectl" experience better (not necessarily the "developing applications on Kubernetes experience").

I think this doesn't fall into the plugin category based on my reading of the situation.
/kind gray-area

https://github.com/kubernetes-sigs/krew-index/pull/2559#issuecomment-1232313104
