### ISSUE TITLE
outgoing connection fails on 3.119.1

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2820]
seems like a regression, user updated and seems that outgoing stopped working.
I suspect

```
- Allow using IPv6 sockets with mirrord.
```

Happens on Java BootSpring + macOS

**Comment by Razz4780** [comment]
Found two places were we assume only IPv4:
* [agent dns lookup config](https://github.com/metalbear-co/mirrord/blob/a006e438bbaefeec5db7a69ce377ce21e3129201/mirrord/agent/src/dns.rs#L96)
* [getaddrinfo hook](https://github.com/metalbear-co/mirrord/blob/a006e438bbaefeec5db7a69ce377ce21e3129201/mirrord/layer/src/socket/ops.rs#L922)

The second one is probably not related to this bug, but the first one looks like a probable cause

**Comment by aviramha** [comment]
But we don't support IPv6 in connect anyway, and when we changed it we actually "allowed" ipv6 so I don't think those references are related.

**Comment by Razz4780** [comment]
What are the symptoms of this bug? Any logs/error codes? :eyes:

**Comment by aviramha** [comment]
We just saw the app faiiling to start on some connectivity issue. Unfortunately I couldn't grab logs.
