### ISSUE TITLE
Add the ability to specify which serviceAccount the agent pod uses

### ISSUE THREAD

**Issue by dbeilin** [metalbear-co/mirrord#2876]
In addition to [this](https://github.com/metalbear-co/mirrord/pull/2834) PR which added support for a `nodeSelector`, I think specifying a SA would also be beneficial, instead of having the agent pod start with the default SA.

If this is something you'd approve of, I'm willing to give it a go and open a PR for it.

**Comment by Razz4780** [comment]
Yeah, I think it's ok. Thanks for willingness to contribute ^^
As for the operator - tbh I don't have any concerns, since agent config is controlled from the operator. Why would we need to check who controls the service account?

**Comment by aviramha** [comment]
> Yeah, I think it's ok. Thanks for willingness to contribute ^^ As for the operator - tbh I don't have any concerns, since agent config is controlled from the operator. Why would we need to check who controls the service account?

I don't think we'd need to do it - just saying that we need to make sure that this will be under the agent config and will not somehow affect via operator.

**Comment by Razz4780** [comment]
Ah, ok. All good then

**Comment by dbeilin** [comment]
Thanks guys, I created the PR.

**Comment by dbeilin** [comment]
Thanks for merging 😄
