### ISSUE TITLE
Failed to create a temporary local file

### ISSUE THREAD

**Issue by fordneild** [metalbear-co/mirrord#2889]
### Bug Description

When running my service, I seem to be getting these errors from mirrord
```
ERROR ThreadId(01) mirrord_layer::file::ops: Creating a temporary local file resulted in an error, closing the file remotely!
ERROR ThreadId(01) mirrord_layer::error: Error occured in Layer >> LocalFileCreation(6)```
```
which is then followed by my own service reporting 
```
Failed to parse install.yml. This could be because the file was moved or removed.
```

### Steps to Reproduce

Read file using os.ReadFile (golang) from `/Users/fneild/sources/witness-webhook/var/conf/install.yml` with the following mapping present
```
"^/Users/(?<path>\\S+)/var/(?<varPath>\\S+)": "/var/${varPath}"
```

### mirrord config

```json
{
  "feature": {
    "env": true,
    "fs": {
      "mode": "write",
      "mapping": {
        "^/Users/(?<path>\\S+)/var/(?<varPath>\\S+)": "/var/${varPath}"
      }
    },
    "network": {
      "incoming": {
        "mode": "steal"
      },
      "outgoing": {
        "tcp": true
      }
    }
  },
  "operator": false,
  "telemetry": false
}
```

### mirrord CLI version

3.115.1

### Your operating system and version

MacOS Sonoma Version 14.7 (23H124

### Local process

./tmp/main

**Comment by aviramha** [comment]
I couldn't reproduce this.<br>Can you try upgrading to latest mirrord please? (3.122.1)<br>If this keeps happening, can you try running in terminal (without mirrord):

```
echo test > $TMPDIR/1-test
echo test > /tmp/1-test
```

and report if those worked? (that's what happening in the failure underneath)

**Comment by aviramha** [comment]
Also,
You can try to use [this build](https://github.com/metalbear-co/mirrord/actions/runs/11651828816), which will provide better error and after you retrieve the better error you can use this config (with the build) to try a fix I added:
```json
{"experimental": {"use_dev_null": true}}
```

**Comment by fordneild** [comment]
Hey! I was able to run both of these locally
```
echo test > $TMPDIR/1-test
echo test > /tmp/1-test
```


And then forgive me if this is a noob question, but can you point me to docs for using a custom build? I tried downloading the universal macos binaries, but then saw this error pop up. Im on MacOS Arm, and use homebrew to download the normal build

<img width="257" alt="Screenshot 2024-11-03 at 5 21 07 PM" src="https://github.com/user-attachments/assets/e8772429-668a-4509-87c8-11a38c41a371">
