### ISSUE TITLE
Control over spawned processes

### ISSUE THREAD

**Issue by milad2golnia** [metalbear-co/mirrord#2891]
Thank you for this awesome  product.

Assume I have following configurations for *mirrord*:
```
{
  "target": "pod/bear-pod",
  "feature": {
    "env": true,
    "fs": "write",
    "network": true
  }
}
```
And here is interested part of code:
```
const child = spawn('mkvmerge', [
        '--default-duration',
        `0:${framerate}fps`,
        sourcePath,
        '-o',
        destinationPath,
      ])
```
Currently, all spawned processes are running on local machine and since all files (including `sourcePath` file) is just available in remote machine (considering `"fs": "write"` in configuration), It produces an error and we are not able to debug such programs.

It would be great if you offer a solution which gives us ability to run these spawned commands on remote machine. Is there any solution?

**Comment by aviramha** [comment]
hi @milad2golnia - this is not possible atm, and I don't think we will support it in the near future since it creates a lot of complexities.

**Comment by aviramha** [comment]
What is the source path / destination path?
also can you do `which mkvmerge` and then `file MKVMERGEPATH` (replace with path)

**Comment by aviramha** [comment]
Thank you - the problem is probably because of the use of relative path - mirrord automatically sets paths that are relative to be local.
Can you try the mkvmerge to have such command line?
```
mkvmerge --default-duration 0:25fps /media/da86527f-c75f-4e52-a98a-59186cbe0ba4/add17fb6-b571-434b-aaf8-7f1d45cc830f-1730724272420/recording-merged.webm -o /media/da86527f-c75f-4e52-a98a-59186cbe0ba4/add17fb6-b571-434b-aaf8-7f1d45cc830f-1730724272420/add17fb6-b571-434b-aaf8-7f1d45cc830f-fixed-framerate.webm
```
(I removed . from the path, so maybe you need to add the current directory instead)

**Comment by aviramha** [comment]
We resolve `/` locally by default as well
https://github.com/metalbear-co/mirrord/blob/main/mirrord/layer/src/file/filter/read_local_by_default.rs
