### ISSUE TITLE
mirrord fails when sniffer fails on old kernel

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2909]
was supposed to be fixed in 3.124.1 thanks to https://github.com/metalbear-co/mirrord/pull/2897 but apparently not

**Comment by meowjesty** [comment]
https://github.com/metalbear-co/mirrord/blob/81315899855bc742a7c7a094f44d737005429501/mirrord/agent/src/sniffer.rs#L167

Don't we need to change this to just log the error instead of `?`.
