### ISSUE TITLE
Update documentation to include outgoing traffic

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#295]
The overview text and architecture diagrams (and maybe other things I've missed) should include the new outgoing traffic feature.

**Comment by eyalb181** [comment]
There's the Technical Reference, but that's a lot of work and less urgent, so please open a separate issue for it.

**Comment by t4lz** [comment]
https://github.com/metalbear-co/mirrord/issues/334 separate issue for Technical Reference.
