### ISSUE TITLE
Getting started, "it seems to have no effect"

### ISSUE THREAD

**Issue by zack-littke-smith-ai** [metalbear-co/mirrord#2994]
Hi there, just learned about this tool and I'm excited to get started with it!

I'm having a bit of trouble getting started, likely due to my own errors, but I'm having trouble moving forward. When targeting a pod on my cluster, I am finding only env is as-expected in my service code, but os operations (file read) and networking operations seem unchanged / identical to my running the binary locally. Here's my setup:
* Building a golang service via bazel. From what i can tell, the produced binary is dynamically linked - running `file` gives: `ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, Go BuildID=redacted, BuildID[sha1]=d09b2c41eff7e55c4d00ea29b1895d273e820cdc, stripped`. Tried following instructions [here](https://mirrord.dev/docs/faq/common-issues/#ive-run-my-program-with-mirrord-but-it-seems-to-have-no-effect) to import "C" and/or add ldflags to the build but these seem not to have an effect.
* I am running on linux.
* I am running my service by directly referencing the produced binary, ie: `mirrord exec bazel-bin/... --target ...`. This produces:
```
* Running binary "bazel-bin/..." with arguments: [].
* mirrord will target: pod/..., a configuration file was loaded from: ...
* operator: the operator will be used if possible
* env: all environment variables will be fetched
* fs: file operations will default to read only from the remote
* incoming: incoming traffic will be mirrored
* outgoing: forwarding is enabled on TCP and UDP
* dns: DNS will be resolved remotely
⠒ mirrord exec
    ✓ running on latest (3.128.0)!
    ✓ ready to launch process
      ✓ layer extracted
      ✓ operator not found
      ✓ agent pod created
      ✓ pod is ready
    ✓ config summary  
```

As above, if i print the env, it seems correct, however connecting to the database in the cluster or executing file operations, it's identical to if i was running locally. I've browsed the troubleshooting docs but haven't found anything specific to my current predicament. Any help would be greatly appreciated, thank you in advance!

**Comment by aviramha** [comment]
Hi,
I am pretty sure the reason the first invocation you mentioned fails is because the binary is stripped. Does your bazel build command have a variant that doesn't strip symbols ?
