### ISSUE TITLE
Remote DNS doesn't work for node.js

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#321]
### Bug Description

@aviramha encountered the following error when enabling remote DNS on a Node.js app:
 
`2022-09-02T16:09:31.397836Z ERROR mirrord_layer::error: Error occured in Layer >> ResponseError(RemoteIO(RemoteIOError { raw_oserror: None, kind: Other }))
Assertion failed: (!"unknown EAI* error code"), function uv__getaddrinfo_translate_error, file ../deps/uv/src/unix/getaddrinfo.c, line 90.
[1]    90277 abort      mirrord exec -s "*" -o -d -p front-end-6585d48b5c-v6q2h -n sock-shop -- node
node dns with uvloop fails`

### Steps to Reproduce

Enable remote DNS on a Node.js app (that does some DNS resolving)

### Your operating system and version

N/A

### Local process

N/A

**Comment by aviramha** [comment]
I found one issue, and that's the DNS being resolved in the agent context instead of the impersonated container context.
Another theoretical issue is that the error is `IO` and not not found for some reason.. might be related to the first issue.

**Comment by aviramha** [comment]
Okay, besides the first theory, the error code didn't propagate but even when it did, macOS expects different codes than Linux so it needs more translation. PR incoming soon.
