### ISSUE TITLE
Have all features enabled by default

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#322]
At the moment only traffic mirroring is enabled by default, and everything else has to be enabled explicitly. Starting with version 3.0.0, we want to have all features (=mirroring, outgoing traffic, file ops, env vars) enabled by default, with the option to disable them explicitly.

**Comment by boaz0** [comment]
can i try my luck and work on this?

**Comment by eyalb181** [comment]
Hey @boaz0, this is something we're looking to get done by the end of the day tomorrow, so if you feel like you'd be able to get to it by then go ahead. Otherwise please feel free (and encouraged!) to grab some other issue :)
