### ISSUE TITLE
Display actual port for easy local testing

### ISSUE THREAD

**Issue by DmitryDodzin** [metalbear-co/mirrord#363]
After mirrord connects it remaps the expected listen port to a different one, causing confusion when trying to access the local process and receiving results without stealing the traffic

**Comment by infiniteregrets** [comment]
Do we not actually do so here https://github.com/metalbear-co/mirrord/blob/main/mirrord-layer/src/lib.rs#L88

**Comment by eyalb181** [comment]
@DmitryDodzin @infiniteregrets What's the verdict here?

**Comment by aviramha** [comment]
closed with #1561
