### ISSUE TITLE
Remote DNS fails under a specific setup

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#371]
### Bug Description

With the https://github.com/istio/istio/tree/master/samples/bookinfo example running in the google cloud, and the agent in a different namespace than the target pod, remote dns fails. It does not fail when the agent is in the same namespace.

### Steps to Reproduce

1. Setup the cluster from the istio repo, but with this load balancer:
    ```
    apiVersion: v1
    kind: Service
    metadata:
      name: example-service
    spec:
      selector:
        app: productpage
      ports:
        - port: 3000
          targetPort: 9080
      type: LoadBalancer
    ```
2. Run `productpage.py` on the `productpage...` pod with mirrord, with the agent pod in the default namespace than the target pod:
    ```
    mirrord exec -a default -n istio -d -c -s='*' -o --tcp-steal --pod-name productpage-v1-... python3 ../istio/samples/bookinfo/src/productpage/productpage.py 9080
    ```
3. Run `kubectl describe service example-service -n istio`
4. Find the IP address in the output (censored here):
    ```
    LoadBalancer Ingress:     ***.***.***.***
    Port:                     <unset>  3000/TCP
    ```
5. Surf with your browser to http://\<Ingress-IP\>:3000/productpage?u=normal
6. The details and reviews on the page are missing because the service cannot complete the dns queries to the other microservices.

### Relevant Logs

```shell
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): reviews:9080
2022-09-07T10:32:51.779200Z TRACE mirrord_layer::socket::hooks: getaddrinfo_detour -> raw_node 0x0000000106a521d0 | raw_service 0x000000016f39875a | raw_hints addrinfo {
    ai_flags: 0,
    ai_family: 0,
    ai_socktype: 1,
    ai_protocol: 0,
    ai_addrlen: 0,
    ai_canonname: 0x0000000000000000,
    ai_addr: 0x0000000000000000,
    ai_next: 0x0000000000000000,
} | out? false
2022-09-07T10:32:51.779221Z TRACE mirrord_layer::socket::ops: getaddrinfo -> node Some(
    "reviews",
) | service Some(
    "9080",
) | hints Some(
    AddrInfoHint {
        ai_family: 0,
        ai_socktype: 1,
        ai_protocol: 0,
        ai_flags: 0,
    },
)
2022-09-07T10:32:51.779256Z TRACE mirrord_layer: Layer::handle_hook_message -> hook_message GetAddrInfoHook(GetAddrInfoHook { node: Some("reviews"), service: Some("9080"), hints: Some(AddrInfoHint { ai_family: 0, ai_socktype: 1, ai_protocol: 0, ai_flags: 0 }), hook_channel_tx: Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: true, is_tx_task_set: false } }) } })
2022-09-07T10:32:51.779267Z TRACE mirrord_layer: HookMessage::GetAddrInfo
2022-09-07T10:32:52.026950Z TRACE mirrord_layer: DaemonMessage::GetAddrInfoResponse Err(
    DnsFailure(
        -5,
    ),
)
```

### Your operating system and version

macOS Monterey 12.5.1

### Local process

Python

### Local process version

3.9.13

**Comment by t4lz** [comment]
Not a bug:
The `productpage` service is searching the `reviews` service by only its service name, [which is only possible from within a namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#namespaces-and-dns). `productpage.py` allows specifying the dns names by environment variable, and if you run it with mirrord with the agent in a different namespace, but specify the full DNS entry via environment variable: `REVIEWS_HOSTNAME=reviews.istio.svc.cluster.local` and `DETAILS_HOSTNAME=details.istio.svc.cluster.local` the reviews and details are displayed successfully.

**Comment by aviramha** [comment]
The agent impersonates the pod, and the agent running namespace shouldn't matter for DNS as the agent resolves it from the context of the pod, meaning it's actually resolving from the namespace of the impersonated pod (linux namespace != k8s namespace)
I think I know what's the issue though - the way dns resolving works is that it checks the local `/etc/resolv.conf` for settings (like adding a prefix of domain on lookups) then sends queries. The lookup is running in the network namespace of the pod but not in the **file** namespace, meaning it probably opens the `/etc/resolv.conf` of the agent instead of the pod. I think the fix would be to add to the name space change to set the file namespace as well.

**Comment by t4lz** [comment]
Ok, but just to make sure that's fine: If we do this change, users might use the `--agent-namespace` flag in expectation to then be able to use only service names for accessing services in that Kubernetes namespace but that would fail.

**Comment by eyalb181** [comment]
I don't think that's implied - the user specifies a pod and the agent impersonates it, no matter which namespaces the two are in.

**Comment by t4lz** [comment]
Was this solved by https://github.com/metalbear-co/mirrord/pull/481?

**Comment by aviramha** [comment]
Yes It should be solved. Can you try to test it then close?

**Comment by t4lz** [comment]
Tested with the same istio example setup, using this command:
```
RUST_LOG=mirrord=debug MIRRORD_AGENT_IMAGE=test /Users/t4lz/Documents/projects/mirrord/target/debug/mirrord exec --agent-namespace default --target-namespace istio -c -s='*' --no-fs --steal --target deployment/productpage-v1 python3 src/productpage/productpage.py 9080
```
And the app now works, details and reviews appear. I verified that I'm served by the local process by changing the book title in the local `productpage.py`, and also verified with `kubectl` that the agent was indeed running in a different namespace than the target pod.
