### ISSUE TITLE
Start the agent in the same namespace as the pod by default

### ISSUE THREAD

**Issue by tamasfe** [metalbear-co/mirrord#391]
DNS with only a service name will be resolved in the agent's namespace, thus the following does not work:

```mirrord exec -n foo-ns --pod-name foo-server -- ping foo-svc```

Whereas this will:

```
mirrord exec -a foo-ns -n foo-ns --pod-name foo-server -- ping foo-svc
```

Unless there's an important reason for the current behaviour, the agent could default to the pod's namespace if it's not explicitly given.

**Comment by aviramha** [comment]
This sounds like a bug as the agent *should spawn* in the same namespace as the pod if not specified.
Thanks for reporting this, we'll look into it!
