### ISSUE TITLE
Shorter way to select a container in the CLI

### ISSUE THREAD

**Issue by tamasfe** [metalbear-co/mirrord#392]
`--impersonated-container-name` is quite a mouthful with no short flags.

Instead of introducing a short flag for it, I'd suggest an alternative for `--pod-name`.

Since #293 is planned, something more general could work as a target selector.

Some ideas:

```
--target pod/foo-asd1234/container-name
```

For deployments:

```
--target deployment/foo
```

Or in case services are supported in the future:

```
--target svc/foo
```

**Comment by aviramha** [comment]
That's an interesting approach. We will start thinking about this after the MVP stable release!
