### ISSUE TITLE
Support mirroring in service mesh proxies

### ISSUE THREAD

**Issue by tamasfe** [metalbear-co/mirrord#397]
Currently if a pod is meshed with a [`linkerd-proxy`](https://github.com/linkerd/linkerd2) the traffic will not reach the agent, and the `linkerd-proxy` container cannot be impersonated #396.

**Comment by tamasfe** [comment]
#396 has been fixed, but no traffic is captured still, or at least the traffic I expect. Linkerd uses its own TLS that could interfere, or some other magic. Without knowing mirrord internals, I can't investigate this further for now.

**Comment by eyalb181** [comment]
Update: service mesh proxies should be mostly supported now, with the exception of traffic mirroring (stealing works fine). The reason for this is that we only starts mirroring when a connection is closed and a new connection is opened, and this can take a while to happen on linkerd (keep-alive is 10 seconds, so we'd need it not to receive any requests for that amount of time).

**Comment by meowjesty** [comment]
Should've been fixed by #1887 , see caveats there.

**Comment by aviramha** [comment]
@meowjesty Please create a follow up ticket (mid-packet HTTP detection) and then close this one
Thanks!

**Comment by meowjesty** [comment]
Tracked in #1942
