### ISSUE TITLE
mirrord-layer deadlocks if accept is called when there's no data

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#41]
### Bug Description

When accept is called before a connection is read from the agent, it locks the connections struct and there's a deadlock.

### Steps to Reproduce

Simulate a delay so that accept is called before a connection is read from the agent.

### Your operating system and version

MacOS

### Your Node version (`node --version`)

N/A

**Comment by aviramha** [comment]
Closed via #44
