### ISSUE TITLE
When running with VSCode's Node debugger, mirrord hooks and breaks an internal socket

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#42]
### Bug Description

VSCode's Node debugger uses a socket for some internal mechanism. Mirrord hooks it, breaking the flow. We should be able to overlook these sockets.

### Steps to Reproduce

Debug a node process in VSCode with mirrord-layer in LD_PRELOAD.

### Your operating system and version

MacOS

### Your Node version (`node --version`)

v17.6.0

**Comment by aviramha** [comment]
Closed via #44
