### ISSUE TITLE
`-x` has no "*" option

### ISSUE THREAD

**Issue by tamasfe** [metalbear-co/mirrord#433]
### Bug Description

`-s '*'` can be used to include all environment variables from a pod but `-x '*'` is ignored. `-s ''` can be used for the same effect as a workaround.

### Steps to Reproduce

1. run `mirrord exec -x '*' ...`
2. assert that env variables from the pod are there

### Your operating system and version

Linux

### Local process

does not matter

**Comment by eyalb181** [comment]
Don't you get the same behavior from omitting these two arguments entirely?

**Comment by tamasfe** [comment]
My observations without looking at the code:

- without flags all env vars are enabled from the pod
- `-s ''`: no env vars from pod
- `-x "FOO"`: env vars from pod without `FOO`

**Comment by aviramha** [comment]
> Don't you get the same behavior from omitting these two arguments entirely?

I assume the desire here is to not have remote environment. The default is to provide same env

**Comment by eyalb181** [comment]
Yup, understood, my mistake.
