### ISSUE TITLE
Support cleaning mirrord-agent pods

### ISSUE THREAD

**Issue by itaischwartz** [metalbear-co/mirrord#482]
Using mirrord 3.0.10-alpha
`mirrord exec` results in an orphan `mirrord-agent` pods with status `NotReady`
I think you should document this behavior, and add a way to remove the pods using mirrord CLI.

**Comment by aviramha** [comment]
Hey @itaischwartz ! Thanks for opening the issue. This sounds like a bug. Did mirrord work alright?

**Comment by itaischwartz** [comment]
It didn't
Maybe it was something on my side (We're using istio service-mesh)
I was using the following command:

 mirrord exec --pod-name backend -n apps --impersonated-container-name
backend ./bin/server :80

‫בתאריך יום א׳, 2 באוק׳ 2022 ב-21:28 מאת ‪Aviram Hassan‬‏ <‪
***@***.***‬‏>:‬

**Comment by aviramha** [comment]
Opened relevant issue - https://github.com/metalbear-co/mirrord/issues/485
Regarding the cleaning of the pods - we shouldn't have any lingering pods after you're done using, so I don't think we want to add such feature (as it might imply to users that we mirrord persists longer than promised). Closing this and let's track this in the new issue.
