### ISSUE TITLE
Add brew install

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#484]
Write a brew formula for Linux and macOS. Add the instructions on how to use it to mirrord.dev and the README file.

**Comment by detronetdip** [comment]
I am interested in this issue could you please elaborate it to me.

**Comment by eyalb181** [comment]
Sorry @detronetdip, we've already started work on this one, forgot to change the assignee.

**Comment by detronetdip** [comment]
Ok

**Comment by infiniteregrets** [comment]
Update: the formula is available here: https://github.com/metalbear-co/homebrew-mirrord for linux and macos

However, we need to automate updating the sha256 and the links on every release, so keeping this issue open
