### ISSUE TITLE
Wrapping a Flask process with an absolute path causes issues with file reads

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#492]
### Bug Description

When running a Flask process with mirrord and specifying the file's full path (e.g. `mirrord exec -p podname -- python /Users/eyalbukchin/flaskapp.py`), the process tries to open files with their absolute paths (e.g. /Users/eyalbukchin/templates/homepage.html), which of course don't exist on the remote pod.

### Steps to Reproduce

Run a Flask process with mirrord, specify the file as an absolute path.

### Your operating system and version

MacOS

### Local process

python

**Comment by infiniteregrets** [comment]
sorry not sure if I understand, are you saying when the process's path is absolute, the files it opens before the server starts are absolute if they are supposed to be relative?

does the flask server not start?

**Comment by eyalb181** [comment]
I think in my case it did start, but then tried to load html templates from my personal user path but on the remote server

**Comment by eyalb181** [comment]
Yup, see my first comment. However Alex's PR is for supporting dynamic file filters, whereas we should add /Users to our static list

**Comment by aviramha** [comment]
Fixed by https://github.com/metalbear-co/mirrord/pull/639
