### ISSUE TITLE
v2.0 Test Plan

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#50]
## 1. Core (Layer + Agent)

1. Happy Flow (Run for Node.js, FastAPI)
    1. Run a process that prints data received with the mirrord env variables
    2. Send three different requests to the impersonated pod
    3. For each request, assert that the correct data was printed
    4. Stop the process
    5. After 30 seconds, assert that the job and agent were both deleted from the cluster
2. Wrong Pod
    1. 1.1.a
    2. Send a request to a different pod in the cluster
    3. Assert that the request wasn’t printed
3. Agent Namespace
    1. Happy Flow
        1. Create a new k8s namespace (call it ‘test-namespace’)
        2. Run a process that prints data received with the mirrord env variables and MIRRORD_AGENT_NAMESPACE=test-namespace
        3. Assert that the job and the agent were created in the cluster under ‘test-namespace’
        4. 1.b-1.c
    2. Nonexistent namespace
        1. Run a process that prints data received with the mirrod env variables and MIRRORD_AGENT_NAMESPACE=<some nonexistent namespace>
        2. Assert that the process crashes with an indicative error
        3. Assert that a new job and agent weren’t created
4. Pod Namespace
    1. Happy Flow
        1. Create a new k8s namespace (call it ‘test-namespace’)
        2. Create a new nginx pod under test-namespace
        3. Run a process that prints data received with the mirrord env variables, IMPERSONATED_POD_NAME set to the name of the nginx pod, and IMPERSONATED_POD_NAMESPACE set to the name of the nginx namespace
        4. 1.1.b-1.1.c
    2. Nonexistent namespace
        1. Run a process that prints data received with the mirrord env variables and IMPERSONATED_POD_NAMESPACE set to a nonexistent namespace
        2. Assert that the process crashed with an indicative error
        3. Assert that a new job and agent weren’t created

## 2. CLI

1. Happy Flow (run for Node.js, FastAPI)
    1. Using the CLI, run a process that prints data received
    2. 1.1.b-1.1.e

## 3. VSCode Extension

1. Happy Flow (Run for Node.js, FastAPI. Test at least one on WSL)
    1. Click ‘enable mirrord’
    2. Set a breakpoint in the debugged process
    3. Start debugging the process
    4. Send a request to the impersonated pod
    5. Assert the breakpoint is hit with the correct data
2. Repeat use
    1. 3.1.a-3.1.e
    2. Stop debugging the process
    3. Click ‘disable mirrord’
    4. 3.1.c-3.1.d
    5. Assert the breakpoint wasn’t hit
    6. 3.1.a-3.1.e

**Comment by aviramha** [comment]
I would add WSL check for vs code extension.
