### ISSUE TITLE
Add detours for dup/dup2/fcntl system calls

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord#51]
When mirrord exec is called with a simple flask API (https://gist.github.com/infiniteregrets/ba753ffb53ff8b98b2dd8f5051323919), where port 80/any other port is explicitly specified, the application seems to ignore that and instead assign a different port. This could perhaps be due to a call to `dup` or `fcntl` with `F_DUPFD/F_DUPFD_CLOEXEC` flags where mirrord is not aware of the new sockfd and probably getsockname returns a different port to the flask app. So we might need to add detours for the mentioned system calls to bring new sockfds to mirrord book-keeping. 
More context:
Strace of flask API: https://gist.github.com/infiniteregrets/09773cc3f1aee7983f95fc800ff8d969
Agent logs when enforcing port `3689` in the Flask Application: https://gist.github.com/infiniteregrets/7c42aeae359e3a55c756f2ba9c7e1213

**Comment by aviramha** [comment]
Thanks for reporting this issue.
Short brief about what `dup` or `fcntl` with `F_DUPFD*` does is that it creates a new fd that is linked to the same structure in the kernel as the first. Some sort of a soft symbolic link.
The way I see it, we can solve it in 2 ways:
1. When `dup` (and other options) is used, we clone the data structure to the new fd. It might create odd side effects, as from our perspective the two sockets will have *different* states. That's an easy solution but probably not great.
2. We change our sockets hashmap to from `HashMap<RawFd, Socket>` to `<HashMap<RawFd, Arc<Socket>>`. This way when we create a real socket we'll wrap it with `Arc` then when `dup` (and friends) are called we just clone the Arc, having similar behavior to what we have in kernel (different fds pointing to same struct)

I think the only disadvantage of doing 2 is introducing a bit of complexity to our internal structures, but that seems like the better approach. 
@metalbear-co/core would love your opinion.

**Comment by meowjesty** [comment]
> different states

Don't like the sound of that,

I would go with the `Arc` solution, I think the additional complexity is more manageable than handling the different states.
