### ISSUE TITLE
Extend label support

### ISSUE THREAD

**Issue by itaischwartz** [metalbear-co/mirrord#524]
mirrord assumes that the pod contains an `app` label.
https://github.com/metalbear-co/mirrord/blob/28856ded64c48751612bd9c2aa6f3245bdf324d2/mirrord-layer/src/pod_api.rs#L480

I wish you either add this as a requirement in documentation or add an option to provide a custom label.

Using `mirrord 3.0.19-alpha`

**Comment by infiniteregrets** [comment]
hi @itaischwartz, thanks for opening the issue! I have patched the deployment target selection not to use the app label, but rather just rely on the labels present in the deployment. I will update the documentation accordingly.

**Comment by aviramha** [comment]
Closed with #534 . Thanks @infiniteregrets for solving it and @itaischwartz for the report. It will be available in the next mirrord version.
