### ISSUE TITLE
mirrord extract panics on non-existent directories

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord#53]
```
mehula@mehul-machine:~/mirrord$ target/debug/mirrord extract blah 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', mirrord-cli/src/main.rs:70:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
It would be nicer to handle the Result type gracefully and return an error or maybe prompt the user whether they want to create the directory (only useful for CLI users)

**Comment by aviramha** [comment]
I am against creating the directory as the extract functionality isn't really user-facing (in most cases). I am up for returning a nice message though. 
It's an easy issue for new contributors, so let's leave it for them.?

**Comment by infiniteregrets** [comment]
yes sounds good! once we have more related issues ill add this to one central tracking issue
