### ISSUE TITLE
Add include/exclude list functionality for fileop paths

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#530]
We should let users specify which paths to include or exclude from remote file ops.

**Comment by meowjesty** [comment]
Few questions about this:

1. Do we keep our ignored file list? Say the user specifies `--exclude=/foo`, do we exclude this path + our default?
2. Should the user be able to override our ignored list (allow the user to `--include=/home/{user}/Downloads` for example)?
3. How should a flag like `--include` work? Say we have `--include=/foo;/baz/bar`, does this mean that we exclude every other path?

**Comment by eyalb181** [comment]
1. Good question. I think that for now we should keep our ignored file list in addition to the user's exclude list, but let the user override it with include if they want, like you suggested in 2.
2. ^
3. Yup
