### ISSUE TITLE
Config file JSON schema

### ISSUE THREAD

**Issue by tamasfe** [metalbear-co/mirrord#538]
A JSON schema for `mirrord.toml|yaml` that is submitted to the [schema store](https://schemastore.org) would enable linting/completion in IDEs and other tools.

It could be either hand-written, or preferably generated with something like [schemars](https://crates.io/crates/schemars).

Open tasks:

- [x] documentation of fields
- [x] distribution either via the schema store (or probably the vscode extension)

edit: fields are documented.
edit2: merged to the schema store.

**Comment by aviramha** [comment]
Great idea! we'll prioritize it.

**Comment by aviramha** [comment]
Closed by #543. Thanks @tamasfe !

**Comment by tamasfe** [comment]
The schema exists, but it still needs
- documentation of fields
- distribution either via the schema store (or probably the vscode extension)

**Comment by aviramha** [comment]
@tamasfe reopening - let's use this issue for tracking the required steps that needs to be done.

**Comment by meowjesty** [comment]
Fields documented by #661 

Just need to settle for a file name for the user's `mirrord-config.[json|toml|yaml]`, and then we can close this.

**Comment by tamasfe** [comment]
I'd suggest picking a name that is as short as possible. Right now I use configs such as as `foo.mirrord.toml`, so something like `.*\.mirrord\.(json|toml|(ya?ml))$` could work imo.

I'd also suggest distributing the schema via the vscode extension as well (orthogonal to the schema store).

**Comment by meowjesty** [comment]
Schema is now distributed in the vscode-extension by #714.
