### ISSUE TITLE
Support for linux/arm64

### ISSUE THREAD

**Issue by itaischwartz** [metalbear-co/mirrord#563]
I would like to run `mirrord` in a Docker container.
For Apple silicon, this requires arm64 support.

**Comment by aviramha** [comment]
More context: arm64 support should be easy, arm64 + go support would take some more tinkering as right now we implement the trapmolines in assembly. @t4lz should solve this as part of his Go journey.

**Comment by t4lz** [comment]
Do we want to support all Go versions on Linux + aarch64? Which one should we do first (1.20/1.19/1.18)?

**Comment by aviramha** [comment]
Start from 1.20 then 1.19
