### ISSUE TITLE
Support pod port-forwarding

### ISSUE THREAD

**Issue by itaischwartz** [metalbear-co/mirrord#567]
I would like to use mirrord to connect to managed RDS service.

I can use something like:
`mirrord exec --no-fs -s "" --target <deployment>   -- /opt/homebrew/opt/libpq/bin/psql -h rds-addr -U admin`
What if I want to use GUI applications such as pgAdmin?

I think something like
`mirrord proxy --target <depoyment> <remote_addr:remote_port> <local_addr:local_port>` could be useful for debugging

Related issues and projects:
https://github.com/kubernetes/kubernetes/issues/72597
https://github.com/knight42/krelay

**Comment by aviramha** [comment]
Thanks for reporting this! It's an interesting use case which can be supported.
If anyone else would like to see this implemented, please upvote it.

**Comment by itaischwartz** [comment]
I think the new agentless mode is a good step toward supporting this :)

**Comment by aviramha** [comment]
Planning to implement it like the `ssh` port forwarding (`mirrord port-forward -t target -L ...`) so we can later on do `-R` in #2609

**Comment by gememma** [comment]
> Planning to implement it like the `ssh` port forwarding (`mirrord port-forward -t target -L ...`) so we can later on do `-R` in #2609

Would you prefer the argument format to follow `ssh` exactly, ie: `-L local_port:destination_server_ip:remote_port ssh_server_hostname`? or should they be non-optional? @aviramha

**Comment by aviramha** [comment]
`ssh_server_hostname` - no, though it's a good question. I think we should stick to `-t target` and if user doesn't specify use targetless like we do with exec.
and regarding `-L`, `local_port` should be optional (default to `remote_port`, that's how it works with ssh afaik)

**Comment by aviramha** [comment]
another note - this should be marked as unstable.
