### ISSUE TITLE
Support incoming traffic from multiple pods

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#571]
As discussed [here](https://github.com/metalbear-co/mirrord/discussions/541), when a deployment has multiple pods we only mirror/steal incoming traffic from one of them, leading to missed traffic. [This](https://github.com/metalbear-co/mirrord/issues/527) is being developed as a temporary solution, but we should strive to properly support incoming traffic from multiple pods.

**Comment by aviramha** [comment]
Part of mirrord for Teams
