### ISSUE TITLE
Error log on closed stream

### ISSUE THREAD

**Issue by tamasfe** [metalbear-co/mirrord#577]
### Bug Description

Error messages during seemingly normal operation.

Are the following supposed to be `debug!`, or is it something unexpected I should look into?

https://github.com/metalbear-co/mirrord/blob/6451e0daf7941c743ad2d6864806dc2fdf20210c/mirrord-layer/src/outgoing/tcp.rs#L110

and 

https://github.com/metalbear-co/mirrord/blob/6451e0daf7941c743ad2d6864806dc2fdf20210c/mirrord-layer/src/outgoing/udp.rs#L131

### Steps to Reproduce

I don't have an MCVE for it yet.

### Your operating system and version

Linux 5.15.73-1-lts

### Local process

proprietary

**Comment by aviramha** [comment]
It looks like it needs to be `debug!` as you suggested.
@meowjesty WDYT?

**Comment by meowjesty** [comment]
Ooops! Thanks for the report. These should be just `trace` or `debug` (feel free to point out similar logs, as I'm sure there are more 😅 ).
