### ISSUE TITLE
Change VSCode Extension configuration to use the mirrord config file

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#583]
Currently configuration is done through the UI and is pretty non-standard and has to be updated every time we add a new configuration value (it's pretty out of date already). We should have it use the mirrord config file instead, and if possible and simple, also provide some UI for it - perhaps through the extension settings window of VS Code.

**Comment by infiniteregrets** [comment]
i think, if conifg file is found, we can just warn the user that we are using the config file otherwise we spawn the UI. besides that on the implementation level I think we'd have to use a json/toml/yaml parser and set the env accordingly..

**Comment by aviramha** [comment]
we don't need to set any env; you provide the layer the config path and it uses it instead of any other env.

**Comment by aviramha** [comment]
we don't need to set any env; you provide the layer the config path and it uses it instead of any other env.
