### ISSUE TITLE
Change IntelliJ Plugin configuration to use the mirrord config file

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#584]
Currently configuration is done through the UI and is pretty non-standard and has to be updated every time we add a new configuration value (it's pretty out of date already). We should have it use the mirrord config file instead, and if possible and simple, also provide some UI for it.

**Comment by jamowei** [comment]
I could try to find a solution for that, but where can I find the current config-file to read from? Does it get generated?

**Comment by aviramha** [comment]
That'd be great @jamowei . We don't generate it, it's a file user can create then provide it as an input to mirrord.
The schema can be generated using `cargo test -p mirrord-config print_schema --features schema -- --ignored --nocapture`.

**Comment by jamowei** [comment]
Ok, I tried your command and getting the following error on `master`-branch:
```
   Compiling mirrord-config v3.4.0 (/Users/jamowei/IdeaProjects/mirrord/mirrord-config)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> mirrord-config/src/lib.rs:1:12
  |
1 | #![feature(slice_concat_trait)]
  |            ^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> mirrord-config/src/lib.rs:2:12
  |
2 | #![feature(once_cell)]
  |            ^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `mirrord-config` due to 2 previous errors

```

**Comment by aviramha** [comment]
Sorry I was assuming you're running nightly. The correct one would be `cargo +nightly test -p mirrord-config print_schema --features schema -- --ignored --nocapture`

**Comment by aviramha** [comment]
Yes because it's used instead of most of the env vars.
The file you attached is a schema that conforms to https://json-schema.org/
You can create a file conforming to it then set the env var `MIRRORD_CONFIG_FILE` to the config file path and it will use it.
I appreciate the desire to help and would understand if you want to wait until we have more docs/examples of using the file, as an alternative until then you can chat with us on our Discord and we can provide further interactive guidance.

**Comment by jamowei** [comment]
Ah ok, thank you. Now I understand your idea better. I would suggest it would be then nice to have an option to present a project based config file for the extension, maybe with a default name (like `mirrord.yaml`) which the extension tries to find and read from. Then after selection a pod mirrord starts right away. I'm right? :)

Yeah, Discord would be an option, but I must see when I have enough time for this to do. I will get back to you when the time comes.

**Comment by aviramha** [comment]
Done as part of #849

**Comment by jamowei** [comment]
I'm sorry. I didn't find time for that :/

**Comment by aviramha** [comment]
That's okay! We totally understand and appreciate your time.
