### ISSUE TITLE
Better error for agent connection failed

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#615]
Right now if we can't make a websocket connection to the agent we get the following:
```
thread '<unnamed>' panicked at 'failed to create agent in k8s: mirrord-layer: Kube failed with error `failed to upgrade to a WebSocket connection: failed to switch protocol: 404 Not Found`!', mirrord-layer/src/connection.rs:84:14
```
It's not very helpful as in many cases it means that
A. agent doesn't exist/exited
B. wrong kubernetes credentials used
we should specify those possible reasons.

**Comment by eyalb181** [comment]
Wasn't this closed by #617?
