### ISSUE TITLE
Support MIRRORD_AGENT_TTL as an argument in the CLI

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#62]
It's currently only usable as an environment variable.

**Comment by thedanvail** [comment]
Planning on looking at this once #144 is merged.

Looking at it now, my approach will probably be to edit the `ExecArgs` struct to add in the `MIRRORD_AGENT_TTL` that will override an environment variable. If it's not in the CLI args, I'll default back to the environment setting or the default setting of 0.

**Comment by aviramha** [comment]
Awesome @thedanvail. Assigning this to you :)

**Comment by thedanvail** [comment]
Addressed in #156

**Comment by aviramha** [comment]
Thank you!
