### ISSUE TITLE
After about 10 minutes of idle time, mirrord-layer starts reading empty messages

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#63]
### Bug Description

This isn't the result of the agent terminating, as logs indicate it's still alive when that happens.

### Steps to Reproduce

Start a process wrapped by mirrord-layer and wait for about 10 minutes.

### Your operating system and version

MacOS

### Your Node version (`node --version`)

17.6.0

**Comment by aviramha** [comment]
I believe this is some timeout, whether by websocket (k8s), kernel or maybe some network component in the way. I suggest adding a keep alive if no data for X duration
