### ISSUE TITLE
Macos development hurdles

### ISSUE THREAD

**Issue by IsaacCloos** [metalbear-co/mirrord#634]
### Bug Description

Currently, the default branch cannot `check` or `build`  with macos (arm64). 

The following dependencies are failing over code compatible exclusively with linux, and yet are required by the project to function on all development platforms.

1. [rawsocket](https://github.com/metalbear-co/rawsocket) | [added](https://github.com/metalbear-co/mirrord/pull/516) | [problem code](https://github.com/metalbear-co/rawsocket/blob/dc7c25d81a8073deb61e8c94ff6196609aca8d4d/bs-filter/src/cbpf.rs#L42-L59)
2. [iptables](https://github.com/yaa110/rust-iptables) | [added](https://github.com/metalbear-co/mirrord/pull/215) | [problem code](https://github.com/yaa110/rust-iptables/blob/3a24f420fb08281fd3655e50820a0a1eee0213ac/src/lib.rs#L188-L212)

### Steps to Reproduce

1. clone mirrord default branch
2. exec `cargo c` or `cargo b`
3. 💥

### Backtrace

```shell
Isaacs-MBP:mirrord cloosisaac$ cargo check
    Checking bs-filter v0.1.0 (https://github.com/metalbear-co/rawsocket.git#dc7c25d8)
    Checking iptables v0.5.0
error[E0412]: cannot find type `sock_fprog` in crate `libc`
  --> /Users/cloosisaac/.cargo/git/checkouts/rawsocket-368652c59e9ee3ab/dc7c25d/bs-filter/src/cbpf.rs:52:17
   |
52 | impl Into<libc::sock_fprog> for SocketFilterProgram {
   |                 ^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `sock_fprog` in crate `libc`
  --> /Users/cloosisaac/.cargo/git/checkouts/rawsocket-368652c59e9ee3ab/dc7c25d/bs-filter/src/cbpf.rs:53:28
   |
53 |     fn into(self) -> libc::sock_fprog {
   |                            ^^^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `sock_fprog` in crate `libc`
  --> /Users/cloosisaac/.cargo/git/checkouts/rawsocket-368652c59e9ee3ab/dc7c25d/bs-filter/src/cbpf.rs:54:15
   |
54 |         libc::sock_fprog {
   |               ^^^^^^^^^^ not found in `libc`

Some errors have detailed explanations: E0412, E0422.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `bs-filter` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error[E0599]: no method named `exists` found for reference `&IPTables` in the current scope
   --> /Users/cloosisaac/.cargo/registry/src/github.com-1ecc6299db9ec823/iptables-0.5.0/src/lib.rs:256:17
    |
256 |         if self.exists(table, chain, rule)? {
    |                 ^^^^^^ help: there is a method with a similar name: `list`

error[E0599]: no method named `exists` found for reference `&IPTables` in the current scope
   --> /Users/cloosisaac/.cargo/registry/src/github.com-1ecc6299db9ec823/iptables-0.5.0/src/lib.rs:294:17
    |
294 |         if self.exists(table, chain, rule)? {
    |                 ^^^^^^ help: there is a method with a similar name: `list`

error[E0599]: no method named `exists` found for reference `&IPTables` in the current scope
   --> /Users/cloosisaac/.cargo/registry/src/github.com-1ecc6299db9ec823/iptables-0.5.0/src/lib.rs:308:17
    |
308 |         if self.exists(table, chain, rule)? {
    |                 ^^^^^^ help: there is a method with a similar name: `list`

error[E0599]: no method named `exists` found for reference `&IPTables` in the current scope
   --> /Users/cloosisaac/.cargo/registry/src/github.com-1ecc6299db9ec823/iptables-0.5.0/src/lib.rs:323:20
    |
323 |         while self.exists(table, chain, rule)? {
    |                    ^^^^^^ help: there is a method with a similar name: `list`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `iptables` due to 4 previous errors
```

### Your operating system and version

macOS Monterey Version 12.6

### Local process

N/A

### Additional Info

After my last PR these issues started to impact my ability to work on the project, so they are pretty recent.

---

As far as I can tell the CI isn't affected by these changes (since it includes mac12 and 11)
https://github.com/metalbear-co/mirrord/blob/6035d82acc7f3a134905dec2d4303b45933dd928/.github/workflows/ci.yaml#L155-L174
https://github.com/metalbear-co/mirrord/blob/6035d82acc7f3a134905dec2d4303b45933dd928/.github/workflows/ci.yaml#L251-L254
 so I'm a little worried I'm missing an obvious piece of the puzzle to get this working. If that is the case perhaps this ticket can be more directed at improving the ergonomics of mirrord development on mac 😄

**Comment by infiniteregrets** [comment]
hi @IsaacCloos, thanks for opening this issue. 
The `mirrord-agent` component heavily relies on some linux specific functionality and is shipped as an image, which is run as an ephemeral agent with the pod being impersonated.

On macos, you can't build `mirrord-agent`, however, you can compile like so: `cargo build --workspace --exclude mirrord-agent` or `cargo build -p mirrord` (this seems to ignore agent).

Since you can't build the agent on macos, you can build the docker image for it using docker and you can specify this image in the config file or as env variable.

We should document this somewhere, would you like to add docs for this?

**Comment by IsaacCloos** [comment]
Thank you for the detailed response! 

Could cfg flags guard these components on systems they don't support?

**Comment by infiniteregrets** [comment]
yw!, and unfortunately, not. Its linux based

> Thank you for the detailed response!
> 
> Could cfg flags guard these components on systems they don't support?

**Comment by infiniteregrets** [comment]
hope your question is answered, closing this issue. Feel free to reach out with any issues, either here or on our discord https://discord.com/invite/J5YSrStDKD. Thanks again and sorry for the inconvenience
