### ISSUE TITLE
Revamp IntelliJ extension UI

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#636]
The UI in the IntelliJ extension looks a bit hacky at the moment, we need to revamp it to make it look more legit.

**Comment by jamowei** [comment]
Is it ok now after my changes?

**Comment by eyalb181** [comment]
Hey Jan, it's a step in the right direction, but another thing we wanted to try is to separate the settings to a different button so they don't show up every time mirrord is run. Ideally when you run mirrord you'd only have to pick a pod.

**Comment by aviramha** [comment]
I think we're okay for now after #849
