### ISSUE TITLE
v3.2.0 and istio support

### ISSUE THREAD

**Issue by wirtsi** [metalbear-co/mirrord#640]
### Bug Description

I am currently investigating mirrord in a rather complex multi-cluster Gloo Mesh setup (which is another layer on top of istio)

Now that https://github.com/metalbear-co/mirrord/issues/485, I would assume that mirrord should also work on istio setups without having to use `--steal`

I can confirm that with 3.2.0 the mirrord-agent is created correctly (so it has no sidecar) but requests are not intercepted locally

### Steps to Reproduce

* Launch `mirrord exec  --agent-namespace product-checkout  --target-namespace product-checkout  --target pod/cart-api-integration-5b5596f699-mqg5s/container/cart-api node index.js`
* Call endpoint via public Gateway -> Request is not intercepted but served from target pod
* Launch above command with `--steal`, requests end up on my locale machine

### Backtrace

```shell
As nothing is crashing, no backtrace
```

### Your operating system and version

Linux 5.11.0-1023-gcp

### Local process

/usr/bin/node: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=5141090ddf3282bf654333ed2b406bd108e0fc38, with debug_info, not stripped

### Local process version

v16.18.0

**Comment by eyalb181** [comment]
Hey @wirtsi, thanks for reporting! It's actually a known issue that we don't support mirroring on clusters with a service mesh. It's in the [FAQ](https://mirrord.dev/docs/overview/faq/#does-mirrord-support-clusters-with-a-service-mesh-like-istio-or-linkerd) - if you have an idea of a better place to put it, let us know.
We're currently working on adding support for mirroring though - we hope to have this working sometime during next week. Follow issue #397 for updates.

**Comment by wirtsi** [comment]
Hey @eyalb181, thanks for the response. I did see the entry in the FAQ but I was hoping that the "cannot mirror traffic with istio" was fixed by #485. But there seems to be more to it, I will stay tuned.

For now mirrord is the tool that works best with our setup here. What I would be really interesting in is "conditional intercepts" (ie. only send to my machine if a cookie or request header is present). Otherwise I see a massive screw up potential if multiple devs hijack the same container and calls to upstreams are being multiplied (when mirroring is used)

**Comment by aviramha** [comment]
Hey @wirtsi!
We're glad to hear that. In terms of priority, what would you prefer - 
1. conditional intercepts
2. mirroring in mesh

As any team, we have to prioritize and we started working on 2 but maybe we should shift our priority to 1.

Thanks

**Comment by wirtsi** [comment]
Oh cool, I even get to participate in the decision making, thanks 👍 

I guess the conditional intercepts are more interesting for me, let me elaborate

* We have a bunch of teams working on different APIs and frontends, each team is in a K8S namespace, istio/gloo mesh sits on top of if it for cross-cluster communication and security (which namespace can speak to whom etc)
* I as a developer am working on a feature for an API that is called
  * from the browser via a public URI mount in the VirtualService (Gloo Mesh calls them RouteTable) ... so the browser calls /api/myapi and the K8S Ingress and what not send the request to the API
  * from other services in the cluster

So I spin up my software on my development machine and I intercept the traffic on the development K8S deployment of my API

If I enable traffic mirroring then the request will hit the original pod and my machine. For data-changing requests, I can see this as quite problematic because then the writes to a database (or other API) will be duplicated, that can probably create havoc.

Also I am unsure what happens if multiple developers (working on different features) intercept the pod, does this work? Do I multiply the write requests even?

So for larger organisiations, the mirroring might get in the way more often (even though the feature is cool :-) )

What I would imagine should happen: I can eg. set a header on the incoming request (eg. X-Mirrord-Intercept: wirtsi) and only if I am intercepting a pod along the call path, it is forwarded to my machine.

If you configure your systems to pass along this header to subsequent calls (ie. my API calls API X), I would even be able to also intercept the pod that runs API X and process it locally.

Does that make sense? I have been thinking around this issue for a while. What I like with mirrord is that I can use all the Ingress definitions (aka URI mounts) that exist in the cluster ... so I don't need to configure a local reverse proxy to know all the URI and where to send them to.

 Plus I get some sort of VPN into the cluster to call internal resources. Which works better than telepresence by the way, because with telepresence there is no way to call Istio entities (eg .ServiceEntries) https://github.com/telepresenceio/telepresence/issues/2717

**Comment by aviramha** [comment]
Thanks for the elaborate response. That's great to hear such detailed use cases so we can build better for you.
> Also I am unsure what happens if multiple developers (working on different features) intercept the pod, does this work? Do I multiply the write requests even?

Only one of the developers will receive the request. The rest should be able to mirror it though.

> Does that make sense? 
Totally. It's part of our roadmap.

Currently our plan is to add this feature after we release our operator. The operator will add the "multi player" features that will help teams/organizations work together without interfering with each other.
The current mirrord project is very standalone - it has no way of syncing/communicating with other devs using mirrord at the same time, and the operator will orchestrate the mirrord usage, including multiple pod intercepts/different devs working on same pod/deployments at the same time.

I would love to hear more of your feedback on that!

**Comment by wirtsi** [comment]
Nice ... so this operator thingy sounds like it's the next step to what is needed. Looking forward to testing it out. I would assume that the conditional intercepts is also orchestrated via this operator. 

What I am thinking ... the way I understand mirrord is that it runs on level 4, so it basically has no idea what k8s is doing but creates iptables entries (or however you do it) in the pod that intercept the traffic and routes it to my machine via some sort of VPN between the pod and the layer running on my machine. Would you be able to access HTTP headers with this solution? 

Bests & thanks

**Comment by aviramha** [comment]
You understand it correctly. We plan to start decoding protocols soon, starting with HTTP so we can conditional filter based on HTTP headers, route, methods, etc.

**Comment by aviramha** [comment]
hey @wirtsi,
I'd love to chat a bit more on calendly/Discord if you have 30 min.
If you're willing, feel free to pick a spot here:
https://calendly.com/aviram-5/30min
