### ISSUE TITLE
SIP binaries support on macOS

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#649]
Currently we don't load into sip protected binaries on macOS. We have a way to fix it, need to implement.
If you face a use case where mirrord failed to load on macOS, please upvote/comment on this ticket with details so we can prioritize it accordingly.

**Comment by t4lz** [comment]
Status update: 
https://github.com/metalbear-co/mirrord/pull/706
Makes it possible to run a sip protected binary with mirrord, also via a shebang chain.
However, we don't yet bypass SIP for binaries that are executed by the executed binary. So things like bash scripts, where usually almost each command is starting some SIP protected binaries won't work on Mac as expected yet. Working now on supporting this.

Small note: we should now put a hash of the original file in the path of the patched file, so that if you write a bash script with a shebang, run it with mirrord, we patch it and save it, then you change your script and run it with mirrord again, we now patch the new version, and not use the old patched version.

**Comment by t4lz** [comment]
Additional note: we should probably mark all the generated files as excluded from filesystem hooks.
Maybe even walk the shebang chain also on Linux to mark all to be ignored regardless of SIP?

It seems for example that when running a script with this shebang `#!/bin/bash` bash `open`s the file of the script for reading (and does not find it if FS is not disabled).

Are there scenarios where a user would want some scripts/commands to be read from the pod?

**Comment by aviramha** [comment]
I agree but the filter should probably be extension of file and that should be general enough.

**Comment by aviramha** [comment]
> Small note: we should now put a hash of the original file in the path of the patched file, so that if you write a bash script with a shebang, run it with mirrord, we patch it and save it, then you change your script and run it with mirrord again, we now patch the new version, and not use the old patched version.

Agree. Create an issue on that, we'll probably wait a bit with that as that's pretty edgy, but ofc we want to fix it.

**Comment by t4lz** [comment]
Created. https://github.com/metalbear-co/mirrord/issues/717
Should be very easy though, if it's the 1 line change I think it is, I would include it in the PR for this issue, if that's ok.

**Comment by aviramha** [comment]
> Created. #717 Should be very easy though, if it's the 1 line change I think it is, I would include it in the PR for this issue, if that's ok.

Wouldn't bother right now. It might seem simple, but testing/actual running might become complicated.

**Comment by t4lz** [comment]
Status update: while testing the new hook with bash scripts, found out that the children processes get the environment the application (in that case, bash) started with, without the existing-agent variables. So I'm now adding handling for that in the hook (check if env vars passed in `execve` include the agent vars, if they don't create new array that does include and pass that instead).

**Comment by t4lz** [comment]
Still missing: support when running from an IDE.

**Comment by aviramha** [comment]
> Still missing: support when running from an IDE.

I believe this should be a separate issue - I think in most cases IDE resolves to the real binary so shebang cases are okay, and usually binaries ran aren't SIP.
Having said that, do create the issue and let's raise suggestions on how it would work, until someone faces it then we'll prioritize it.

**Comment by t4lz** [comment]
Tracking SIP IDE support on https://github.com/metalbear-co/mirrord/issues/747 :)

**Comment by t4lz** [comment]
SIP supported with the exceptions of #747 and the theoretical situation described in https://github.com/metalbear-co/mirrord/pull/759#issuecomment-1319969427.
