### ISSUE TITLE
Ventura dylib issue

### ISSUE THREAD

**Issue by alairock** [metalbear-co/mirrord#677]
### Bug Description

After installing ventura on my M1 macbook, I started seeing this error:

```
dyld[28029]: terminating because inserted dylib '/Users/{user}/.vscode/extensions/metalbear.mirrord-3.5.3-darwin-arm64/libmirrord_layer.dylib' could not be loaded: tried: '/Users/{user}/.vscode/extensions/metalbear.mirrord-3.5.3-darwin-arm64/libmirrord_layer.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64,arm64e', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Users/{user}/.vscode/extensions/metalbear.mirrord-3.5.3-darwin-arm64/libmirrord_layer.dylib' (no such file), '/Users/{user}/.vscode/extensions/metalbear.mirrord-3.5.3-darwin-arm64/libmirrord_layer.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64,arm64e', need ''))
dyld[28029]: tried: '/Users/{user}/.vscode/extensions/metalbear.mirrord-3.5.3-darwin-arm64/libmirrord_layer.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64,arm64e', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Users/{user}/.vscode/extensions/metalbear.mirrord-3.5.3-darwin-arm64/libmirrord_layer.dylib' (no such file), '/Users/{user}/.vscode/extensions/metalbear.mirrord-3.5.3-darwin-arm64/libmirrord_layer.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64,arm64e', need ''))
```

The path `/System/Volumes/Preboot/Cryptexes/OS/User/*` does not exist. 

I am unable to start mirrord from inside vscode as a result of this error.

### Steps to Reproduce

1. Installed mirrord (v3.4, in my case)
2. Upgrade macos to Ventura on my M1
3. Got error as shown above
4. Updated mirrord to latest (3.5.2 at the time of this report)
5. Continued to get error as shown above

### Your operating system and version

macos Ventura

### Local process

/opt/homebrew/bin/go: Mach-O 64-bit executable arm64

### Additional Info

Let me know if I need to provide supplemental information. Thanks!

**Comment by aviramha** [comment]
Thanks for reporting this @alairock ! I'm sorry for the inconvenience.
I'm actually on Ventura and it works for me so it's a bit of a puzzle.
Can you please specify what go version you're running `go version`?
Also, can you run `file BINARY` on the built binary from go?
The problem seems to be that the binary is ran doesn't have an architecture.. which is, weird. the `file` command might shed some light on it.

**Comment by alairock** [comment]
`go version`
```
go version go1.19.2 darwin/arm64
```

`file BINARY`
```
{filename}: Mach-O 64-bit executable arm64
```

**Comment by aviramha** [comment]
Thanks for the report.
It's a confirmed issue with macOS new version, we're still investigating what's changed from macOS side. I'll keep this issue updated.

**Comment by aviramha** [comment]
Hey,
We shipped a patch. I tested it and appears to work on my setup. Please let us know if it's okay now.

**Comment by aviramha** [comment]
> Perfectly! Thank you so much for tackling that! How do I buy you a coffee???

You're welcome. Thanks for reporting it :)
We'd actually love to hear some feedback over video if you're up - we want to understand better our user base and make the product even better.
If you're up for it, you can pick [a time slot here.](https://calendly.com/d/drb-fg3-8m2/metalbear-meeting)
