### ISSUE TITLE
Support mirroring/intercepting traffic from entire deployment (all pods)

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#685]
Currently when impersonating a deployment we actually impersonate the first pod in it. We should instead support impersonating the entire deployment. This means we should mirror or steal incoming traffic to all the pods rather than just the first one.

**Comment by itaischwartz** [comment]
Is #571 different or duplicate? Any news regarding this?

**Comment by aviramha** [comment]
Hey,
This feature was developed as part of the mirrord operator (mirrord for teams - commercial version), currently in closed beta.
We will update the docs and close this issue once it goes GA.

**Comment by eyalb181** [comment]
mirrord for Teams is currently in open beta, which can be accessed by signing up to the waitlist on https://mirrord.dev/. Closing this.
