### ISSUE TITLE
IntelliJ extension: mirrord steals traffic although `MIRRORD_AGENT_TCP_STEAL_TRAFFIC` is set to `false`

### ISSUE THREAD

**Issue by jamowei** [metalbear-co/mirrord#687]
Hi, I discovered a problem, when using the new 3.6.0 version of the IntelliJ extension.
following env vars are set by the extension when starting a debug session with mirrord enabled:
```
DEBUGGER_IGNORE_PORTS_PATCH=45000-65535
DYLD_INSERT_LIBRARIES=/Users/jamowei/Library/Application Support/JetBrains/IntelliJIdea2022.2/plugins/mirrord/libmirrord_layer.dylib
LD_PRELOAD=/Users/jamowei/Library/Application Support/JetBrains/IntelliJIdea2022.2/plugins/mirrord/libmirrord_layer.so
MIRRORD_ACCEPT_INVALID_CERTIFICATES=false
MIRRORD_AGENT_RUST_LOG=INFO
MIRRORD_AGENT_TCP_STEAL_TRAFFIC=false
MIRRORD_EPHEMERAL_CONTAINER=false
MIRRORD_FILE_OPS=false
MIRRORD_IMPERSONATED_TARGET=pod/user-context-778cd9b74f-9mh5b
MIRRORD_OVERRIDE_ENV_VARS_INCLUDE=*
MIRRORD_REMOTE_DNS=true
MIRRORD_SKIP_PROCESSES=
MIRRORD_TARGET_NAMESPACE=ita
MIRRORD_TCP_OUTGOING=true
MIRRORD_UDP_OUTGOING=true
RUST_LOG=INFO
```
I would expect that mirrord only mirrors the traffic instead of stealing it. But in my case, mirrord is stealing the traffic although `MIRRORD_AGENT_TCP_STEAL_TRAFFIC` is set to `false`!?
Should it be not set as env var otherwise when it is not enabled in the dialog!?
What is the default for env vars which contains a boolean value? (""/"true" or "false"/"true")

Thanks!

**Comment by infiniteregrets** [comment]
> I tested this behavior with also with the current version of the extension in master branch and there I don't have the issue... It's a bit confusing 🙈

I am kinda unable to reproduce this issue.. testing with the sample java application you linked, it seems to be working fine? we didn't make any latest changes to the extension for env vars in main branch

**Comment by jamowei** [comment]
Ok, thanks for the fast reply. Then I have a local problem in my current IntelliJ... I close this for now.
