### ISSUE TITLE
Add the ability to pause the remote pod

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#712]
Today, mirrord runs side-by-side with the existing pod/s. Many users want to "replace" the remote pod.
I think the best, nicest, approach wouldn't be to really replace the replicaset with our agent, but still run it side by side, making the agent send `SIGSTOP` to the pod's process, then `SIGCONT` when agent finishes running.
This way we're just pausing the activity of the original pod.

Small hint-  I think we should have a loop that sends SIGSTOP every few seconds, as there might be some OS stuff that will send `SIGCONT` without us knowing/wanting.

Suggestion - flag would be `--pause` `-p`
- We need to test it on multiple runtimes, so this should be covered in e2e, not just integration testing.
- Manually test few frameworks (Python, Java, Go) to see how they behave with this method.
- Check a scenario where the remote pod has health checks - I assume the local service would answer for those so k8s won't mark it as not ready / dead

**Comment by t4lz** [comment]
Should we use [docker's `pause` command](https://docs.docker.com/engine/reference/commandline/pause/#examples) if docker is the container's runtime?

And maybe if it's not docker we can still use [cgroup freezer](https://www.kernel.org/doc/Documentation/cgroup-v1/freezer-subsystem.txt) which is apparently what docker uses to pause?

**Comment by aviramha** [comment]
I wouldn't bother with `docker` pause as it's not the common runtime.
`cgroup freezer` sounds cool but also overkill for now if we already went with the sigstop..

**Comment by t4lz** [comment]
Saw your reply too late. But now we have a neat implementation using the docker/containerd API to pause the container instead of doing it ourselves :)

**Comment by t4lz** [comment]
Is adding this feature to the IDEs part of this issue or should I open separate issues for that?
(PRs would be separate either way I guess)

**Comment by aviramha** [comment]
> Is adding this feature to the IDEs part of this issue or should I open separate issues for that? (PRs would be separate either way I guess)

No, this feature should be possible to enable from the config file - VS Code already uses it and IntelliJ is underway.

**Comment by t4lz** [comment]
Stable status tracked in #809, support for ephemeral tracked in #795.

**Comment by bcouetil** [comment]
That exactly what is preventing me from using Telepresence 2.

Many thanks 🙏🎉

**Comment by aviramha** [comment]
@bcouetil Thanks for letting us know! It'll make us prioritize stabilizing this feature :) #809 
Let us know if you have any more feature requests/feedback.
