### ISSUE TITLE
 Example for golang

### ISSUE THREAD

**Issue by koolay** [metalbear-co/mirrord#718]
I can't find any doc or example for golang.

**Comment by infiniteregrets** [comment]
hey @koolay, golang should work with mirrord just like any other language. We hooked golang by creating a trampoline between rust and assembly, you can read more about it here https://metalbear.co/blog/hooking-go-from-rust-hitchhikers-guide-to-the-go-laxy/ and also refer to the FAQ https://mirrord.dev/docs/overview/faq/ (in case of statically linked binaries)
In general, please refer to this example: https://mirrord.dev/docs/overview/real-world-example/

Besides this, you can also look at the E2E tests, for some quick examples with Go https://github.com/metalbear-co/mirrord/blob/main/tests/src/sanity.rs#L615

**Comment by aviramha** [comment]
Closing. Please let us know if we can help.
