### ISSUE TITLE
Add example config file

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#720]
For users to use as an example, for an easy and quick place to find settings in, and maybe for copying and using as a template to start their config from.
The documentation of each field should be included directly above it as a comment.
Maybe put the defaults as values of fields that have defaults, or at least comment the default above the field.

It would be nice if this would be generated automatically with the schema (or out of the schema) if that's easy to do, but that's not a must in my opinion.

**Comment by eyalb181** [comment]
Thanks @opeolluwa !
Our configuration follows the json schema specified [here](https://raw.githubusercontent.com/metalbear-co/mirrord/main/mirrord-schema.json). Our CI keeps this file up to date with the code. The following steps would need to be completed:

### Example File Generation Script
- We'd need a script that generates an example configuration file based on this schema. It should be a .toml file to support documentation. 
- Ideally it would generate a configuration file with the most potential branching. For example, the feature->fs key can take true/false as a value, or an object - we'd ideally want the example configuration file to use the object option.
- However, an initial version of the script that just uses the default option (or even the first option) is acceptable. The important thing is for the script to be deterministic and generate the exact same file whenever it's run on the same schema.
- The above script should be added to the scripts/ directory.

### Adding the example configuration to the repo + linting
- We'd need to add the generated example file to the repository (e.g. under mirrord/config/example-config.toml). A step should be added to the CI workflow that insures the file is up to date with the current schema.

That's it, let me know if you have any questions!

**Comment by opeolluwa** [comment]
@eyalb181  To be sure, 

the task requires a script that generates a sample config file as `toml` using the provided schema. In addition, this schema will be updated from time to time by the CI and once it does a new `toml` config file should be created.

**Comment by opeolluwa** [comment]
@eyalb181  To be sure, 

the task requires a script that generates a sample config file as `toml` using the provided schema. In addition, this schema will be updated from time to time by the CI and once it does a new `toml` config file should be created.

**Comment by eyalb181** [comment]
@opeolluwa The first part is right - it requires a script that generates a sample config file.
Re the second part - the schema is updated manually by devs whenever e.g. a new configuration type is added, using the `check_schema_file_exists_and_is_valid_or_create_it` test in mirrord/config/src/lib.rs. Whenever that happens, we'd also want the devs to manually run the sample generation script (it can even be run as part of `check_schema_file_exists_and_is_valid_or_create_it`, since they always have to be run together anyway).
Finally, to make sure we don't forget to generate a new sample file if the schema changed, we'd want to add a CI step that makes sure the schema matches the sample file.

**Comment by opeolluwa** [comment]
Oh great!

**Comment by opeolluwa** [comment]
So essentially the core task is about getting creating the config.

**Comment by eyalb181** [comment]
I think this was pretty much covered with @meowjesty 's work on the configuration.
