### ISSUE TITLE
SIP bypassing for main application also on IDE

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#747]
We Bypass SIP on two occasions: executing the user's application, and when the application executes other executables.
The first one is currently only done in the CLI, so if a user tries to run a SIP application (Maybe a bash script, if there is IDE support for that?) in the IDE with mirrord, the layer would not be loaded into the application, and the application would run alone.

The second kind is handled also on IDEs, so if the user's application is not SIP, but executes SIP binaries, we do handle that (by hooking `execve`), assuming the executable's path is ignored by the file hooks (otherwise we would try to read the file for SIP handling, then we would hook the file open, try to open it in the cloud, not find it, return "File not found", the SIP detour would fail, and the executable would be executed without the layer loading into it).

If you would like to have support for executing SIP binaries with mirrord in an IDE, please let us know and we will prioritise it :)

**Comment by t4lz** [comment]
Whenever there are developments in this issue, **the part about SIP in the [FAQ](https://github.com/metalbear-co/mirrord.dev/blob/main/content/docs/overview/faq.md) should be updated accordingly.**

**Comment by t4lz** [comment]
In vscode we modify the debug configuration on launch in order to inject the layer. Unfortunately there is no universal "executable" configuration field that specifies what will be the command that is run. The value of the `program` field is just an argument to the executable, when running programs written in interpreted languages (`config.program` might be `main.py`, but the executable that has to run is the python interpreter).
I think we could sidestep SIP by replacing the interpreter, and debugging would still work, but I am not sure of it.
If we want to replace the interpreter the same way we set the environment, by modifying the debug configuration, we would have to have custom code for each interpreted language, and we would only support sidestepping SIP for those debug types. This is because the interpreter config field is different for each debug type.
For example, with the built-in debugger type `node`, [`config.runtimeExecutable` sets the interpreter](https://code.visualstudio.com/docs/nodejs/nodejs-debugging), but [for `python` its `config.python`](https://code.visualstudio.com/docs/python/debugging#_python).
This approach might lead to a situation where users decide to use some new interpreted language on Mac with a dedicated vscode debugger extension, and we would have to quickly add a couple of lines to our extension's code in order to support that debug type. The change itself would not be difficult, we would just have to find out the name of the field that is used to specify the interpreter with that debugger, and add
```typescript
if (config.type === "thisnewdebugger") {
    let patched_interpreter_path = sip_patch(config.interpreter); // simplified code
    config.interpreter = patched_interpreter_path;
}
```
So supporting new debuggers would probably mostly not be a problem, but users might have to wait a bit for support, and some users might just give up on mirrord without ever asking us to add support for their weird debugger.

Is this ok, or do you think there is a good way for us to switch the executable that is being run in a way that is debugger-type-agnostic?

My guess is that if there is another way to do it it's so complicated it's not worth it, but I wanted to write all of this down so that you can let me know if I'm wrong about this.

There is another way I can think of, but it has many flaws. One of them is that it assumes the interpreter executable is always going to be specified as just the name (`python`, `node`) and not as a path, so if that assumption is wrong this method will not do.
1. We iterate all configuration fields in the assumption of one of them has to be the interpreter executable if this debug type is of an interpreted language (if it's not interpreted we're fine anyways). We try to SIP-patch each of those fields. Any successfully created patched binaries will be created in mirrord's temp dir.
2. We put mirrord's temp dir at the front of the PATH environment variable.
Now when the interpreter is executed, the patched version is the first in PATH so it's the one that is going to be executed.

**Comment by aviramha** [comment]
I think it's okay to have implementation per launch type for time being.

**Comment by t4lz** [comment]
Done for vscode (for node and python - other config types need to be added to a mapping) in #1069.
Still not supported on JetBrains.

**Comment by aviramha** [comment]
Did we experience this on JetBrains?

**Comment by t4lz** [comment]
> Did we experience this on JetBrains? if not I suggest to close this and open when we have a solid situation :)

Ok, closing.

If you are a mirrord user and would like to have support in the mirrord JetBrains plugin for running interpreted scripts where the interpreter is SIP protected (e.g. because it has a `#!env ...` shebang), please comment here and we'll prioritise adding support for that.
