### ISSUE TITLE
`capture-error-trace` doesn't log application errors

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#753]
### Bug Description

It seems to only capture mirrord's errors, but if mirrord behaves 'normally' but causes the application to malfunction, we miss it. It also doesn't seem to show the log with the github link.

### Steps to Reproduce

Run mirrord with `capture-error-trace`, e.g.:
`RUST_LOG=mirrord=trace mirrord exec --target deployment/busybox --steal --no-fs --capture-error-trace -x=*  -- npx ts-node src/repro.ts`

### Your operating system and version

MacOS Ventura

### Local process

npx

**Comment by aviramha** [comment]
not sure if we can do that tbh.. the app writes to stdout/err and making it work sounds complicated.

**Comment by eyalb181** [comment]
I'm not sure it's worthwhile to have the feature otherwise - might lead people to just send us unhelpful logs (rather than just running with RUST_LOG=trace and copy-pasting).
