### ISSUE TITLE
mirrord crashes when running `bash -i`

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#756]
### Bug Description

The following error is displayed (full logs attached under Additional Info):
`malloc: unknown:0: assertion botched
malloc: block on free list clobbered
Aborting..../.workspace/runtime/src/shell.sh: line 6: 383940 Aborted                 (core dumped)`

It's not a memory thing though.

### Steps to Reproduce

Run `bash -i` with mirrord

### Your operating system and version

TBD (some Linux)

### Local process

bash

### Additional Info

[mirrord-bash.log.txt](https://github.com/metalbear-co/mirrord/files/10034026/mirrord-bash.log.txt)

**Comment by aviramha** [comment]
It doesn't happen when running just bash, without `-i`. I'm not sure what that even means in this context.
It seems to happen 80% of the time, attaching relevant logs.
https://gist.github.com/aviramha/9d7a003b1c177eab3a0ba058c14eb9fa

**Comment by aviramha** [comment]
I investigated deeper, and found out that it seems fixing this would require quite big change (it seems like a ctor/tokio/parking_lot integration issue, where ctor shouldn't be used to create threads.. and changing this behavior might cause new problems).
I tend to believe that this use case is very niche, especially that it doesn't happen with regular bash + without specifying `-i`. @mentos1386 please let us know how important this to you.

**Comment by aviramha** [comment]
I think that #763 solves it/reduces the odds of the crash, yay? :)

**Comment by aviramha** [comment]
We just released 3.11. Please let us know if that fixed it for you.
