### ISSUE TITLE
create mirrord ls: list targets for use by extensions

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord#811]
`mirrord ls` will list all the possible targets from kube API eliminating the need for extensions to interact with the kube API, refer https://github.com/metalbear-co/mirrord/issues/780

**Comment by eyalb181** [comment]
Is it going to list pods? Deployments? Both?

**Comment by aviramha** [comment]
Initially pods (to provide same functionality as current extension) and later on we'll decide if deployments will be a flag or just print it all together .

**Comment by eyalb181** [comment]
IMO lets add a `type` flag from the outset so we don't have to break the API later on (plus it makes sense)

**Comment by aviramha** [comment]
> IMO lets add a `type` flag from the outset so we don't have to break the API later on (plus it makes sense)

Yeah the idea is to have `--output`/`--format` similar to other CLIs. Options would be `table/json`.
Since this is hidden at first, I think defaulting to json then adding the optional param makes more sense (just to be able to ship in smaller parts)

**Comment by aviramha** [comment]
Create new issue for table format please.
