### ISSUE TITLE
Add Pycharm Plugin

### ISSUE THREAD

**Issue by ni-todo-spot** [metalbear-co/mirrord#819]
I use pycharm as my IDE for python projects.

Would be great if there was a plugin for it

Cheers!

**Comment by t4lz** [comment]
Hi @ni-todo-spot, nice to hear that you want to use mirrord.
You're in luck, because mirrord already has a JetBrains plugin. It can be found in the plugin marketplace in PyCharm or on the [JetBrains Marketplace Website](https://plugins.jetbrains.com/plugin/19772-mirrord).
Let us know what you think after you try it out :)

**Comment by ni-todo-spot** [comment]
@t4lz 
Thanks for your quick reply, Highly appreciated!

I'v tried installing it in both Pycharm Professional & Community edition but did not succeeded 😞 

First I tried finding it in the "Plugins MarketPlace" - but I could not find such plugin there,
So then I followed your link in the the response above & downloaded it.
When I tried installing the plugin via "Install Plugin from Disk" option both IDE editions stated the

```
(Community Edition):
Plugin 'mirrord' (version '3.12.1') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is PC-223.7571.203
```

```
(Professional Edition):
Plugin 'mirrord' (version '3.12.1') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is PY-223.7571.203
```

For the record: I tried installing in:
```
PyCharm 2022.3 (Community Edition)
Build #PC-223.7571.203, built on November 30, 2022
Runtime version: 17.0.5+1-b653.14 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.watches.in.variables=false

Non-Bundled Plugins:
    com.intellij.plugins.watcher (223.7571.113)
    uk.co.hadoopathome.intellij.avro.intellijavroviewer (3.1.0)
    Docker (223.7571.212)
    net.seesharpsoft.intellij.plugins.csv (3.0.1-223)
    ru.adelf.idea.dotenv (2022.3)
```

And:
```
PyCharm 2022.3 (Professional Edition)
Build #PY-223.7571.203, built on November 30, 2022
Licensed to Nativ Issac
Subscription is active until January 5, 2023.
Evaluation purpose only.
Runtime version: 17.0.5+1-b653.14 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.watches.in.variables=false

Non-Bundled Plugins:
    uk.co.hadoopathome.intellij.avro.intellijavroviewer (3.1.0)
    Docker (223.7571.212)
    net.seesharpsoft.intellij.plugins.csv (3.0.1-223)
    ru.adelf.idea.dotenv (2022.3)
```

Perhaps I'm doing something wrong - can you please instruct me if so?

In any case - Thanks in advance!

Can't wait to start debugging using this 😄

**Comment by t4lz** [comment]
Oh, that's interesting, thanks for the additional information. We're looking into it and will update when we have a solution.

**Comment by ni-todo-spot** [comment]
Sweet 😄 Awesome You guys
