### ISSUE TITLE
panic when listening on `::` but do not have ipv6 in the cluster

### ISSUE THREAD

**Issue by mentos1386** [metalbear-co/mirrord#848]
### Bug Description

Running Nodejs default http server on a local machine that has IPv6 available, by defaults results in to listening on `::` "host"[1].

This makes mirrord crash.

[1] https://nodejs.org/api/net.html#serverlistenport-host-backlog-callback

A workaround is to explicitly set listening host to `0.0.0.0`.

### Steps to Reproduce

1. Start nodejs server using default host (or set it explicitly to `::`).
2. Run in mirrord where kubernetes cluster has no IPv6.
3. Crash

### Relevant Logs

```shell
mirrord has encountered an error and is now exiting.
thread 'tokio-runtime-worker' panicked at 'explicit panic', mirrord/layer/src/lib.rs:455:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-12-16T09:11:33.712727Z ERROR ThreadId(08) mirrord_layer: Error handling daemon message: IO(Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" })
Terminated
```

### Your operating system and version

Ubuntu 22.04.1 LTS (Jammy Jellyfish)

### Local process

node

### Local process version

v16

**Comment by infiniteregrets** [comment]
hi @mentos1386, i tried reproducing this but wasn't able to. 

Following is the simple node server I used:
```
const net = require('net');

const server = net.createServer((socket) => {  
  console.log('New connection from', socket.remoteAddress);

  socket.write('Hello world!\n');

  socket.on('data', (data) => {
    console.log('Received data from client:', data.toString());
  });

  socket.on('end', () => {
    console.log('Connection closed');
  });
});

server.listen(8080, () => {
  console.log('Server listening on', server.address());
});
```
locally I do have ipv6, but my remote cluster does not seem as I checked referring to this: https://kubernetes.io/docs/tasks/network/validate-dual-stack/

If you could provide some logs from the layer(RUST_LOG=mirrord=trace) and the agent(MIRRORD_AGENT_RUST_LOG=mirrord=trace), it would be very helpful! Thanks
