### ISSUE TITLE
Support stat operation for Golang on Linux

### ISSUE THREAD

**Issue by niconatalie** [metalbear-co/mirrord#856]
Related to this comment https://github.com/metalbear-co/mirrord/issues/789#issuecomment-1361130547

Some of our services are doing `stat` to do some check before opening the file, so it would be great if mirrord can support it.

Not a major blocker, feel free to treat this as low priority :)

**Comment by aviramha** [comment]
Removed macOS from title as we already support it there ;)
Thanks for the report!
