### ISSUE TITLE
Cannot run mirrord in vscode debug mode with custom launch script

### ISSUE THREAD

**Issue by niconatalie** [metalbear-co/mirrord#863]
### Bug Description

I created the simple setup to reproduce it in this repository https://github.com/niconatalie/mirrord-golang-vscode

It looks like the process isn't wrap with mirrord layer, the agent will start and stop after few second and the process will "just" run normally

### Steps to Reproduce

Follow instruction on https://github.com/niconatalie/mirrord-golang-vscode

### Your operating system and version

Ubuntu 18.04.6 LTS

### Local process

ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, with debug_info, not stripped

### Local process version

3.14.1

**Comment by aviramha** [comment]
Hey,
the issue is most probably due to dlv version we don't support - please update to latest one (1.20).
When using the extension we provide our own dlv but in this case you're running dlv on your own so we can't make the switch automatically ;)

**Comment by aviramha** [comment]
Thought about it more - I think you're attaching in that scenario? if so, you have to run `dlv` that listens with mirrord as well...
