### ISSUE TITLE
Tidy actions

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#874]
We have many warnings in our GitHub actions regarding pending deprecations. We should prepare in advance and change all actions to work properly.

**Comment by infiniteregrets** [comment]
i think those warnings are from the actions we are using not being updated, we already fixed the set-output deprecation

**Comment by infiniteregrets** [comment]
pending new release on, Apple-Actions/import-codesign-certs and actions-rs/toolchain's https://github.com/actions-rs/toolchain/pull/224 to merged for all warnings to be fixed. some will be fixed when #883 is merged

**Comment by infiniteregrets** [comment]
should be closed by #1494
