### ISSUE TITLE
No "Enable/Disable mirrord" toggle button in new Intellij UI

### ISSUE THREAD

**Issue by Chr1stian** [metalbear-co/mirrord#881]
### Bug Description

No "Enable/Disable mirrord" toggle button in new Intellij UI

### Steps to Reproduce

1. Go to Appearance & Behavior in Intellij
2. Click "Enable new UI" in the New UI submenu
3. Watch the mirrord button dissapear

### Your operating system and version

MacOS Ventura 13.1

### Local process

Intellij

**Comment by aviramha** [comment]
Thanks for the report. We'll look into it.

**Comment by aviramha** [comment]
Fixed in #882 .
It will be released as part of 3.16.0/3.15.3 - until then you can either disable New UI or use the customization feature to add the buttons yourself.
