### ISSUE TITLE
Only show the outdated version messages on JetBrains IDEs if the new version is already available in the marketplace.

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#891]
Whenever a new version of mirrord is available, the user is currently presented with a suggestion to update it:
![image](https://user-images.githubusercontent.com/12370607/210278462-c3659d78-0f9d-4041-990e-13b2fe2a72f2.png)

But if the new version is not available on the JetBrains marketplace yet, when clicking `update`, the user would be presented with the plugin's page where there would be no `update` button if the current version is the latest available one.
![image](https://user-images.githubusercontent.com/12370607/210278655-2a014f29-d369-4958-93ed-ad6dd37cdb25.png)

It would be a better experience for the message only to be.shown if the new version is already available for JetBrains IDEs.

**Comment by infiniteregrets** [comment]
should be a minor fix, as we can do something like this:
```
curl -s 'https://plugins.jetbrains.com/api/plugins/19772/updates?channel=&size=1' | jq -r '.[0].version'
3.15.2
```
