### ISSUE TITLE
Add vscode ignore to VSCode extension

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#90]
As our CI complains:
```
 This extension consists of 5252 files, out of which 2627 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
```

Contributions welcome!

**Comment by TawalMc** [comment]
Hi, I'm junior web dev, and currently learn Rust, and want to contribue to this project.... 
So what can you do to help on this issues... ?

**Comment by aviramha** [comment]
Hi @TawalMc, That's great and you're more than welcome. Do you wish to work on this specific issue?
The work that needs to be done here is to use `.vscodeignore` file when building our extension ignoring files that doesn't matter, making sure when we package the extension only required files are packed to reduce extension size.

**Comment by TawalMc** [comment]
Hi @aviramha , I'm sorry for the late response. I had some issues on windows with my rust setup so I installed a linux distro (manjaro) to be able to run this project.

Yes I want to work on this issues. Ok

**Comment by eyalb181** [comment]
@anuvratsingh Sure! @TawalMc is working on another issue. Go ahead and assign it to yourself, and hop on our [Discord](https://discord.gg/pSKEdmNZcK) if you need any help. Thank you!
