### ISSUE TITLE
JetBrains Plugin: mirrord.json config fs disabled not working

### ISSUE THREAD

**Issue by f-blass** [metalbear-co/mirrord#900]
### Bug Description

When using the config `"fs": "disabled"` in the `mirrord.json` config file of the JetBrains plugin I get the error
```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
```

Feature is described here: https://mirrord.dev/docs/overview/configuration/#tab-pane_feature_fs_anyOf_i1_anyOf_i0

### Steps to Reproduce

1. Use `mirrord.json` config as below
1. Start a hello world example (in my case GoLang) with mirrord plugin enabled
1. After selecting the target pod the error messages appears

```json
{
    "accept_invalid_certificates": false,
    "feature": {
        "network": {
            "incoming": "mirror",
            "outgoing": true
        },
        "fs": "disabled",
        "env": true
    }
}
```

### Your operating system and version

MacBook Pro M1 Max; macOS 13.1 (22C65)

### Local process

/private/var/folders/lb/y5b0sgds5nv7z_vr4y9z68kc0000gn/T/GoLand/___1go_build_playground_http: Mach-O 64-bit executable arm64

### Additional Info

mirrord plugin version 3.16.2

**Comment by aviramha** [comment]
It seems that the page is outdated, can you try `local` instead of `disabled`? (disabled is deprecated, replaced by local)

**Comment by aviramha** [comment]
Okay reading the error now I see that it's saying it's not a valid JSON which is weird. 
Can you upload the `mirrord.json` file as a file?

**Comment by f-blass** [comment]
[mirrord.json.txt](https://github.com/metalbear-co/mirrord/files/10345248/mirrord.json.txt)
[mirrord-v2.json.txt](https://github.com/metalbear-co/mirrord/files/10345247/mirrord-v2.json.txt)

Renamed to .txt because Github does not allow .json files

**Comment by aviramha** [comment]
Can you click `GoLand` -> `About GoLand` -> `Copy`
then paste output here? I can't reproduce it so I'm thinking maybe it's some GoLand version or JDK/Java..

**Comment by f-blass** [comment]
Thanks for the super quick response again! Yes it is indeed working with `"fs" : "local"`. 

Still interesting to see this error. When using any other non-existing value I just see the error message `failed launch`

**Comment by aviramha** [comment]
Yes, it's kinda cryptic error but for good reason (i.e it's not a bug that can be handled by user)
The issue is when using `disabled` it prints an error that it's deprecated into the stdout, so when we try to parse the stdout instead of getting a valid json we read "deprecated" message then fail on it.
