### ISSUE TITLE
Further tests for HTTP header filtering.

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#911]
Some more stuff that we could/should test, but does not block the release of the feature.

- [x] Client sending multiple matching requests in the same connection.
- [x] Multiple requests in one connection, where some of the requests are unmatched.
- [ ] Valid HTTP responses to unmatched requests after invalid HTTP responses by buggy application on the same connection.

Please add to the list if you have more ideas (and check off the list any tests that were implemented).

**Comment by aviramha** [comment]
I think we have this already? @Razz4780

**Comment by Razz4780** [comment]
> I think we have this already? @Razz4780

I think first two cases are covered by E2E, but I don't recall seeing the third one.

**Comment by aviramha** [comment]
I think we can close - seems to be enough coverage and will add as we go.
