### ISSUE TITLE
Rust binary from `cargo run` still running locally after killing mirrord with ctrl+c and thus mirrord agent does not get removed on k8s

### ISSUE THREAD

**Issue by timonbimon** [metalbear-co/mirrord#956]
### Bug Description

I noticed that when I run mirrord with cargo watch and then hit ctrl+c to kill the process, the mirrord agent doesn't disappear. after some digging I found that it's because the underlying binary (in my case from our own crate epibator) is still running on my mac. once killed it also shuts down the mirrord agent.

```
❯ mirrord exec -a dev-`whoami` -n dev-`whoami` -t deployment/backend-core --fs-mode local --steal cargo -- watch -x 'run --bin epibator'
⠼ mirrord cli starting
New mirrord version available: 3.19.1. To update, run: `curl -fsSL https://raw.githubusercontent.com/metalbear-co/mirrord/main/scripts/install.sh | bash`.
⠹ mirrord cli starting
  ✓ ready to launch process
    ✓ layer extracted
    ✓ agent pod created
    ✓ pod is ready
[Running 'cargo run --bin epibator']
    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
     Running `target/debug/epibator`
{"timestamp":"2023-01-16T23:25:29.129597Z","level":"INFO","fields":{"message":"Running migrations for tenant testing"},"target":"epibator::db_connection","threadName":"main"}
{"timestamp":"2023-01-16T23:25:29.425890Z","level":"INFO","fields":{"message":"Running migrations for tenant luminovo"},"target":"epibator::db_connection","threadName":"main"}
{"timestamp":"2023-01-16T23:25:29.805984Z","level":"INFO","fields":{"message":"Starting server at 0.0.0.0:4999"},"target":"epibator","threadName":"main"}
^C
```

When running `cargo -- watch -x 'run --bin epibator'` without mirrord and hitting ctrl+c it does correctly kill the process from the epibator binary as well.

### Steps to Reproduce

Since you guys also use Rust, the first thing to try would probably be with any Rust binary of your own to see if you can re-produce it.

### Your operating system and version

macOS Moneterey, 12.5.1

### Local process

/Users/timon/.cargo/bin/cargo: Mach-O 64-bit executable arm64

### Additional Info

mirrord 3.18.2

**Comment by eyalb181** [comment]
Hey @timonbimon, thanks for reporting this! We've managed to reproduce this, will let you know when we release a solution.

**Comment by DmitryDodzin** [comment]
Hi, @timonbimon could you please try and see if version 3.22.0 fixes the problem if you add `--skip-processes cargo-watch`?

**Comment by timonbimon** [comment]
Yes that fixes it. thank you so much! 🙏

**Comment by timonbimon** [comment]
is this skip-processes now needed for any command one would want to run or just `cargo watch`?

**Comment by eyalb181** [comment]
The reason it's needed for `cargo watch` is that it has a signal handler that's in charge of killing its child processes, and mirrord somehow disrupts it, leading to the zombie processes you were seeing. So it's probably not necessary for other commands unless they behave the same way.
